#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS :   -s:                     do not split into several cff files (rare BGs only)

use Getopt::Std;
getopts('s');

print "\n";

$dir  = "/home/ceggel/workspace/test";

my @backgrounds = ("Bd2MuMuPi0", "Bd2MuMu", "Bd2PiMuNu", "Bd2PiKp", "Bd2PiPi", "Bu2MuMuMuNu",
		   "Bs2MuMu", "Bs2KpKm", "Bs2KmPi", "Bs2KmMuNu", "Bs2PiPi", "Bs2JpsiPhi", "Bc2MuMuMuNu",
		   "Bc2JpsiMuNu", "Lb2PPi", "Lb2PKm");


chdir($dir);

foreach $bg ( @backgrounds ) {
    
    
    $data = "/net/moor/export/data2/ursl/cmssw/CMSSW_1_3_6/rec";
    chdir("$data");
    $tmp = `pwd`;
    print "$tmp";

    @rbg = `ls -1 $bg-*.root`;
    $nof = $#rbg+1;
    print " ----> channel : $bg total $nof root files \n\n";
    
    chdir("$dir/input");
    system("rm -f $bg-*.cff");
    
    if ( !$opt_s ) {

	$stop = int(($#rbg+1)/3);
	if ( $bg eq "Bu2MuMuMuNu" ) { $stop = int(($#rbg-4)/3) ; }

	foreach $k ( 0 .. $stop-1 ) {

	    chop(@rbg[3*$k]); chop(@rbg[3*$k+1]); chop(@rbg[3*$k+2]);

	    system("echo \"replace PoolSource.fileNames = { \" > $bg-$k.cff");
	    system("echo \"  \\\"file:$data/@rbg[3*$k]\\\",\" >> $bg-$k.cff");
	    system("echo \"  \\\"file:$data/@rbg[3*$k+1]\\\",\" >> $bg-$k.cff");
	    system("echo \"  \\\"file:$data/@rbg[3*$k+2]\\\"\" >> $bg-$k.cff");
	    system("echo \"}\" >> $bg-$k.cff");

	}

	if ( ((($#rbg+1)/3.)- $stop) > 0. ) {
	    
	    $r = $stop;
	    system("echo \"replace PoolSource.fileNames = { \" > $bg-$r.cff");
	    
	    foreach $m ( 0 .. $#rbg-1 ) {

		if ( $m < 3*$stop ) { next; }
		chop(@rbg[$m]); 
		system("echo \"  \\\"file:$data/@rbg[$m]\\\",\" >> $bg-$r.cff");
	    }
	    
	    chop(@rbg[$#rbg]);
	    system("echo \"  \\\"file:$data/@rbg[$#rbg]\\\" \" >> $bg-$r.cff");
	    system("echo \"}\" >> $bg-$r.cff");
	}


    } else {
	
	system("echo \"replace PoolSource.fileNames = { \" > $bg.cff");
	
	foreach $k ( 0 .. $#rbg-1 ) {
	    
	    chop(@rbg[$k]); 
	    system("echo \"  \\\"file:$data/@rbg[$k]\\\",\" >> $bg.cff");
	}
	
	chop(@rbg[$#rbg]);
	system("echo \"  \\\"file:$data/@rbg[$#rbg]\\\" \" >> $bg.cff");
	system("echo \"}\" >> $bg.cff");
    }
}

system("rm -f Bu2MuMuMuNu-8.cff");

print "\n";

