#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS : -m: -1 or 1,2,3,...     min number of output file
#           -n: -1 or 1,2,3,...     max number of output file
#           -p: dry-run

use Getopt::Std;
getopts('m:n:p');

print "\n";

if ( !$opt_n ) {
    $opt_n = -1;
}

if (!$opt_m ) { 
    $opt_m = -1; 
}

$dir  = "/home/ceggel/workspace/test";

my @backgrounds = ("Bd2MuMuPi0", "Bd2MuMu", "Bd2PiMuNu", "Bd2PiKp", "Bd2PiPi", "Bu2MuMuMuNu",
		   "Bs2MuMu", "Bs2KpKm", "Bs2KmPi", "Bs2KmMuNu", "Bs2PiPi", "Bs2JpsiPhi", "Bc2MuMuMuNu",
		   "Bc2JpsiMuNu", "Lb2PPi", "Lb2PKm");


chdir($dir);

if ( !$opt_p ) { open(LOG, ">cmsRun.rare.log"); }

foreach $channel ( @backgrounds ) {

    @files = `ls -1 test-rare/$channel-*.cff`;

    foreach $fn ( 0 .. $#files ) {

	if ( $opt_n > 0 && $fn > $opt_n ) { next; } 
	if ( $opt_m > 0 && $fn < $opt_m ) { next; } 
	
	
	$cfg = "$channel-$fn.cfg";
	$log = "$channel-$fn.log";
	
	if ( -e "$cfg" )  { system("rm -f $cfg"); }
	
	system("cp test-rare/test-rare.cfg $cfg");

	system("perl -pi -e \"s/FILELIST/$channel-$fn/g\" $cfg");
	system("perl -pi -e \"s/OUTPUT/$channel-$fn/g\" $cfg");
	system("perl -pi -e \"s/CHANNEL/$channel/g\" $cfg");
	
	if ( $opt_p ) { 
	    
	    if ( -e "analyzer/rare_new/test/$log" ) { system("rm -f analyzer/rare_new/test/$log"); }
	    print "nice cmsRun $cfg \>\& analyzer/rare_new/test/$log\n";
	    system("touch analyzer/rare_new/test/$log"); 	
	    system("cat $cfg >> analyzer/rare_new/test/$log");
	    system("cat test-rare/$channel-$fn.cff >> analyzer/rare_new/test/$log");
	    
	} else {  
	    
	    if ( -e "analyzer/rare_new/$log" ) { system("rm -f analyzer/rare_new/$log"); }

	    $date = `date`; chop($date);
	    print LOG "$date \"nice cmsRun $cfg \>\& analyzer/rare_new/$log\"\n";

	    system("nice cmsRun $cfg \>\& analyzer/rare_new/$log");		
	    system("cat $cfg >> analyzer/rare_new/$log");
	    system("cat test-rare/$channel-$fn.cff >> analyzer/rare_new/$log");
	}
	
	system("rm -f $cfg");
    }
}    

if ( !$opt_p ) { close(LOG); }

print "\n";
