#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS :  -p: dry-run

#===============================================================
# Directory
# ---------
# $dir      = "/home/ceggel/workspace/test";
# $loca      = "/home/ceggel/workspace/test/test-local";
$output = "test";
#
#===============================================================


use Getopt::Std;
getopts('p');


$dir = `pwd`; chop($dir);
$loca = "$dir/test-local";

chdir($loca);
@files = `ls -1 test-*.cfg`;

chdir($dir);

if (-d "$output") {
    print "\n ----> Output files will be written to directory: $output\n\n";
} else {
    print "\n ----> Output directory \"$output\" does not exist, please create link first.\n";
    print "\n ----> ABORTING ...\n\n";
    exit;
}

if ( !$opt_p ) { open(LOG, ">cmsRun.local.log"); }

foreach $f ( @files ) {

    chop($f);
    ($run, $bla) = split(/\./,$f);

    $cfg = "$run.cfg";
    $log = "$run.log";
    
    if ( -e "$cfg" )  { system("rm -f $cfg"); }
    system("cp $loca/$f $cfg");
    


    $date = `date`; chop($date);

    if ( !$opt_p ) {     

	if ( -e "$output/$log" ) {  system("rm -f $output/$log"); }

	print LOG "$date \"nice cmsRun $cfg \>\& $output/$log\"\n";
	system("nice cmsRun $cfg \>\& $output/$log");		
	system("cat $cfg >> $output/$log");

    } else {

	print "$date \"nice cmsRun $cfg \>\& $output/$log\"\n";

    }

    system("rm -f $cfg");
}

if ( !$opt_p ) { close(LOG); }
