// Class: ReadBDT2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT2::BDT2
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.27/06       [334598]
Creator        : tinti_g
Date           : Fri Nov 25 17:07:31 2011
Host           : Linux lxbuild151.cern.ch 2.6.18-194.11.3.el5.cve20103081 #1 SMP Thu Sep 16 15:17:10 CEST 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/tinti_g/TMVA/test
Training events: 18364
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "80" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "35" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "4" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "18364" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT2 training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
alpha                         alpha                         alpha                         pointing angle                                                  'F'    [0.000245286530117,0.199997276068]
fls3d                         fls3d                         fls3d                         3D flight length significance                                   'F'    [7.00020456314,1958.77722168]
chi2/dof                      chi2_D_NDF                    chi2/NDF                      #chi^{2}/NDF                                                    'F'    [2.12198134064e-10,4.9998664856]
iso                           iso                           iso                           isolation                                                       'F'    [0.0614304021001,1]
m1pt                          m1pt                          m1pt                          m1pt (GeV)                                                      'F'    [4.50037288666,109.604484558]
m2pt                          m2pt                          m2pt                          m2pt (GeV)                                                      'F'    [4.00001239777,26.7605762482]
m1eta                         m1eta                         m1eta                         m1 #eta                                                         'F'    [-2.39863109589,2.399964571]
m2eta                         m2eta                         m2eta                         m2 #eta                                                         'F'    [-2.39909529686,2.39788198471]
docatrk                       docatrk                       docatrk                       doca (cm)                                                       'F'    [9.07465728233e-05,15.3859367371]
pvlip                         pvlip                         pvlip                         PV IP (cm)                                                      'F'    [-1.17734193802,1.16537666321]
closetrk                      closetrk                      closetrk                      N^{#DeltaR}_{trk}                                               'F'    [0,20]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN2 new BDT2Node
   
#ifndef BDT2Node__def
#define BDT2Node__def
   
class BDT2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT2Node ( BDT2Node* left,BDT2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT2Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT2Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT2Node*   fLeft;     // pointer to the left daughter node
   BDT2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT2Node::~BDT2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT2" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "alpha", "fls3d", "chi2/dof", "iso", "m1pt", "m2pt", "m1eta", "m2eta", "docatrk", "pvlip", "closetrk" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.000245286530116573;
      fVmax[0] = 0.199997276067734;
      fVmin[1] = 7.00020456314087;
      fVmax[1] = 1958.77722167969;
      fVmin[2] = 2.12198134064145e-10;
      fVmax[2] = 4.9998664855957;
      fVmin[3] = 0.0614304021000862;
      fVmax[3] = 1;
      fVmin[4] = 4.50037288665771;
      fVmax[4] = 109.604484558105;
      fVmin[5] = 4.00001239776611;
      fVmax[5] = 26.7605762481689;
      fVmin[6] = -2.39863109588623;
      fVmax[6] = 2.39996457099915;
      fVmin[7] = -2.39909529685974;
      fVmax[7] = 2.39788198471069;
      fVmin[8] = 9.07465728232637e-05;
      fVmax[8] = 15.3859367370605;
      fVmin[9] = -1.1773419380188;
      fVmax[9] = 1.16537666320801;
      fVmin[10] = 0;
      fVmax[10] = 20;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT2Node*)current->GetRight();
         else current=(BDT2Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(3.59459169842535);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN2(
0, 
0, 
-1, 1.33051, 1, -1, 0.0864715,-99) , 
4, 20.0141, 0, 0, 0.092978,-99) , 
NN2(
0, 
0, 
-1, 0.0392891, 0, -1, 0.00869779,-99) , 
3, 0.89796, 0, 0, 0.0243139,-99) , 
NN2(
0, 
0, 
-1, 0.0372383, 1, -1, 0.000424814,-99) , 
0, 0.0168913, 1, 0, 0.000773392,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.97885);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 7.96813, 0, 1, 0.775321,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.74248,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.433987,-99) , 
2, 0.27731, 1, 0, 0.541223,-99) , 
3, 0.921769, 0, 0, 0.697083,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.555071,-99) , 
NN2(
0, 
0, 
-1, 0.73499, 0, -1, 0.0784106,-99) , 
10, 0.527778, 1, 0, 0.127601,-99) , 
3, 0.84344, 0, 0, 0.404207,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.520171,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.113646,-99) , 
6, 1.45438, 1, 0, 0.39856,-99) , 
NN2(
0, 
0, 
-1, 0.818116, 0, -1, 0.0407478,-99) , 
3, 0.904076, 0, 0, 0.10698,-99) , 
NN2(
0, 
0, 
-1, 0.947857, 0, -1, 0.00667677,-99) , 
0, 0.0421727, 1, 0, 0.0124467,-99) , 
0, 0.02244, 1, 0, 0.0267561,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.27489);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.624744,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.307777,-99) , 
7, 0.933025, 1, 0, 0.477518,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.6189,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.105521,-99) , 
0, 0.0140798, 1, 0, 0.189092,-99) , 
6, -1.46556, 0, 0, 0.40383,-99) , 
NN2(
0, 
0, 
-1, 0.0189455, 1, -1, 0.0961263,-99) , 
3, 0.775182, 0, 0, 0.284489,-99) , 
NN2(
0, 
0, 
-1, 0.895714, 0, -1, 0.0329581,-99) , 
0, 0.0557319, 1, 0, 0.086762,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.877812);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.62904,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.349394,-99) , 
2, 1.38855, 1, 0, 0.538539,-99) , 
NN2(
0, 
0, 
-1, -0.97288, 0, -1, 0.27299,-99) , 
7, -0.800103, 0, 0, 0.436301,-99) , 
NN2(
0, 
0, 
-1, 0.018509, 1, -1, 0.108311,-99) , 
3, 0.700243, 0, 0, 0.358563,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.564978,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.108387,-99) , 
6, -1.33114, 0, 0, 0.449819,-99) , 
NN2(
0, 
0, 
-1, 1.0566, 1, -1, 0.15384,-99) , 
0, 0.114973, 1, 0, 0.271362,-99) , 
NN2(
0, 
0, 
-1, 0.849196, 0, -1, 0.0216559,-99) , 
3, 0.895714, 0, 0, 0.0799884,-99) , 
0, 0.0723779, 1, 0, 0.183418,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.753305);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.768137,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.390347,-99) , 
7, 1.86651, 1, 0, 0.725319,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.700597,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.270006,-99) , 
0, 0.0113746, 0, 0, 0.349233,-99) , 
3, 0.979592, 1, 0, 0.629458,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.560253,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.368502,-99) , 
0, 0.0427838, 0, 0, 0.457652,-99) , 
NN2(
0, 
0, 
-1, 0.038145, 1, -1, 0.2297,-99) , 
3, 0.825141, 0, 0, 0.359534,-99) , 
0, 0.0162734, 1, 0, 0.419006,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.662633,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.139186,-99) , 
6, -0.900481, 0, 0, 0.406762,-99) , 
NN2(
0, 
0, 
-1, 0.887388, 1, -1, 0.0850615,-99) , 
7, 0.932082, 1, 0, 0.295104,-99) , 
NN2(
0, 
0, 
-1, 0.100745, 1, -1, 0.0226015,-99) , 
3, 0.843572, 0, 0, 0.124881,-99) , 
0, 0.0723779, 1, 0, 0.250528,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.651997);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.721891,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.470565,-99) , 
0, 0.0335534, 1, 0, 0.665429,-99) , 
NN2(
0, 
0, 
-1, 0.592323, 0, -1, 0.430154,-99) , 
1, 11.5148, 0, 0, 0.586796,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524831,-99) , 
NN2(
0, 
0, 
-1, -0.0609248, 0, -1, 0.111917,-99) , 
3, 0.932972, 1, 0, 0.227442,-99) , 
1, 61.2196, 1, 0, 0.557966,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.654822,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.2674,-99) , 
7, -1.47436, 0, 0, 0.561292,-99) , 
NN2(
0, 
0, 
-1, 1.53913, 1, -1, 0.145271,-99) , 
6, 1.20114, 1, 0, 0.438992,-99) , 
NN2(
0, 
0, 
-1, 0.100745, 1, -1, 0.12107,-99) , 
3, 0.947857, 0, 0, 0.1918,-99) , 
0, 0.0446346, 1, 0, 0.303979,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.432549);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.576838,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.339293,-99) , 
7, -1.73286, 0, 0, 0.545985,-99) , 
NN2(
0, 
0, 
-1, 0.0422888, 1, -1, 0.28686,-99) , 
6, 1.86607, 1, 0, 0.514767,-99) , 
NN2(
0, 
0, 
-1, 0.0449329, 1, -1, 0.176441,-99) , 
3, 0.600323, 0, 0, 0.482633,-99) , 
NN2(
0, 
0, 
-1, 0.843572, 0, -1, 0.163845,-99) , 
0, 0.0945726, 1, 0, 0.362653,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.424173);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.608581,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.399264,-99) , 
4, 13.5011, 1, 0, 0.573671,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.215379,-99) , 
9, 0.00440868, 1, 0, 0.542685,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0893754,-99) , 
9, -0.00598926, 0, 0, 0.521868,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.523216,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.181194,-99) , 
6, -1.75316, 0, 0, 0.477413,-99) , 
NN2(
0, 
0, 
-1, 0.444444, 1, -1, 0.161057,-99) , 
6, 1.46718, 1, 0, 0.415732,-99) , 
NN2(
0, 
0, 
-1, 0.972196, 1, -1, 0.147691,-99) , 
3, 0.843572, 0, 0, 0.281222,-99) , 
0, 0.0446346, 1, 0, 0.365476,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.297059);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 61.2164, 1, -1, 0.455399,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.51472,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0769346,-99) , 
0, 0.0323029, 1, 0, 0.237021,-99) , 
7, 1.86488, 1, 0, 0.43491,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.513947,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.138805,-99) , 
6, -1.19309, 0, 0, 0.422401,-99) , 
NN2(
0, 
0, 
-1, 9.44444, 0, -1, 0.115068,-99) , 
0, 0.0565261, 1, 0, 0.242893,-99) , 
3, 0.687143, 0, 0, 0.399743,-99) , 
NN2(
0, 
0, 
-1, 0.975118, 0, -1, 0.120957,-99) , 
0, 0.144511, 1, 0, 0.357756,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.298516);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.543955,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.214143,-99) , 
1, 61.2164, 1, 0, 0.529526,-99) , 
NN2(
0, 
0, 
-1, 0.0323029, 1, -1, 0.235473,-99) , 
7, 1.86488, 1, 0, 0.503659,-99) , 
NN2(
NN2(
0, 
0, 
-1, 1.44615, 1, -1, 0.372248,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.578862,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.108427,-99) , 
10, 11.3333, 0, 0, 0.141945,-99) , 
3, 0.982625, 0, 0, 0.217725,-99) , 
0, 0.144494, 1, 0, 0.468297,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.597956,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.215093,-99) , 
7, -0.950961, 0, 0, 0.459743,-99) , 
NN2(
0, 
0, 
-1, 0.604985, 0, -1, 0.0341146,-99) , 
6, 1.60059, 1, 0, 0.38407,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510334,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.90375, 1, 0, 0.299879,-99) , 
NN2(
0, 
0, 
-1, 0.0799713, 1, -1, 0.0559617,-99) , 
10, 9.44444, 0, 0, 0.100983,-99) , 
0, 0.0559554, 1, 0, 0.198418,-99) , 
3, 0.687143, 0, 0, 0.417235,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.247027);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 1.86403, 1, -1, 0.473653,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.525082,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.203786,-99) , 
0, 0.0468688, 1, 0, 0.316576,-99) , 
2, 2.36064, 1, 0, 0.447083,-99) , 
NN2(
0, 
0, 
-1, 0.984072, 0, -1, 0.168687,-99) , 
0, 0.166686, 1, 0, 0.430647,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.538008,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.208059,-99) , 
6, 1.33453, 1, 0, 0.472555,-99) , 
NN2(
0, 
0, 
-1, 1.31592, 1, -1, 0.190549,-99) , 
2, 1.24861, 1, 0, 0.371967,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.608428,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.111204,-99) , 
3, 0.622001, 0, 0, 0.310137,-99) , 
NN2(
0, 
0, 
-1, 0.0796632, 1, -1, 0.0376633,-99) , 
10, 9.44444, 0, 0, 0.0928585,-99) , 
0, 0.0725757, 1, 0, 0.220308,-99) , 
3, 0.713215, 0, 0, 0.386871,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.264982);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.55084,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.351139,-99) , 
7, 1.86403, 1, 0, 0.535326,-99) , 
NN2(
0, 
0, 
-1, 0.926918, 1, -1, 0.230044,-99) , 
0, 0.166686, 1, 0, 0.520211,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531393,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.237365,-99) , 
7, -0.931816, 0, 0, 0.435527,-99) , 
NN2(
0, 
0, 
-1, 0.968138, 0, -1, 0.159735,-99) , 
0, 0.0726792, 1, 0, 0.310438,-99) , 
2, 2.36064, 1, 0, 0.484959,-99) , 
NN2(
NN2(
0, 
0, 
-1, 2.77731, 1, -1, 0.326085,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.559186,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.276672, 1, 0, 0.246657,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0449677,-99) , 
0, 0.105816, 1, 0, 0.226777,-99) , 
3, 0.713215, 0, 0, 0.433759,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.187674);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.016286, 1, -1, 0.460662,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.688633,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.24096,-99) , 
10, 2.22222, 1, 0, 0.411271,-99) , 
NN2(
0, 
0, 
-1, 10.5556, 0, -1, 0.0489694,-99) , 
0, 0.0670046, 1, 0, 0.204807,-99) , 
3, 0.57701, 0, 0, 0.443322,-99) , 
NN2(
NN2(
0, 
0, 
-1, 4.16636, 1, -1, 0.361848,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.564611,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.082284,-99) , 
4, 6.38375, 0, 0, 0.386144,-99) , 
NN2(
0, 
0, 
-1, -2.13259, 1, -1, 0.0358666,-99) , 
3, 0.973929, 0, 0, 0.124724,-99) , 
0, 0.0729301, 1, 0, 0.248799,-99) , 
2, 2.49993, 1, 0, 0.412335,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.17494);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524101,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.108693,-99) , 
9, -0.0169146, 0, 0, 0.515924,-99) , 
NN2(
0, 
0, 
-1, 0.911348, 1, -1, 0.066204,-99) , 
9, 0.016286, 1, 0, 0.507716,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50329,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.211938,-99) , 
2, 4.16636, 1, 0, 0.433896,-99) , 
NN2(
0, 
0, 
-1, 0.965272, 0, -1, 0.151208,-99) , 
0, 0.0729301, 1, 0, 0.307706,-99) , 
2, 2.49951, 1, 0, 0.478145,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.66545,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.103044,-99) , 
7, -0.785425, 0, 0, 0.469836,-99) , 
NN2(
0, 
0, 
-1, 0.517296, 0, -1, 0.00471989,-99) , 
6, 1.18338, 1, 0, 0.373429,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.574639,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.00772051, 0, 0, 0.20163,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0419023,-99) , 
0, 0.0670046, 1, 0, 0.185356,-99) , 
3, 0.582858, 0, 0, 0.456351,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.158195);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 2.36064, 1, -1, 0.444172,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.625448,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.120373,-99) , 
7, -0.785425, 0, 0, 0.454611,-99) , 
NN2(
0, 
0, 
-1, 0.517296, 0, -1, 0.00561714,-99) , 
6, 1.18338, 1, 0, 0.36493,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531424,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.00772051, 0, 0, 0.196036,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0416553,-99) , 
0, 0.0670046, 1, 0, 0.184087,-99) , 
3, 0.582858, 0, 0, 0.425869,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.165414);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.529589,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.224976,-99) , 
6, -2.13204, 0, 0, 0.520002,-99) , 
NN2(
0, 
0, 
-1, 0.837863, 0, -1, 0.267975,-99) , 
0, 0.1667, 1, 0, 0.507943,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501694,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.261177,-99) , 
2, 4.12051, 1, 0, 0.448801,-99) , 
NN2(
0, 
0, 
-1, 0.965272, 0, -1, 0.216437,-99) , 
0, 0.072763, 1, 0, 0.348785,-99) , 
2, 2.36064, 1, 0, 0.483493,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.549449,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0209194,-99) , 
7, -1.28002, 0, 0, 0.439834,-99) , 
NN2(
0, 
0, 
-1, 0.517296, 0, -1, 0.00657355,-99) , 
6, 1.18338, 1, 0, 0.356526,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.515223,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.524356, 0, 0, 0.190396,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0413947,-99) , 
0, 0.0670046, 1, 0, 0.182785,-99) , 
3, 0.582858, 0, 0, 0.463342,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.308736);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.738739,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.498953,-99) , 
4, 9.81878, 1, 0, 0.655653,-99) , 
NN2(
0, 
0, 
-1, 0.0834828, 1, -1, 0.397583,-99) , 
6, -0.525146, 0, 0, 0.49051,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.643593,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.45616,-99) , 
5, 5.04832, 0, 0, 0.542209,-99) , 
NN2(
0, 
0, 
-1, 0.849366, 0, -1, 0.293111,-99) , 
0, 0.0390806, 1, 0, 0.393842,-99) , 
6, 0.667138, 1, 0, 0.454237,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.555516,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.130477,-99) , 
7, -0.742991, 0, 0, 0.414021,-99) , 
NN2(
0, 
0, 
-1, 0.506547, 0, -1, 0.00772147,-99) , 
7, 1.33261, 1, 0, 0.339479,-99) , 
NN2(
0, 
0, 
-1, 10.5556, 0, -1, 0.0411067,-99) , 
0, 0.0670046, 1, 0, 0.178263,-99) , 
3, 0.582858, 0, 0, 0.436564,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.249872);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.634327,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.163999,-99) , 
1, 61.2198, 1, 0, 0.611574,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.518266,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.36472,-99) , 
0, 0.0834828, 1, 0, 0.470193,-99) , 
6, -0.54739, 0, 0, 0.528811,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.657565,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.436315,-99) , 
8, 0.0215755, 0, 0, 0.512974,-99) , 
NN2(
0, 
0, 
-1, 1.1493, 1, -1, 0.226456,-99) , 
9, 0.00216514, 1, 0, 0.430121,-99) , 
6, 0.933727, 1, 0, 0.497525,-99) , 
NN2(
NN2(
0, 
0, 
-1, 1.05151, 1, -1, 0.320479,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.570967,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 11.25, 1, 0, 0.23546,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0551551,-99) , 
0, 0.0670046, 1, 0, 0.182497,-99) , 
3, 0.582858, 0, 0, 0.478646,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.220499);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.599603,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.464225,-99) , 
10, 1.05556, 1, 0, 0.524332,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.608477,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.26889,-99) , 
0, 0.0169553, 1, 0, 0.38644,-99) , 
1, 22.0294, 1, 0, 0.5039,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.81883,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.358921,-99) , 
4, 9.70086, 0, 0, 0.525745,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0538571,-99) , 
0, 0.0111429, 1, 0, 0.272837,-99) , 
1, 61.2162, 1, 0, 0.495674,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510677,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.199068,-99) , 
6, -1.4658, 0, 0, 0.463206,-99) , 
NN2(
0, 
0, 
-1, 2.11111, 1, -1, 0.09062,-99) , 
2, 2.77731, 1, 0, 0.418943,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.525235,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.276672, 1, 0, 0.265598,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0567881,-99) , 
0, 0.105816, 1, 0, 0.316622,-99) , 
3, 0.713215, 0, 0, 0.466706,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.200616);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.575553,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.458159,-99) , 
1, 11.509, 1, 0, 0.520353,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.534311,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.066577,-99) , 
0, 0.0111429, 1, 0, 0.288681,-99) , 
1, 61.2162, 1, 0, 0.512392,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.509339,-99) , 
NN2(
0, 
0, 
-1, 4.30832, 1, -1, 0.093002,-99) , 
0, 0.0334858, 1, 0, 0.261707,-99) , 
6, -2.13105, 0, 0, 0.504528,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.574423,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.187494,-99) , 
7, 1.19908, 1, 0, 0.496321,-99) , 
NN2(
0, 
0, 
-1, 0.0362614, 1, -1, 0.277467,-99) , 
4, 7.755, 1, 0, 0.389471,-99) , 
NN2(
0, 
0, 
-1, 10.5556, 0, -1, 0.0560779,-99) , 
0, 0.105816, 1, 0, 0.300731,-99) , 
3, 0.713215, 0, 0, 0.472208,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.148218);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.522709,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.178645,-99) , 
4, 26.0832, 1, 0, 0.517585,-99) , 
NN2(
0, 
0, 
-1, 0.0111429, 1, -1, 0.28049,-99) , 
1, 61.2162, 1, 0, 0.509731,-99) , 
NN2(
0, 
0, 
-1, 0.0500974, 1, -1, 0.259353,-99) , 
6, -2.13105, 0, 0, 0.502154,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.52773,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.196167,-99) , 
6, 1.60059, 1, 0, 0.491908,-99) , 
NN2(
0, 
0, 
-1, 4.22222, 1, -1, 0.0157887,-99) , 
2, 3.32961, 1, 0, 0.464638,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.849711,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.108517,-99) , 
7, -0.175469, 1, 0, 0.272754,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -0.133357, 0, 0, 0.165295,-99) , 
0, 0.0559554, 1, 0, 0.311561,-99) , 
3, 0.713215, 0, 0, 0.472822,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.150574);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.751988,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.48756,-99) , 
0, 0.0057933, 1, 0, 0.495747,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.6472,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.189398,-99) , 
3, 0.809229, 1, 0, 0.284513,-99) , 
7, -2.1326, 0, 0, 0.487378,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.575932,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.368373,-99) , 
6, -1.06487, 0, 0, 0.514901,-99) , 
NN2(
0, 
0, 
-1, 0.930492, 0, -1, 0.309523,-99) , 
0, 0.0447675, 1, 0, 0.393014,-99) , 
2, 1.94406, 1, 0, 0.468212,-99) , 
NN2(
NN2(
0, 
0, 
-1, 1.33219, 1, -1, 0.362025,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.582093,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.66478, 1, 0, 0.326034,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.083525,-99) , 
0, 0.105816, 1, 0, 0.288816,-99) , 
3, 0.687143, 0, 0, 0.44595,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.185698);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.554196,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.424381,-99) , 
7, 1.5162, 1, 0, 0.533678,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.573257,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.216048,-99) , 
3, 0.818446, 1, 0, 0.287917,-99) , 
7, -2.13265, 0, 0, 0.524266,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.6458,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.401889,-99) , 
3, 0.968274, 0, 0, 0.521303,-99) , 
NN2(
0, 
0, 
-1, 0.00107876, 1, -1, 0.360022,-99) , 
10, 0.527778, 1, 0, 0.412025,-99) , 
2, 1.94406, 1, 0, 0.501785,-99) , 
NN2(
NN2(
0, 
0, 
-1, 3.33277, 1, -1, 0.414976,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.534121,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.66478, 1, 0, 0.297348,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0727131,-99) , 
0, 0.105816, 1, 0, 0.333,-99) , 
3, 0.713215, 0, 0, 0.477086,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.107199);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50993,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.284063,-99) , 
1, 61.2162, 1, 0, 0.502242,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.560187,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.11129,-99) , 
3, 0.988419, 0, 0, 0.278579,-99) , 
0, 0.172254, 1, 0, 0.49353,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508693,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.245179,-99) , 
9, -0.00150436, 0, 0, 0.438822,-99) , 
NN2(
0, 
0, 
-1, 0.94244, 0, -1, 0.110087,-99) , 
0, 0.0722462, 1, 0, 0.35769,-99) , 
6, -1.73216, 0, 0, 0.478679,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.58102,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.051755,-99) , 
7, -1.21378, 0, 0, 0.497608,-99) , 
NN2(
0, 
0, 
-1, 0.501611, 0, -1, 0.0587281,-99) , 
6, 1.05151, 1, 0, 0.421537,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.577219,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.00772051, 0, 0, 0.249002,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0689166,-99) , 
0, 0.0670046, 1, 0, 0.267375,-99) , 
3, 0.582858, 0, 0, 0.468233,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.179321);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.605651,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0939572,-99) , 
4, 22.2079, 1, 0, 0.579064,-99) , 
NN2(
0, 
0, 
-1, 0.0142567, 1, -1, 0.449864,-99) , 
7, -0.00776708, 1, 0, 0.483888,-99) , 
NN2(
0, 
0, 
-1, 0.133415, 1, -1, 0.400713,-99) , 
7, -0.933352, 0, 0, 0.457059,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.554721,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0572759,-99) , 
7, -1.21378, 0, 0, 0.47896,-99) , 
NN2(
0, 
0, 
-1, 0.501611, 0, -1, 0.064942,-99) , 
6, 1.05151, 1, 0, 0.40916,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.555959,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.524356, 0, 0, 0.243967,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0685252,-99) , 
0, 0.0670046, 1, 0, 0.262634,-99) , 
3, 0.582858, 0, 0, 0.447707,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.260393);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.638982,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.455304,-99) , 
9, 0.00183529, 1, 0, 0.603899,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.665291,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.356842,-99) , 
6, 1.46365, 0, 0, 0.437125,-99) , 
3, 0.907302, 1, 0, 0.531209,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.566776,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.39247,-99) , 
6, -0.682885, 0, 0, 0.48997,-99) , 
NN2(
0, 
0, 
-1, 0.965284, 0, -1, 0.294112,-99) , 
7, 1.19857, 1, 0, 0.452048,-99) , 
0, 0.0446346, 1, 0, 0.486455,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.583427,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.563813,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.166397,-99) , 
8, 0.0115273, 0, 0, 0.286898,-99) , 
10, 2.22222, 1, 0, 0.387467,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.538282,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.00772051, 0, 0, 0.234974,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0677965,-99) , 
0, 0.0670046, 1, 0, 0.254055,-99) , 
3, 0.582858, 0, 0, 0.475679,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.117235);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.614552,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.485248,-99) , 
4, 5.19787, 1, 0, 0.502867,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.133522,-99) , 
4, 29.6818, 1, 0, 0.499354,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.747953,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.275751,-99) , 
8, 0.0194835, 0, 0, 0.547129,-99) , 
NN2(
0, 
0, 
-1, 5.19444, 0, -1, 0.133749,-99) , 
3, 0.982646, 0, 0, 0.307043,-99) , 
0, 0.172234, 1, 0, 0.492871,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.530802,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.213039,-99) , 
6, -1.23083, 0, 0, 0.463558,-99) , 
NN2(
0, 
0, 
-1, 0.613742, 0, -1, 0.140039,-99) , 
7, 1.33219, 1, 0, 0.416283,-99) , 
NN2(
0, 
0, 
-1, 10.5556, 0, -1, 0.0720456,-99) , 
0, 0.105816, 1, 0, 0.337147,-99) , 
3, 0.687143, 0, 0, 0.475334,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.124446);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531588,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.371236,-99) , 
2, 3.88812, 1, 0, 0.524244,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.147677,-99) , 
4, 29.6818, 1, 0, 0.520804,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.682759,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.182881,-99) , 
7, 0.375118, 1, 0, 0.54398,-99) , 
NN2(
0, 
0, 
-1, 5.19444, 0, -1, 0.147925,-99) , 
3, 0.982646, 0, 0, 0.31546,-99) , 
0, 0.172234, 1, 0, 0.514103,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.509496,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.123548,-99) , 
6, 1.59917, 1, 0, 0.469234,-99) , 
NN2(
0, 
0, 
-1, 0.0121232, 0, -1, 0.210139,-99) , 
4, 11.0074, 1, 0, 0.404747,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517575,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.276672, 1, 0, 0.280691,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0802874,-99) , 
0, 0.105816, 1, 0, 0.332242,-99) , 
3, 0.687143, 0, 0, 0.493951,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0901415);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.503563,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.380925,-99) , 
6, 2.00008, 1, 0, 0.496001,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.164037,-99) , 
4, 29.6818, 1, 0, 0.493087,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.715514,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.286384,-99) , 
8, 0.0194835, 0, 0, 0.531009,-99) , 
NN2(
0, 
0, 
-1, 5.19444, 0, -1, 0.164307,-99) , 
3, 0.982646, 0, 0, 0.32095,-99) , 
0, 0.172234, 1, 0, 0.487644,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510823,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0373398,-99) , 
2, 3.27992, 1, 0, 0.486922,-99) , 
NN2(
0, 
0, 
-1, 10.0845, 0, -1, 0.183961,-99) , 
3, 0.4753, 0, 0, 0.443669,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.825118,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.108216,-99) , 
7, -0.175679, 1, 0, 0.290157,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -0.13253, 0, 0, 0.181012,-99) , 
0, 0.0559554, 1, 0, 0.324799,-99) , 
3, 0.687143, 0, 0, 0.469864,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.215959);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.0101308, 1, 1, 0.588783,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.535143,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.378542,-99) , 
3, 0.887448, 1, 0, 0.453255,-99) , 
7, 0.932815, 0, 0, 0.502997,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.599321,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.401401,-99) , 
10, 1.05556, 1, 0, 0.54428,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506603,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.308425,-99) , 
4, 6.81237, 1, 0, 0.3929,-99) , 
3, 0.991311, 0, 0, 0.443298,-99) , 
0, 0.0446294, 1, 0, 0.469188,-99) , 
NN2(
NN2(
0, 
0, 
-1, 3.33277, 1, -1, 0.384298,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507444,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.14267, 1, 0, 0.281888,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.083552,-99) , 
0, 0.105816, 1, 0, 0.320276,-99) , 
3, 0.687143, 0, 0, 0.453204,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.115707);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.00955039, 1, -1, 0.46494,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.610153,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.16673, 1, 0, 0.550106,-99) , 
NN2(
0, 
0, 
-1, 0.781777, 0, -1, 0.21419,-99) , 
3, 0.988419, 0, 0, 0.3533,-99) , 
0, 0.150059, 1, 0, 0.456177,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508509,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0732052,-99) , 
7, -1.28002, 0, 0, 0.452067,-99) , 
NN2(
0, 
0, 
-1, 0.517296, 0, -1, 0.025421,-99) , 
6, 1.18338, 1, 0, 0.40175,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.520675,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 11.25, 1, 0, 0.235583,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0757014,-99) , 
0, 0.0670046, 1, 0, 0.282427,-99) , 
3, 0.582858, 0, 0, 0.449026,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0760064);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507515,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.171239,-99) , 
9, -0.0146299, 0, 0, 0.501754,-99) , 
NN2(
0, 
0, 
-1, 6.82334, 0, -1, 0.197658,-99) , 
9, 0.00955039, 1, 0, 0.49381,-99) , 
NN2(
0, 
0, 
-1, 0.779957, 0, -1, 0.356829,-99) , 
0, 0.150059, 1, 0, 0.48328,-99) , 
NN2(
NN2(
0, 
0, 
-1, 1.05151, 1, -1, 0.384798,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507262,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 0.808666, 0, 0, 0.229478,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0750598,-99) , 
0, 0.0670046, 1, 0, 0.274166,-99) , 
3, 0.582858, 0, 0, 0.474845,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.100052);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.588487,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.468275,-99) , 
0, 0.00980123, 1, 0, 0.476208,-99) , 
NN2(
0, 
0, 
-1, 0.837863, 0, -1, 0.311542,-99) , 
0, 0.172254, 1, 0, 0.471215,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.157498,-99) , 
4, 29.6804, 1, 0, 0.468637,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.513004,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0833657,-99) , 
7, -1.21378, 0, 0, 0.456491,-99) , 
NN2(
0, 
0, 
-1, 0.501611, 0, -1, 0.0827353,-99) , 
6, 1.05151, 1, 0, 0.402941,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502383,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.524356, 0, 0, 0.225509,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.0746301,-99) , 
0, 0.0670046, 1, 0, 0.287492,-99) , 
3, 0.582858, 0, 0, 0.461435,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0718784);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506682,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.248304,-99) , 
4, 25.7474, 1, 0, 0.503016,-99) , 
NN2(
0, 
0, 
-1, 0.0332863, 1, -1, 0.273471,-99) , 
6, -2.15428, 0, 0, 0.497454,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.774631,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.391926,-99) , 
7, 1.71214, 0, 0, 0.558381,-99) , 
NN2(
0, 
0, 
-1, 0.0339056, 0, -1, 0.204594,-99) , 
0, 0.0283351, 1, 0, 0.373577,-99) , 
6, 2.00008, 1, 0, 0.490416,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0.354965, 0, -1, 0.389457,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.563723,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.38345, 1, 0, 0.220711,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.27777, 1, 0, 0.074054,-99) , 
0, 0.0670046, 1, 0, 0.280824,-99) , 
3, 0.582858, 0, 0, 0.48223,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.138597);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.577074,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.467529,-99) , 
2, 0.138861, 1, 0, 0.493672,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.556759,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.343887,-99) , 
0, 0.0103123, 1, 0, 0.423033,-99) , 
0, 0.0193572, 0, 0, 0.480183,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.580512,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.231297,-99) , 
1, 9.64963, 1, 0, 0.420427,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.837863, 0, 0, 0.317904,-99) , 
0, 0.172254, 1, 0, 0.475311,-99) , 
NN2(
0, 
0, 
-1, 0.0670046, 1, -1, 0.293829,-99) , 
3, 0.582858, 0, 0, 0.46832,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.12102);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.578423,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.478867,-99) , 
3, 0.973929, 0, 0, 0.505714,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.581199,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.255071,-99) , 
2, 0.694327, 0, 0, 0.371075,-99) , 
1, 31.061, 1, 0, 0.495945,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.801052,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.42743,-99) , 
7, 0.125592, 0, 0, 0.549639,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.139776,-99) , 
0, 0.00975471, 1, 0, 0.325861,-99) , 
1, 61.2162, 1, 0, 0.490755,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.551035,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 14.9351, 1, 0, 0.4833,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 0.929663, 1, 0, 0.411768,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.831299, 0, 0, 0.296873,-99) , 
0, 0.172254, 1, 0, 0.484912,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.124452);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.533124,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.32397,-99) , 
1, 61.2162, 1, 0, 0.526493,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508983,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.263962,-99) , 
0, 0.0435107, 1, 0, 0.410145,-99) , 
6, 1.80755, 1, 0, 0.513408,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.583963,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.274978,-99) , 
3, 0.835689, 0, 0, 0.473338,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0813805, 1, 0, 0.408587,-99) , 
6, -1.86545, 0, 0, 0.504563,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.525098,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.45179, 0, 0, 0.459997,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 0.929663, 1, 0, 0.394731,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.831299, 0, 0, 0.287913,-99) , 
0, 0.172254, 1, 0, 0.498191,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0603302);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 29.6817, 1, -1, 0.495255,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.692778,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00192551,-99) , 
0, 0.122154, 0, 0, 0.19964,-99) , 
9, -0.0146299, 0, 0, 0.490456,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.215251,-99) , 
9, 0.00955039, 1, 0, 0.483773,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.525648,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.70204, 0, 0, 0.486336,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.435078,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.354088,-99) , 
0, 0.150059, 1, 0, 0.474073,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0768592);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.513198,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.178831,-99) , 
4, 29.6817, 1, 0, 0.510336,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.67979,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00204501,-99) , 
0, 0.122154, 0, 0, 0.198623,-99) , 
9, -0.0146299, 0, 0, 0.505397,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.225617,-99) , 
9, 0.00955039, 1, 0, 0.498713,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510587,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.70204, 0, 0, 0.473416,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.424709,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.347189,-99) , 
0, 0.150059, 1, 0, 0.487482,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0614845);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 29.6817, 1, -1, 0.491449,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.662834,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00220802,-99) , 
0, 0.122154, 0, 0, 0.197252,-99) , 
9, -0.0146299, 0, 0, 0.486925,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.239328,-99) , 
9, 0.00955039, 1, 0, 0.481122,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.338197,-99) , 
0, 0.150059, 1, 0, 0.470634,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0653052);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.509356,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.200056,-99) , 
4, 29.6817, 1, 0, 0.506819,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.648958,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00234771,-99) , 
0, 0.122154, 0, 0, 0.196094,-99) , 
9, -0.0146299, 0, 0, 0.502154,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.2507,-99) , 
9, 0.00955039, 1, 0, 0.496348,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506744,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.70204, 0, 0, 0.472146,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.426295,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.352093,-99) , 
0, 0.150059, 1, 0, 0.485848,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.059356);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.490759,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.63394,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00250575,-99) , 
0, 0.122154, 0, 0, 0.1948,-99) , 
9, -0.0146299, 0, 0, 0.486425,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.263166,-99) , 
9, 0.00955039, 1, 0, 0.481346,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.344133,-99) , 
0, 0.150059, 1, 0, 0.47144,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.056089);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50709,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.505597,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.62006,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00265858,-99) , 
0, 0.122154, 0, 0, 0.193567,-99) , 
9, -0.0146299, 0, 0, 0.501128,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.274836,-99) , 
9, 0.00955039, 1, 0, 0.496047,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.505257,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.70204, 0, 0, 0.47271,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.429159,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.357652,-99) , 
0, 0.150059, 1, 0, 0.48613,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0926837);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.53613,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.47565,-99) , 
10, 0.555556, 1, 0, 0.491657,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.60676,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00281152,-99) , 
0, 0.122154, 0, 0, 0.192348,-99) , 
9, -0.0146299, 0, 0, 0.487459,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.286155,-99) , 
9, 0.00955039, 1, 0, 0.482991,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.520689,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.216634,-99) , 
2, 1.94291, 1, 0, 0.460415,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.419001,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.350569,-99) , 
0, 0.150059, 1, 0, 0.473567,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.14941);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.539915,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.262211,-99) , 
2, 3.88879, 1, 0, 0.529312,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.621162,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.407204,-99) , 
3, 0.973929, 0, 0, 0.447517,-99) , 
4, 9.81414, 1, 0, 0.506827,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.986869,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.49076,-99) , 
0, 0.00193857, 1, 0, 0.518748,-99) , 
NN2(
0, 
0, 
-1, 0.877552, 1, -1, 0.343153,-99) , 
0, 0.0104161, 1, 0, 0.426831,-99) , 
0, 0.016891, 0, 0, 0.49411,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504793,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.19992,-99) , 
6, -1.22908, 0, 0, 0.446077,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.407413,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.342911,-99) , 
0, 0.150059, 1, 0, 0.483479,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0552292);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, -2.13204, 0, -1, 0.492433,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.597046,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00274981,-99) , 
0, 0.122154, 0, 0, 0.195802,-99) , 
9, -0.0146299, 0, 0, 0.488193,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.290483,-99) , 
9, 0.00955039, 1, 0, 0.483928,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.329774,-99) , 
0, 0.150059, 1, 0, 0.473234,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0662109);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.511031,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.344381,-99) , 
6, -2.13204, 0, 0, 0.50624,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.583691,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0029055,-99) , 
0, 0.122154, 0, 0, 0.194442,-99) , 
9, -0.0146299, 0, 0, 0.50187,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.301997,-99) , 
9, 0.00955039, 1, 0, 0.497604,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.342093,-99) , 
0, 0.150059, 1, 0, 0.486901,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.19152);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.81791, 0, 1, 0.616623,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.652615,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.400931,-99) , 
0, 0.00810668, 1, 0, 0.463181,-99) , 
0, 0.018852, 0, 0, 0.550605,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.781933,-99) , 
NN2(
0, 
0, 
-1, 6.82034, 0, -1, 0.404518,-99) , 
0, 0.0409239, 0, 0, 0.442052,-99) , 
3, 0.928057, 1, 0, 0.512246,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.519987,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.396529,-99) , 
7, -0.844671, 0, 0, 0.475742,-99) , 
NN2(
0, 
0, 
-1, 1.41667, 1, -1, 0.256598,-99) , 
7, 1.59831, 1, 0, 0.456721,-99) , 
NN2(
0, 
0, 
-1, 0.869643, 0, -1, 0.133667,-99) , 
4, 16.1786, 1, 0, 0.443897,-99) , 
0, 0.0446346, 1, 0, 0.474372,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.206603);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.584763,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.227123,-99) , 
10, 8.33333, 1, 0, 0.573365,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531163,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.311293,-99) , 
2, 0.00764432, 0, 0, 0.465885,-99) , 
2, 0.138734, 0, 0, 0.545091,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.777529,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.462035,-99) , 
3, 0.871003, 0, 0, 0.524817,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.62825,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.289648,-99) , 
8, 0.0398374, 0, 0, 0.355755,-99) , 
3, 0.932903, 1, 0, 0.453696,-99) , 
5, 4.57364, 0, 0, 0.515216,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.554515,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -2.0388, 0, 0, 0.535502,-99) , 
NN2(
0, 
0, 
-1, 0.635001, 0, -1, 0.407084,-99) , 
2, 0.694327, 1, 0, 0.475409,-99) , 
NN2(
0, 
0, 
-1, 0.850121, 0, -1, 0.349611,-99) , 
6, 0.800433, 1, 0, 0.436968,-99) , 
0, 0.0446346, 1, 0, 0.471721,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0653061);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50027,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.431402,-99) , 
10, 4.44444, 1, 0, 0.488235,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.566013,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.00314553,-99) , 
0, 0.122154, 0, 0, 0.192378,-99) , 
9, -0.0146299, 0, 0, 0.484085,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.305301,-99) , 
9, 0.00955039, 1, 0, 0.480407,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.522071,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.63125, 0, 0, 0.492942,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.30735, 1, 0, 0.456532,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.823097,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -0.324988, 1, 0, 0.550061,-99) , 
NN2(
0, 
0, 
-1, 5.47314, 1, -1, 0.0789262,-99) , 
4, 13.2614, 0, 0, 0.147849,-99) , 
3, 0.875591, 0, 0, 0.351662,-99) , 
0, 0.150059, 1, 0, 0.47158,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0759783);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.150059, 1, -1, 0.462084,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0379892);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.150059, 1, -1, 0.481015,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0496202);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508586,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.403215,-99) , 
6, 2.00008, 1, 0, 0.502426,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.217166,-99) , 
4, 29.6817, 1, 0, 0.50028,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.498982,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.503703,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0851301,-99) , 
5, 6.61069, 1, 0, 0.466028,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.431206,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.372314,-99) , 
0, 0.150059, 1, 0, 0.490504,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0398147);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.150059, 1, -1, 0.480103,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0331132);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.503598,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.232754,-99) , 
4, 29.6817, 1, 0, 0.501592,-99) , 
NN2(
0, 
0, 
-1, -0.00122495, 0, -1, 0.243873,-99) , 
6, -2.26534, 0, 0, 0.499447,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.498207,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.375082,-99) , 
0, 0.150059, 1, 0, 0.490048,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0345393);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.490226,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.503994,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.61213, 0, 0, 0.473908,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.440321,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.382875,-99) , 
0, 0.150059, 1, 0, 0.483138,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0443082);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507235,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.207762,-99) , 
9, -0.0146299, 0, 0, 0.503241,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.344183,-99) , 
9, 0.00955039, 1, 0, 0.50006,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.49886,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.377871,-99) , 
0, 0.150059, 1, 0, 0.4909,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0360218);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 14.4444, 1, -1, 0.481997,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0354897);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504924,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.421999,-99) , 
6, -1.86545, 0, 0, 0.498075,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.497005,-99) , 
NN2(
0, 
0, 
-1, 0.833207, 0, -1, 0.340755,-99) , 
0, 0.172254, 1, 0, 0.493048,-99) , 
NN2(
0, 
0, 
-1, 6.86059, 0, -1, 0.159596,-99) , 
10, 14.4444, 1, 0, 0.490996,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0317642);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 14.4444, 1, -1, 0.484123,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0262253);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502806,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.242987,-99) , 
4, 29.6817, 1, 0, 0.500913,-99) , 
NN2(
0, 
0, 
-1, 0.782958, 0, -1, 0.410394,-99) , 
0, 0.150059, 1, 0, 0.495088,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.494018,-99) , 
NN2(
0, 
0, 
-1, 6.86059, 0, -1, 0.168824,-99) , 
10, 14.4444, 1, 0, 0.49206,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0642518);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.549101,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.479477,-99) , 
4, 5.47263, 1, 0, 0.492699,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.52359,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.182575,-99) , 
0, 0.0281081, 1, 0, 0.353565,-99) , 
4, 22.0177, 1, 0, 0.489462,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.488418,-99) , 
NN2(
0, 
0, 
-1, 6.86059, 0, -1, 0.172536,-99) , 
10, 14.4444, 1, 0, 0.486532,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0569283);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.516922,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.468104,-99) , 
6, 1.06702, 1, 0, 0.502662,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.649157,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.267111,-99) , 
7, 1.08764, 0, 0, 0.351902,-99) , 
4, 22.0177, 1, 0, 0.499187,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.498154,-99) , 
NN2(
0, 
0, 
-1, 6.86059, 0, -1, 0.181903,-99) , 
10, 14.4444, 1, 0, 0.496301,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0480558);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507175,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.437164,-99) , 
9, -0.00598264, 0, 0, 0.500705,-99) , 
NN2(
0, 
0, 
-1, -0.00128047, 0, -1, 0.26154,-99) , 
6, -2.26534, 0, 0, 0.498792,-99) , 
NN2(
0, 
0, 
-1, 0.837863, 0, -1, 0.363601,-99) , 
0, 0.172254, 1, 0, 0.49542,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.55391,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.097375,-99) , 
7, -1.25858, 0, 0, 0.507652,-99) , 
NN2(
0, 
0, 
-1, 9.18397, 0, -1, 0.0576244,-99) , 
7, 1.33261, 1, 0, 0.463391,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.624863,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 0.808666, 0, 0, 0.325227,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.11698,-99) , 
0, 0.0670046, 1, 0, 0.366888,-99) , 
3, 0.582858, 0, 0, 0.490846,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0880521);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524146,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.478796,-99) , 
2, 0.832858, 0, 0, 0.497756,-99) , 
NN2(
0, 
0, 
-1, 1.52568, 0, -1, 0.359223,-99) , 
6, 2.17042, 1, 0, 0.493454,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.558051,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.330125,-99) , 
3, 0.860977, 0, 0, 0.472186,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0999322, 1, 0, 0.427965,-99) , 
6, -1.73216, 0, 0, 0.486331,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.542007,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.101681,-99) , 
7, -1.25858, 0, 0, 0.498066,-99) , 
NN2(
0, 
0, 
-1, 9.18397, 0, -1, 0.0602902,-99) , 
7, 1.33261, 1, 0, 0.455673,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.613532,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 0.808666, 0, 0, 0.32213,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.116577,-99) , 
0, 0.0670046, 1, 0, 0.362219,-99) , 
3, 0.582858, 0, 0, 0.481954,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0699391);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.645795,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.263546,-99) , 
9, -0.00322585, 0, 0, 0.581424,-99) , 
NN2(
0, 
0, 
-1, -1.39264, 0, -1, 0.491428,-99) , 
6, -1.50222, 1, 0, 0.497624,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.536237,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.34988,-99) , 
3, 0.860977, 0, 0, 0.466467,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0999322, 1, 0, 0.424191,-99) , 
6, -1.73216, 0, 0, 0.489707,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.520267,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.111915,-99) , 
7, -1.28002, 0, 0, 0.481271,-99) , 
NN2(
0, 
0, 
-1, 0.517296, 0, -1, 0.0642568,-99) , 
6, 1.18338, 1, 0, 0.441318,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.603201,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.524356, 0, 0, 0.316224,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.115794,-99) , 
0, 0.0670046, 1, 0, 0.353432,-99) , 
3, 0.582858, 0, 0, 0.484967,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0845397);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.521598,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.445409,-99) , 
10, 6.33333, 1, 0, 0.514994,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.26084,-99) , 
4, 29.6804, 1, 0, 0.513118,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.749774,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.437284,-99) , 
8, 0.0521367, 0, 0, 0.461866,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0999322, 1, 0, 0.421137,-99) , 
6, -1.73216, 0, 0, 0.503262,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.756705,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.396317,-99) , 
3, 0.412262, 1, 0, 0.462635,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.354965, 0, 0, 0.429757,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.596346,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 11.25, 1, 0, 0.31153,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.115158,-99) , 
0, 0.0670046, 1, 0, 0.346278,-99) , 
3, 0.582858, 0, 0, 0.497858,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0369214);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.172254, 1, -1, 0.494565,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.696996,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.215362,-99) , 
8, 0.0304441, 0, 0, 0.366822,-99) , 
7, 2.13138, 1, 0, 0.491534,-99) , 
NN2(
0, 
0, 
-1, 0.0549444, 1, -1, 0.267514,-99) , 
6, -2.26534, 0, 0, 0.489835,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.516278,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0785184,-99) , 
6, 1.18338, 1, 0, 0.475713,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.354965, 0, 0, 0.442896,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.582088,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.00772051, 0, 0, 0.30584,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.114372,-99) , 
0, 0.0670046, 1, 0, 0.357179,-99) , 
3, 0.582858, 0, 0, 0.48534,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0471459);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506884,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.384546,-99) , 
0, 0.172254, 1, 0, 0.503795,-99) , 
NN2(
0, 
0, 
-1, 0.0549444, 1, -1, 0.274811,-99) , 
6, -2.26534, 0, 0, 0.502031,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.689142,-99) , 
NN2(
0, 
0, 
-1, 11.1561, 0, -1, 0.221666,-99) , 
8, 0.0304441, 0, 0, 0.369003,-99) , 
7, 2.13138, 1, 0, 0.498927,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.73506,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.409358,-99) , 
3, 0.412262, 1, 0, 0.468131,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.354965, 0, 0, 0.436333,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.601181,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.37131, 0, 0, 0.303796,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.53467, 1, 0, 0.11402,-99) , 
0, 0.0670046, 1, 0, 0.353006,-99) , 
3, 0.582858, 0, 0, 0.494011,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.06434);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50921,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.444784,-99) , 
5, 6.52896, 1, 0, 0.497517,-99) , 
NN2(
0, 
0, 
-1, 0.0999322, 1, -1, 0.43781,-99) , 
6, -1.73216, 0, 0, 0.491014,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.678953,-99) , 
NN2(
0, 
0, 
-1, 11.1561, 0, -1, 0.229907,-99) , 
8, 0.0304441, 0, 0, 0.371848,-99) , 
7, 2.13138, 1, 0, 0.488264,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.514461,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0844119,-99) , 
6, 1.18338, 1, 0, 0.475528,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.354965, 0, 0, 0.443775,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.578586,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 0.808666, 0, 0, 0.302475,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.113605,-99) , 
0, 0.0670046, 1, 0, 0.359266,-99) , 
3, 0.582858, 0, 0, 0.483957,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.112406);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.54688,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.363724,-99) , 
0, 0.0409509, 1, 0, 0.532432,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.552271,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.332801,-99) , 
4, 6.82034, 0, 0, 0.451149,-99) , 
3, 0.930477, 1, 0, 0.502768,-99) , 
NN2(
0, 
0, 
-1, 14.0721, 1, -1, 0.463727,-99) , 
0, 0.0446346, 1, 0, 0.481161,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0.354965, 0, -1, 0.432208,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.588509,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.37131, 0, 0, 0.299558,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 4.53467, 1, 0, 0.112984,-99) , 
0, 0.0670046, 1, 0, 0.35183,-99) , 
3, 0.582858, 0, 0, 0.476881,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0446696);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.636057,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.489569,-99) , 
2, 3.57987, 0, 0, 0.494233,-99) , 
NN2(
0, 
0, 
-1, 0.837642, 0, -1, 0.383782,-99) , 
2, 4.02767, 1, 0, 0.490172,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.489246,-99) , 
NN2(
0, 
0, 
-1, 0.0281081, 1, -1, 0.337828,-99) , 
4, 22.0177, 1, 0, 0.485822,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0629581);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.0383518, 0, 1, 0.511755,-99) , 
NN2(
0, 
0, 
-1, 0.900965, 1, -1, 0.142509,-99) , 
9, 0.016286, 1, 0, 0.50837,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.693963,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.474638,-99) , 
0, 0.12251, 0, 0, 0.534425,-99) , 
NN2(
0, 
0, 
-1, 0.0730419, 1, -1, 0.313158,-99) , 
3, 0.869643, 0, 0, 0.44281,-99) , 
2, 2.49993, 1, 0, 0.499728,-99) , 
NN2(
0, 
0, 
-1, 0.0281081, 1, -1, 0.347892,-99) , 
4, 22.0177, 1, 0, 0.496316,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0517682);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.528952,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.481039,-99) , 
4, 5.47263, 1, 0, 0.490102,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506255,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.213519,-99) , 
0, 0.0281081, 1, 0, 0.363499,-99) , 
4, 22.0177, 1, 0, 0.487267,-99) , 
NN2(
0, 
0, 
-1, -0.000637531, 0, -1, 0.22167,-99) , 
10, 14.4444, 1, 0, 0.485832,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.484911,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.017391);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 14.4444, 1, -1, 0.496694,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.572953,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.550923,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.133869,-99) , 
0, 0.021965, 1, 0, 0.270117,-99) , 
2, 1.66118, 0, 0, 0.361885,-99) , 
4, 22.0177, 1, 0, 0.493709,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.492795,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0237865);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504027,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.293579,-99) , 
6, -2.26534, 0, 0, 0.502492,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.234566,-99) , 
10, 14.4444, 1, 0, 0.501042,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.621194,-99) , 
NN2(
0, 
0, 
-1, -1.07873, 1, -1, 0.288194,-99) , 
7, 1.08764, 0, 0, 0.361122,-99) , 
4, 22.0177, 1, 0, 0.497954,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.497041,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0402886);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50699,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.465825,-99) , 
5, 4.44055, 0, 0, 0.496632,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.238864,-99) , 
10, 14.4444, 1, 0, 0.495246,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.570312,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.549985,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.138191,-99) , 
0, 0.021965, 1, 0, 0.27354,-99) , 
2, 1.66118, 0, 0, 0.363842,-99) , 
4, 22.0177, 1, 0, 0.492358,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.491465,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0385299);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.604966,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.488865,-99) , 
10, 11.2778, 0, 0, 0.491624,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.246266,-99) , 
10, 14.4444, 1, 0, 0.490318,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.611682,-99) , 
NN2(
0, 
0, 
-1, -1.07873, 1, -1, 0.292311,-99) , 
7, 1.08764, 0, 0, 0.362057,-99) , 
4, 22.0177, 1, 0, 0.48752,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.486654,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0243787);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.503498,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.385465,-99) , 
7, 2.13138, 1, 0, 0.500798,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.253487,-99) , 
10, 14.4444, 1, 0, 0.499494,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.563068,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.545512,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.146945,-99) , 
0, 0.021965, 1, 0, 0.279541,-99) , 
2, 1.66118, 0, 0, 0.366521,-99) , 
4, 22.0177, 1, 0, 0.496612,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.495745,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0220536);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 14.4444, 1, -1, 0.49374,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.557061,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.539462,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.150027,-99) , 
0, 0.021965, 1, 0, 0.280237,-99) , 
2, 1.66118, 0, 0, 0.365432,-99) , 
4, 22.0177, 1, 0, 0.490971,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.490125,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0185295);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501944,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.301877,-99) , 
6, -2.26534, 0, 0, 0.500495,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.262374,-99) , 
10, 14.4444, 1, 0, 0.499253,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.551613,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.533978,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.152861,-99) , 
0, 0.021965, 1, 0, 0.280874,-99) , 
2, 1.66118, 0, 0, 0.364438,-99) , 
4, 22.0177, 1, 0, 0.496355,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.495509,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0196428);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 14.4444, 1, -1, 0.494735,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.547026,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.529364,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.155276,-99) , 
0, 0.021965, 1, 0, 0.281415,-99) , 
2, 1.66118, 0, 0, 0.363596,-99) , 
4, 22.0177, 1, 0, 0.491926,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.491095,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.019573);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502497,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.333308,-99) , 
6, 2.26667, 1, 0, 0.50084,-99) , 
NN2(
0, 
0, 
-1, 6.90586, 0, -1, 0.269828,-99) , 
10, 14.4444, 1, 0, 0.499646,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.59392,-99) , 
NN2(
0, 
0, 
-1, -1.07873, 1, -1, 0.298631,-99) , 
7, 1.08764, 0, 0, 0.362698,-99) , 
4, 22.0177, 1, 0, 0.496722,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.495891,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0549688);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.509314,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.340475,-99) , 
1, 31.0469, 1, 0, 0.497597,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.541359,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.106245,-99) , 
0, 0.0165918, 1, 0, 0.396793,-99) , 
1, 61.2162, 1, 0, 0.494898,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.543523,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.527308,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.159995,-99) , 
0, 0.021965, 1, 0, 0.284555,-99) , 
2, 1.66118, 0, 0, 0.364997,-99) , 
4, 22.0177, 1, 0, 0.492134,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.491318,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0675959);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502395,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.450786,-99) , 
0, 0.02244, 0, 0, 0.491611,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.629513,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.354465,-99) , 
8, 0.0217614, 0, 0, 0.426468,-99) , 
4, 15.1239, 1, 0, 0.486407,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.643317,-99) , 
NN2(
0, 
0, 
-1, 1.51246, 0, -1, 0.303087,-99) , 
4, 9.89956, 0, 0, 0.397713,-99) , 
6, 2.13338, 1, 0, 0.483473,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.656238,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.400154,-99) , 
10, 2.22222, 1, 0, 0.49358,-99) , 
NN2(
0, 
0, 
-1, 9.18397, 0, -1, 0.0916972,-99) , 
7, 1.33261, 1, 0, 0.457845,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.576229,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 7.82366, 1, 0, 0.30387,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 10.5556, 0, 0, 0.114808,-99) , 
0, 0.0670046, 1, 0, 0.373482,-99) , 
3, 0.582858, 0, 0, 0.479913,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0551648);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.472446,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0293457);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.00955039, 1, -1, 0.491411,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508313,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.476386,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.782958, 0, 0, 0.421834,-99) , 
0, 0.150059, 1, 0, 0.486961,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.486212,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0426088);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504587,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.240327,-99) , 
9, -0.0146299, 0, 0, 0.501155,-99) , 
NN2(
0, 
0, 
-1, 0.820471, 1, -1, 0.380001,-99) , 
9, 0.00955039, 1, 0, 0.498746,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.498029,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.58647,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.352907,-99) , 
10, 2.11111, 1, 0, 0.499296,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.467581,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.415656,-99) , 
0, 0.150059, 1, 0, 0.492768,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0331508);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.483431,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0180526);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 29.6817, 1, -1, 0.497071,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506995,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.476121,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.782958, 0, 0, 0.423726,-99) , 
0, 0.150059, 1, 0, 0.492433,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.491713,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0308655);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504354,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.315643,-99) , 
6, -2.26534, 0, 0, 0.502908,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.299927,-99) , 
4, 29.6817, 1, 0, 0.501584,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.500896,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531515,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.61213, 0, 0, 0.50079,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.469846,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.419485,-99) , 
0, 0.150059, 1, 0, 0.495749,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0271097);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, -2.01048, 0, -1, 0.495364,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517272,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.118304,-99) , 
1, 10.7382, 0, 0, 0.297152,-99) , 
7, 2.26463, 1, 0, 0.494085,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.493418,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.519027,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.70204, 0, 0, 0.494156,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.463825,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.414678,-99) , 
0, 0.150059, 1, 0, 0.488457,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0372757);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.506509,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.433151,-99) , 
7, -2.01048, 0, 0, 0.502141,-99) , 
NN2(
0, 
0, 
-1, 0.865646, 0, -1, 0.296649,-99) , 
7, 2.26463, 1, 0, 0.500823,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.500156,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.51764,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.61213, 0, 0, 0.488332,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.45841,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.410345,-99) , 
0, 0.150059, 1, 0, 0.494513,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0293594);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.492079,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.51313,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.110214,-99) , 
5, 6.61002, 1, 0, 0.480423,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.451092,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.404471,-99) , 
0, 0.150059, 1, 0, 0.486596,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0234343);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502519,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.310738,-99) , 
7, 2.26463, 1, 0, 0.501296,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.310603,-99) , 
4, 29.6817, 1, 0, 0.500064,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.499419,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.502821,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.61213, 0, 0, 0.474369,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.445653,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.400116,-99) , 
0, 0.150059, 1, 0, 0.493222,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0248933);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0.348216, 0, -1, 0.493724,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501117,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.1109,-99) , 
5, 6.61002, 1, 0, 0.469456,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.441045,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.396398,-99) , 
0, 0.150059, 1, 0, 0.487664,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0311518);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504921,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.390871,-99) , 
9, 0.00955039, 1, 0, 0.502701,-99) , 
NN2(
0, 
0, 
-1, 0.679679, 0, -1, 0.39906,-99) , 
4, 22.4877, 1, 0, 0.500578,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.499947,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.392683,-99) , 
0, 0.150059, 1, 0, 0.493284,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0265494);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 2.01119, 1, -1, 0.494685,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.539329,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0462532,-99) , 
9, -0.00122495, 0, 0, 0.326575,-99) , 
6, -2.26534, 0, 0, 0.493405,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.492793,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.500055,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, -1.61213, 0, 0, 0.472092,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 1.32774, 1, 0, 0.444104,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.400136,-99) , 
0, 0.150059, 1, 0, 0.487053,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0364947);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.505409,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.432413,-99) , 
6, 2.01119, 1, 0, 0.501322,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.532726,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0474386,-99) , 
9, -0.00122495, 0, 0, 0.32465,-99) , 
6, -2.26534, 0, 0, 0.499984,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.499372,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517038,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.247234,-99) , 
2, 1.94291, 1, 0, 0.46653,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 1.186, 1, 0, 0.438862,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.776064, 0, 0, 0.395875,-99) , 
0, 0.150059, 1, 0, 0.492976,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0299531);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 2.13138, 1, -1, 0.493219,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.523632,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0491152,-99) , 
9, -0.00122495, 0, 0, 0.321968,-99) , 
6, -2.26534, 0, 0, 0.491931,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 0.348216, 0, 0, 0.49134,-99) , 
NN2(
0, 
0, 
-1, 0.776064, 0, -1, 0.391911,-99) , 
0, 0.150059, 1, 0, 0.485219,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
