// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.27/06       [334598]
Creator        : tinti_g
Date           : Thu Jan 19 21:20:47 2012
Host           : Linux lxbuild151.cern.ch 2.6.18-194.11.3.el5.cve20103081 #1 SMP Thu Sep 16 15:17:10 CEST 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/tinti_g/TMVA/test
Training events: 8297
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "3.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "200" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "25" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "8297" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
alpha                         alpha                         alpha                         pointing angle                                                  'F'    [0.000196760316612,0.199997276068]
fls3d                         fls3d                         fls3d                         3D flight length significance                                   'F'    [5.00062417984,210.749984741]
iso                           iso                           iso                           isolation                                                       'F'    [0.043730456382,1]
m1eta                         m1eta                         m1eta                         m1 #eta                                                         'F'    [-1.39817726612,1.39961600304]
m2eta                         m2eta                         m2eta                         m2 #eta                                                         'F'    [-1.39924478531,1.39976394176]
pvlips                        pvlips                        pvlips                        PV  lz IP significance                                          'F'    [-2.95721960068,2.76474046707]
closetrk                      closetrk                      closetrk                      N^{#DeltaR}_{trk}                                               'F'    [0,20]
prob                          prob                          prob                          B candidate probability                                         'F'    [2.3720624423e-11,0.999926567078]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "alpha", "fls3d", "iso", "m1eta", "m2eta", "pvlips", "closetrk", "prob" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.000196760316612199;
      fVmax[0] = 0.199997276067734;
      fVmin[1] = 5.00062417984009;
      fVmax[1] = 210.749984741211;
      fVmin[2] = 0.0437304563820362;
      fVmax[2] = 1;
      fVmin[3] = -1.39817726612091;
      fVmax[3] = 1.3996160030365;
      fVmin[4] = -1.39924478530884;
      fVmax[4] = 1.39976394176483;
      fVmin[5] = -2.95721960067749;
      fVmax[5] = 2.76474046707153;
      fVmin[6] = 0;
      fVmax[6] = 20;
      fVmin[7] = 2.37206244230181e-11;
      fVmax[7] = 0.999926567077637;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.81812608644954);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177016,-99) , 
7, 0.23078, 0, 0, 0.540188,-99) , 
NN(
0, 
0, 
-1, 0.0432144, 1, -1, 0.0328461,-99) , 
0, 0.0229945, 1, 0, 0.0717402,-99) , 
NN(
0, 
0, 
-1, 0.926441, 0, -1, 0.00159111,-99) , 
6, 0.769231, 1, 0, 0.00301437,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.30791);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234214,-99) , 
2, 0.84323, 0, 0, 0.613622,-99) , 
NN(
0, 
0, 
-1, 0.0689872, 1, -1, 0.107839,-99) , 
0, 0.038193, 1, 0, 0.223621,-99) , 
NN(
0, 
0, 
-1, 0.926441, 0, -1, 0.0097219,-99) , 
6, 0.769231, 1, 0, 0.0148491,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.974833);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.755658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418586,-99) , 
3, -0.323165, 0, 0, 0.583165,-99) , 
NN(
0, 
0, 
-1, 0.423046, 0, -1, 0.104699,-99) , 
0, 0.092089, 1, 0, 0.305771,-99) , 
NN(
0, 
0, 
-1, 0.0309353, 1, -1, 0.0236593,-99) , 
2, 0.926441, 0, 0, 0.0454511,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.781594);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452402,-99) , 
1, 13.6485, 0, 0, 0.698147,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.110184,-99) , 
2, 0.972222, 0, 0, 0.22798,-99) , 
0, 0.0536216, 1, 0, 0.427421,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.137267,-99) , 
0, 0.0632043, 1, 0, 0.21816,-99) , 
NN(
0, 
0, 
-1, 0.0398249, 1, -1, 0.0238906,-99) , 
2, 0.852882, 0, 0, 0.0536807,-99) , 
6, 1.53846, 1, 0, 0.0948596,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.613896);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323793,-99) , 
7, 0.230642, 0, 0, 0.512876,-99) , 
NN(
0, 
0, 
-1, 0.957566, 0, -1, 0.199227,-99) , 
0, 0.0923841, 1, 0, 0.345387,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.132773,-99) , 
2, 0.659568, 0, 0, 0.310176,-99) , 
NN(
0, 
0, 
-1, 0.726838, 0, -1, 0.027486,-99) , 
0, 0.039082, 1, 0, 0.0518281,-99) , 
2, 0.816102, 0, 0, 0.13559,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.494346);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460858,-99) , 
0, 0.0308188, 1, 0, 0.521579,-99) , 
NN(
0, 
0, 
-1, 0.922205, 0, -1, 0.287303,-99) , 
6, 2.19231, 1, 0, 0.391359,-99) , 
NN(
0, 
0, 
-1, 0.0620699, 1, -1, 0.0750397,-99) , 
2, 0.816102, 0, 0, 0.176397,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.393831);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289655,-99) , 
3, 0.861668, 1, 0, 0.513192,-99) , 
NN(
0, 
0, 
-1, 0.890054, 0, -1, 0.244912,-99) , 
0, 0.153842, 1, 0, 0.459616,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218315,-99) , 
6, 3.07692, 1, 0, 0.352983,-99) , 
NN(
0, 
0, 
-1, 0.0880739, 1, -1, 0.0562949,-99) , 
0, 0.0467447, 1, 0, 0.0985069,-99) , 
2, 0.779322, 0, 0, 0.249311,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.350984);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479186,-99) , 
7, 0.692257, 0, 0, 0.537871,-99) , 
NN(
0, 
0, 
-1, 0.0770431, 1, -1, 0.323334,-99) , 
2, 0.901017, 0, 0, 0.412755,-99) , 
NN(
0, 
0, 
-1, 0.0620558, 1, -1, 0.100135,-99) , 
2, 0.742543, 0, 0, 0.259739,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.301622);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40281,-99) , 
3, -0.859766, 0, 0, 0.589835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311086,-99) , 
2, 0.88122, 0, 0, 0.402205,-99) , 
6, 2.19231, 1, 0, 0.481589,-99) , 
NN(
0, 
0, 
-1, 0.0620558, 1, -1, 0.136492,-99) , 
2, 0.742543, 0, 0, 0.321508,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.25821);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407129,-99) , 
6, 6.23077, 1, 0, 0.53467,-99) , 
NN(
0, 
0, 
-1, 0.852981, 0, -1, 0.352894,-99) , 
0, 0.100097, 1, 0, 0.454176,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183819,-99) , 
7, 0.285679, 0, 0, 0.399092,-99) , 
NN(
0, 
0, 
-1, 0.0886779, 1, -1, 0.069665,-99) , 
0, 0.0620958, 1, 0, 0.146933,-99) , 
2, 0.705763, 0, 0, 0.337125,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.212519);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291526,-99) , 
4, -1.18344, 0, 0, 0.505142,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266441,-99) , 
0, 0.0541642, 1, 0, 0.329613,-99) , 
7, 0.153835, 0, 0, 0.462075,-99) , 
NN(
0, 
0, 
-1, 0.0850717, 1, -1, 0.160257,-99) , 
2, 0.705763, 0, 0, 0.351887,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.219753);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313235,-99) , 
3, 0.968883, 1, 0, 0.543986,-99) , 
NN(
0, 
0, 
-1, 0.0770431, 1, -1, 0.388201,-99) , 
2, 0.97454, 0, 0, 0.425116,-99) , 
NN(
0, 
0, 
-1, 0.0697544, 1, -1, 0.170469,-99) , 
2, 0.668984, 0, 0, 0.348444,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.167834);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458806,-99) , 
0, 0.0238412, 1, 0, 0.478989,-99) , 
NN(
0, 
0, 
-1, 0.830271, 0, -1, 0.312466,-99) , 
0, 0.153889, 1, 0, 0.448842,-99) , 
NN(
0, 
0, 
-1, 0.0637514, 1, -1, 0.180116,-99) , 
2, 0.632204, 0, 0, 0.383262,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.153819);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410152,-99) , 
7, 0.153788, 0, 0, 0.512086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130741,-99) , 
2, 0.830271, 0, 0, 0.349604,-99) , 
0, 0.153889, 1, 0, 0.483223,-99) , 
NN(
0, 
0, 
-1, 0.0637514, 1, -1, 0.206242,-99) , 
2, 0.632204, 0, 0, 0.417754,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.14339);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334726,-99) , 
5, 1.19621, 1, 0, 0.503319,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210697,-99) , 
2, 0.844456, 0, 0, 0.36643,-99) , 
0, 0.123151, 1, 0, 0.458768,-99) , 
NN(
0, 
0, 
-1, 0.0637514, 1, -1, 0.20283,-99) , 
2, 0.595424, 0, 0, 0.411328,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.13652);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343436,-99) , 
3, -0.90243, 0, 0, 0.467231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252247,-99) , 
3, 1.1844, 1, 0, 0.451662,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190167,-99) , 
7, 0.248639, 0, 0, 0.472986,-99) , 
NN(
0, 
0, 
-1, 14.6154, 0, -1, 0.105466,-99) , 
0, 0.0850717, 1, 0, 0.263831,-99) , 
2, 0.668984, 0, 0, 0.400948,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.180364);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390996,-99) , 
3, -0.37602, 0, 0, 0.467975,-99) , 
NN(
0, 
0, 
-1, 0.406908, 1, -1, 0.366589,-99) , 
3, 0.646364, 1, 0, 0.441484,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249843,-99) , 
7, 0.248096, 0, 0, 0.469005,-99) , 
NN(
0, 
0, 
-1, 14.6154, 0, -1, 0.130521,-99) , 
0, 0.0850717, 1, 0, 0.281088,-99) , 
2, 0.705763, 0, 0, 0.3911,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.144087);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449931,-99) , 
6, 1.46154, 1, 0, 0.473928,-99) , 
NN(
0, 
0, 
-1, 0.796529, 0, -1, 0.339428,-99) , 
0, 0.161574, 1, 0, 0.455248,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349758,-99) , 
1, 10.1842, 0, 0, 0.480309,-99) , 
NN(
0, 
0, 
-1, 0.241462, 0, -1, 0.175506,-99) , 
0, 0.0697544, 1, 0, 0.286935,-99) , 
2, 0.705763, 0, 0, 0.403388,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.105485);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.153889, 1, -1, 0.466614,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336132,-99) , 
0, 0.039027, 1, 0, 0.417653,-99) , 
NN(
0, 
0, 
-1, 14.6154, 0, -1, 0.123191,-99) , 
0, 0.100389, 1, 0, 0.285051,-99) , 
2, 0.668984, 0, 0, 0.420708,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0987749);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343719,-99) , 
3, 1.1844, 1, 0, 0.504248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328793,-99) , 
5, -1.63677, 0, 0, 0.492936,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317859,-99) , 
7, 0.506888, 0, 0, 0.425634,-99) , 
NN(
0, 
0, 
-1, 14.6154, 0, -1, 0.135045,-99) , 
0, 0.100389, 1, 0, 0.296635,-99) , 
2, 0.668984, 0, 0, 0.444141,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0935811);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.194275,-99) , 
1, 52.4848, 1, 0, 0.496075,-99) , 
NN(
0, 
0, 
-1, 0.796529, 0, -1, 0.381646,-99) , 
0, 0.161574, 1, 0, 0.48051,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38543,-99) , 
0, 0.0313869, 1, 0, 0.435447,-99) , 
NN(
0, 
0, 
-1, 0.471228, 0, -1, 0.166691,-99) , 
0, 0.100389, 1, 0, 0.317925,-99) , 
2, 0.705763, 0, 0, 0.432557,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.103459);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267026,-99) , 
1, 28.7442, 1, 0, 0.499146,-99) , 
NN(
0, 
0, 
-1, 0.84441, 0, -1, 0.409686,-99) , 
7, 0.423046, 0, 0, 0.45388,-99) , 
NN(
0, 
0, 
-1, 0.511396, 0, -1, 0.276928,-99) , 
2, 0.595424, 0, 0, 0.425584,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0866718);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.153889, 1, -1, 0.455458,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.238931,-99) , 
3, -0.429544, 0, 0, 0.447395,-99) , 
NN(
0, 
0, 
-1, 0.0712823, 1, -1, 0.168797,-99) , 
7, 0.511396, 0, 0, 0.298115,-99) , 
2, 0.595424, 0, 0, 0.430658,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.068294);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353862,-99) , 
4, -1.18344, 0, 0, 0.494458,-99) , 
NN(
0, 
0, 
-1, 0.797793, 0, -1, 0.388712,-99) , 
0, 0.153889, 1, 0, 0.477023,-99) , 
NN(
0, 
0, 
-1, 0.0637514, 1, -1, 0.301237,-99) , 
2, 0.595424, 0, 0, 0.449668,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0823177);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.207941,-99) , 
1, 52.4833, 1, 0, 0.495992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323922,-99) , 
4, 1.1845, 1, 0, 0.485234,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444494,-99) , 
6, 2.30769, 1, 0, 0.483221,-99) , 
NN(
0, 
0, 
-1, 0.358, 0, -1, 0.211097,-99) , 
0, 0.10036, 1, 0, 0.368174,-99) , 
2, 0.742543, 0, 0, 0.444101,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0749002);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.521865, 0, -1, 0.437905,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0524302);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.521865, 0, -1, 0.456419,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0580314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401591,-99) , 
5, 1.24236, 1, 0, 0.495194,-99) , 
NN(
0, 
0, 
-1, 4.15385, 1, -1, 0.337074,-99) , 
5, -1.63677, 0, 0, 0.484797,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295461,-99) , 
0, 0.117555, 1, 0, 0.434375,-99) , 
NN(
0, 
0, 
-1, 0.093951, 1, -1, 0.125365,-99) , 
7, 0.361743, 0, 0, 0.312757,-99) , 
2, 0.521865, 0, 0, 0.469454,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0670106);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431709,-99) , 
5, 0.894202, 1, 0, 0.493394,-99) , 
NN(
0, 
0, 
-1, -0.646222, 0, -1, 0.398145,-99) , 
5, -0.976541, 0, 0, 0.476315,-99) , 
NN(
0, 
0, 
-1, 0.361743, 0, -1, 0.313368,-99) , 
2, 0.521865, 0, 0, 0.461902,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0693468);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344764,-99) , 
3, -1.21609, 0, 0, 0.49043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.901447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356918,-99) , 
0, 0.0231771, 1, 0, 0.393312,-99) , 
3, 0.969186, 1, 0, 0.477381,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251691,-99) , 
0, 0.140027, 1, 0, 0.500273,-99) , 
NN(
0, 
0, 
-1, 0.0712823, 1, -1, 0.227508,-99) , 
7, 0.511396, 0, 0, 0.361276,-99) , 
2, 0.595424, 0, 0, 0.460162,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0776881);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463021,-99) , 
0, 0.0250232, 1, 0, 0.475116,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.118543,-99) , 
2, 0.798045, 0, 0, 0.380567,-99) , 
0, 0.161574, 1, 0, 0.463158,-99) , 
NN(
0, 
0, 
-1, 0.361743, 0, -1, 0.329259,-99) , 
2, 0.521865, 0, 0, 0.451539,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0742721);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485596,-99) , 
3, -0.643234, 1, 0, 0.503444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376481,-99) , 
6, 2.30769, 1, 0, 0.432289,-99) , 
4, -0.430004, 0, 0, 0.480188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500904,-99) , 
NN(
0, 
0, 
-1, 6.66383, 1, -1, 0.19807,-99) , 
2, 0.816102, 0, 0, 0.359586,-99) , 
0, 0.161574, 1, 0, 0.464448,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.088997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469798,-99) , 
4, 0.344132, 1, 0, 0.518463,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414265,-99) , 
0, 0.0249996, 1, 0, 0.437161,-99) , 
4, -0.430004, 0, 0, 0.491972,-99) , 
NN(
0, 
0, 
-1, 0.816102, 0, -1, 0.356845,-99) , 
0, 0.161574, 1, 0, 0.474442,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0523887);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411902,-99) , 
3, -1.07499, 0, 0, 0.506792,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248857,-99) , 
7, 0.499859, 0, 0, 0.371385,-99) , 
4, -1.18344, 0, 0, 0.498152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504585,-99) , 
NN(
0, 
0, 
-1, 6.66383, 1, -1, 0.225285,-99) , 
2, 0.816102, 0, 0, 0.377521,-99) , 
0, 0.161574, 1, 0, 0.4826,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0314997);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.184628, 1, -1, 0.473774,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0360296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38287,-99) , 
2, 0.4984, 0, 0, 0.498604,-99) , 
NN(
0, 
0, 
-1, 5.38462, 1, -1, 0.352519,-99) , 
5, -1.63677, 0, 0, 0.489551,-99) , 
NN(
0, 
0, 
-1, 0.686952, 0, -1, 0.293691,-99) , 
0, 0.184628, 1, 0, 0.481633,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0671713);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467651,-99) , 
7, 0.499963, 0, 0, 0.499485,-99) , 
NN(
0, 
0, 
-1, 0.768141, 0, -1, 0.386347,-99) , 
5, 1.41481, 1, 0, 0.489212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34913,-99) , 
7, 0.268817, 0, 0, 0.46804,-99) , 
NN(
0, 
0, 
-1, 9.23077, 0, -1, 0.188299,-99) , 
2, 0.742543, 0, 0, 0.381821,-99) , 
0, 0.161574, 1, 0, 0.475487,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0377192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49857,-99) , 
1, 60.3968, 0, 0, 0.500347,-99) , 
NN(
0, 
0, 
-1, 0.499859, 0, -1, 0.372869,-99) , 
4, -1.18344, 0, 0, 0.492332,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292886,-99) , 
2, 0.791302, 0, 0, 0.456357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.176038,-99) , 
1, 8.32703, 1, 0, 0.382341,-99) , 
0, 0.161574, 1, 0, 0.478361,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.052589);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358837,-99) , 
3, 1.29202, 1, 0, 0.509711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279443,-99) , 
7, 0.499859, 0, 0, 0.38173,-99) , 
4, -1.18344, 0, 0, 0.501699,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300758,-99) , 
2, 0.791302, 0, 0, 0.454037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181576,-99) , 
1, 8.32703, 1, 0, 0.382511,-99) , 
0, 0.161574, 1, 0, 0.48664,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0522842);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442625,-99) , 
0, 0.118122, 1, 0, 0.499339,-99) , 
NN(
0, 
0, 
-1, 0.768141, 0, -1, 0.399823,-99) , 
5, 1.41481, 1, 0, 0.490344,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.247948,-99) , 
2, 0.756518, 0, 0, 0.433254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.114625,-99) , 
1, 9.99023, 1, 0, 0.382753,-99) , 
0, 0.161574, 1, 0, 0.476836,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0488101);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477582,-99) , 
6, 14.6154, 0, 0, 0.486368,-99) , 
NN(
0, 
0, 
-1, 5.38462, 1, -1, 0.359512,-99) , 
5, -1.63677, 0, 0, 0.47852,-99) , 
NN(
0, 
0, 
-1, 0.686952, 0, -1, 0.297742,-99) , 
0, 0.184628, 1, 0, 0.471476,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0456657);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375593,-99) , 
1, 28.7435, 1, 0, 0.502804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242963,-99) , 
7, 0.511231, 0, 0, 0.386181,-99) , 
2, 0.5008, 0, 0, 0.494877,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285809,-99) , 
2, 0.791302, 0, 0, 0.435924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.125256,-99) , 
1, 9.99023, 1, 0, 0.387854,-99) , 
0, 0.161574, 1, 0, 0.481581,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0323219);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.184628, 1, -1, 0.473091,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0233614);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359945,-99) , 
3, 1.29202, 1, 0, 0.495446,-99) , 
NN(
0, 
0, 
-1, 5.38462, 1, -1, 0.371588,-99) , 
5, -1.63677, 0, 0, 0.487826,-99) , 
NN(
0, 
0, 
-1, 0.686952, 0, -1, 0.313142,-99) , 
0, 0.184628, 1, 0, 0.481155,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0775088);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466757,-99) , 
3, 0.216913, 1, 0, 0.502084,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404727,-99) , 
3, -0.379391, 0, 0, 0.444116,-99) , 
4, -0.430004, 0, 0, 0.483083,-99) , 
NN(
0, 
0, 
-1, 0.686952, 0, -1, 0.318189,-99) , 
0, 0.184628, 1, 0, 0.476809,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0479351);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3907,-99) , 
1, 28.7435, 1, 0, 0.502438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260897,-99) , 
7, 0.511231, 0, 0, 0.394466,-99) , 
2, 0.5008, 0, 0, 0.495147,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288749,-99) , 
7, 0.274011, 0, 0, 0.508451,-99) , 
NN(
0, 
0, 
-1, 0.779322, 0, -1, 0.285853,-99) , 
1, 6.66383, 1, 0, 0.401381,-99) , 
0, 0.161574, 1, 0, 0.483684,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.111508);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495557,-99) , 
4, -0.429483, 0, 0, 0.562243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31603,-99) , 
6, 1.23077, 1, 0, 0.410158,-99) , 
0, 0.0616103, 0, 0, 0.508353,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468017,-99) , 
4, -0.320725, 0, 0, 0.540237,-99) , 
NN(
0, 
0, 
-1, 0.350837, 0, -1, 0.350461,-99) , 
0, 0.0850578, 1, 0, 0.450601,-99) , 
2, 0.852882, 0, 0, 0.475248,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0274509);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43452,-99) , 
7, 0.115376, 0, 0, 0.48943,-99) , 
NN(
0, 
0, 
-1, 5.38462, 1, -1, 0.380719,-99) , 
5, -1.63677, 0, 0, 0.482854,-99) , 
NN(
0, 
0, 
-1, 0.686952, 0, -1, 0.345736,-99) , 
0, 0.184628, 1, 0, 0.477779,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0543471);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617033,-99) , 
NN(
0, 
0, 
-1, 0.112548, 0, -1, 0.48023,-99) , 
7, 0.0384587, 1, 0, 0.487828,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454753,-99) , 
0, 0.0361741, 1, 0, 0.497524,-99) , 
NN(
0, 
0, 
-1, 0.250087, 0, -1, 0.251413,-99) , 
0, 0.115706, 1, 0, 0.425708,-99) , 
2, 0.668984, 0, 0, 0.47428,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0561033);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384383,-99) , 
4, 1.18446, 1, 0, 0.506621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239173,-99) , 
3, -0.320962, 0, 0, 0.375331,-99) , 
1, 28.7433, 1, 0, 0.499902,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343712,-99) , 
5, 0.94322, 1, 0, 0.503479,-99) , 
NN(
0, 
0, 
-1, 0.250087, 0, -1, 0.261779,-99) , 
0, 0.115706, 1, 0, 0.433458,-99) , 
2, 0.668984, 0, 0, 0.485468,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
