// Class: ReadBDT2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT2::BDT2
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.27/06       [334598]
Creator        : tinti_g
Date           : Sun Dec 18 16:38:07 2011
Host           : Linux lxbuild151.cern.ch 2.6.18-194.11.3.el5.cve20103081 #1 SMP Thu Sep 16 15:17:10 CEST 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/tinti_g/TMVA/test
Training events: 12918
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "80" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "5.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "250" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "35" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "4" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "12918" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT2 training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
alpha                         alpha                         alpha                         pointing angle                                                  'F'    [0.000227197029744,0.199997499585]
fls3d                         fls3d                         fls3d                         3D flight length significance                                   'F'    [5.00079488754,235.267944336]
iso                           iso                           iso                           isolation                                                       'F'    [0.0992664992809,1]
m1pt                          m1pt                          m1pt                          m1pt (GeV)                                                      'F'    [4.50167798996,66.7366409302]
m2pt                          m2pt                          m2pt                          m2pt (GeV)                                                      'F'    [4.00001239777,21.5767230988]
m1eta                         m1eta                         m1eta                         m1 #eta                                                         'F'    [-2.39785766602,2.39998412132]
m2eta                         m2eta                         m2eta                         m2 #eta                                                         'F'    [-2.39862179756,2.39984822273]
docatrk                       docatrk                       docatrk                       doca (cm)                                                       'F'    [1.44957757584e-05,24.5759887695]
pvlips                        pvlips                        pvlips                        PV IP significance                                              'F'    [-2.49630880356,2.49772047997]
closetrk                      closetrk                      closetrk                      N^{#DeltaR}_{trk}                                               'F'    [0,20]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN2 new BDT2Node
   
#ifndef BDT2Node__def
#define BDT2Node__def
   
class BDT2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT2Node ( BDT2Node* left,BDT2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT2Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT2Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT2Node*   fLeft;     // pointer to the left daughter node
   BDT2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT2Node::~BDT2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT2 : public IClassifierReader {

 public:

   // constructor
   ReadBDT2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT2" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "alpha", "fls3d", "iso", "m1pt", "m2pt", "m1eta", "m2eta", "docatrk", "pvlips", "closetrk" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.000227197029744275;
      fVmax[0] = 0.199997499585152;
      fVmin[1] = 5.00079488754272;
      fVmax[1] = 235.267944335938;
      fVmin[2] = 0.0992664992809296;
      fVmax[2] = 1;
      fVmin[3] = 4.50167798995972;
      fVmax[3] = 66.7366409301758;
      fVmin[4] = 4.00001239776611;
      fVmax[4] = 21.5767230987549;
      fVmin[5] = -2.39785766601562;
      fVmax[5] = 2.39998412132263;
      fVmin[6] = -2.39862179756165;
      fVmax[6] = 2.39984822273254;
      fVmin[7] = 1.44957757584052e-05;
      fVmax[7] = 24.5759887695312;
      fVmin[8] = -2.49630880355835;
      fVmax[8] = 2.49772047996521;
      fVmin[9] = 0;
      fVmax[9] = 20;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT2Node*)current->GetRight();
         else current=(BDT2Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(3.80557346558751);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 0.0113255, 1, -1, 0.000494659,-99)    );
  // itree = 1
  fBoostWeights.push_back(2.09822);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 24.2426, 0, 1, 0.745167,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.118165,-99) , 
9, 1.16667, 1, 0, 0.440618,-99) , 
NN2(
0, 
0, 
-1, 0.0270589, 1, -1, 0.00991518,-99) , 
0, 0.0168747, 1, 0, 0.0217623,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.31895);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.0163904, 0, 1, 0.789578,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.468623,-99) , 
1, 11.398, 0, 0, 0.646066,-99) , 
NN2(
0, 
0, 
-1, 0.71607, 0, -1, 0.147532,-99) , 
2, 0.832133, 0, 0, 0.401117,-99) , 
NN2(
0, 
0, 
-1, 0.899918, 0, -1, 0.0349115,-99) , 
0, 0.0390714, 1, 0, 0.0922325,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.905737);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.826579,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.478463,-99) , 
0, 0.016888, 0, 0, 0.722441,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.597205,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.361927,-99) , 
3, 8.53226, 1, 0, 0.49115,-99) , 
2, 0.896205, 0, 0, 0.624541,-99) , 
NN2(
0, 
0, 
-1, 9.41973, 0, -1, 0.182943,-99) , 
2, 0.712228, 0, 0, 0.517027,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.547234,-99) , 
NN2(
0, 
0, 
-1, 1.59785, 1, -1, 0.206116,-99) , 
0, 0.0917908, 1, 0, 0.330135,-99) , 
NN2(
0, 
0, 
-1, 0.795507, 0, -1, 0.0375604,-99) , 
2, 0.97498, 0, 0, 0.0903694,-99) , 
0, 0.0501698, 1, 0, 0.211094,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.714856);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.691632,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.385353,-99) , 
5, -1.90768, 0, 0, 0.635292,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.36093,-99) , 
5, 1.9964, 1, 0, 0.592982,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.538056,-99) , 
NN2(
0, 
0, 
-1, 0.0452829, 1, -1, 0.166639,-99) , 
0, 0.0274394, 1, 0, 0.319803,-99) , 
2, 0.784171, 0, 0, 0.498695,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.629444,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.291335,-99) , 
6, -1.06846, 0, 0, 0.418561,-99) , 
NN2(
0, 
0, 
-1, 1.88012, 1, -1, 0.155968,-99) , 
5, 1.46551, 1, 0, 0.33806,-99) , 
NN2(
0, 
0, 
-1, 0.766438, 0, -1, 0.0510175,-99) , 
2, 0.899918, 0, 0, 0.132981,-99) , 
0, 0.0612681, 1, 0, 0.277583,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.46486);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.0113241, 1, 1, 0.536068,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.27925,-99) , 
6, 1.99897, 1, 0, 0.506988,-99) , 
NN2(
0, 
0, 
-1, 0.962471, 0, -1, 0.245039,-99) , 
0, 0.100112, 1, 0, 0.430822,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.527148,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.189457,-99) , 
1, 9.41973, 0, 0, 0.387437,-99) , 
NN2(
0, 
0, 
-1, 0.643371, 0, -1, 0.0404859,-99) , 
0, 0.0447325, 1, 0, 0.13509,-99) , 
2, 0.774817, 0, 0, 0.313837,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.494173);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.749438,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.593919,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.386458,-99) , 
5, 1.13673, 1, 0, 0.481398,-99) , 
NN2(
0, 
0, 
-1, -0.196738, 0, -1, 0.32135,-99) , 
5, -1.73176, 0, 0, 0.443727,-99) , 
0, 0.011359, 1, 0, 0.464022,-99) , 
NN2(
0, 
0, 
-1, 0.0945276, 1, -1, 0.20944,-99) , 
2, 0.899918, 0, 0, 0.30771,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.407102);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 1.41667, 0, 1, 0.647419,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.306639,-99) , 
8, 0.300317, 1, 0, 0.567631,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.59754,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.420711,-99) , 
4, 5.08885, 0, 0, 0.475786,-99) , 
NN2(
0, 
0, 
-1, 0.0936577, 1, -1, 0.308775,-99) , 
2, 0.936759, 0, 0, 0.378704,-99) , 
0, 0.0335222, 1, 0, 0.438628,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.515688,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.240237,-99) , 
2, 0.569789, 0, 0, 0.405108,-99) , 
NN2(
0, 
0, 
-1, 0.642756, 0, -1, 0.0389267,-99) , 
0, 0.0447325, 1, 0, 0.151261,-99) , 
2, 0.674735, 0, 0, 0.378603,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.3005);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.549442,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.311284,-99) , 
6, -1.99849, 0, 0, 0.523225,-99) , 
NN2(
0, 
0, 
-1, -1.46335, 0, -1, 0.255379,-99) , 
8, -0.893303, 0, 0, 0.492705,-99) , 
NN2(
0, 
0, 
-1, 0.936763, 0, -1, 0.226709,-99) , 
8, 1.11049, 1, 0, 0.470591,-99) , 
NN2(
0, 
0, 
-1, 0.0447325, 1, -1, 0.167444,-99) , 
2, 0.674735, 0, 0, 0.411721,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.242889);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 16.6043, 1, -1, 0.460769,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.666303,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.393086,-99) , 
3, 6.00391, 0, 0, 0.539497,-99) , 
NN2(
0, 
0, 
-1, 1.05556, 1, -1, 0.0862538,-99) , 
2, 0.961084, 0, 0, 0.298058,-99) , 
0, 0.122309, 1, 0, 0.433311,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531123,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.331326,-99) , 
3, 8.56642, 1, 0, 0.447033,-99) , 
NN2(
0, 
0, 
-1, 5.27285, 1, -1, 0.0301696,-99) , 
0, 0.0457913, 1, 0, 0.184311,-99) , 
2, 0.649715, 0, 0, 0.394832,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.271904);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.553468,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.308217,-99) , 
5, -2.12997, 0, 0, 0.535019,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.23935,-99) , 
3, 16.6043, 1, 0, 0.521397,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.596063,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.292865,-99) , 
5, 1.19828, 1, 0, 0.516029,-99) , 
NN2(
0, 
0, 
-1, 0.00722395, 1, -1, 0.0798565,-99) , 
2, 0.912439, 0, 0, 0.3155,-99) , 
0, 0.122309, 1, 0, 0.488403,-99) , 
NN2(
0, 
0, 
-1, 0.0457913, 1, -1, 0.194568,-99) , 
2, 0.649715, 0, 0, 0.445368,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.247408);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531115,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.361783,-99) , 
6, -1.82484, 0, 0, 0.495281,-99) , 
NN2(
0, 
0, 
-1, 0.406363, 1, -1, 0.354298,-99) , 
6, 1.73339, 1, 0, 0.466404,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.597967,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.354573,-99) , 
7, 0.0114537, 0, 0, 0.505291,-99) , 
NN2(
0, 
0, 
-1, 1.05556, 1, -1, 0.107349,-99) , 
2, 0.964556, 0, 0, 0.292397,-99) , 
0, 0.122309, 1, 0, 0.439445,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.157704,-99) , 
2, 0.574654, 0, 0, 0.417171,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.230183);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.798871,-99) , 
NN2(
0, 
0, 
-1, 14.8758, 1, -1, 0.448336,-99) , 
0, 0.0045428, 1, 0, 0.45908,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.541168,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.332187,-99) , 
5, -1.59469, 0, 0, 0.47274,-99) , 
NN2(
0, 
0, 
-1, 0.104995, 1, -1, 0.154484,-99) , 
5, 1.73314, 1, 0, 0.424186,-99) , 
NN2(
0, 
0, 
-1, 6.04402, 1, -1, 0.0800612,-99) , 
2, 0.749796, 0, 0, 0.328424,-99) , 
0, 0.0779156, 1, 0, 0.410947,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.230543);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.547808,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.391044,-99) , 
3, 14.8758, 1, 0, 0.532511,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.273797,-99) , 
8, 1.09574, 1, 0, 0.521528,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.181513,-99) , 
8, -1.10606, 0, 0, 0.513038,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.536039,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.348385,-99) , 
2, 0.958325, 0, 0, 0.452059,-99) , 
NN2(
0, 
0, 
-1, 0.104995, 1, -1, 0.186992,-99) , 
5, 1.73314, 1, 0, 0.413744,-99) , 
NN2(
0, 
0, 
-1, 6.04402, 1, -1, 0.0987374,-99) , 
2, 0.749796, 0, 0, 0.330607,-99) , 
0, 0.0779156, 1, 0, 0.447292,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.190291);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.622469,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.467789,-99) , 
4, 6.92958, 0, 0, 0.483957,-99) , 
NN2(
0, 
0, 
-1, -1.45965, 0, -1, 0.3189,-99) , 
8, -0.790563, 0, 0, 0.467683,-99) , 
NN2(
0, 
0, 
-1, 1.46583, 1, -1, 0.246113,-99) , 
8, 1.11089, 1, 0, 0.455738,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.526727,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.290098,-99) , 
1, 6.81169, 1, 0, 0.413624,-99) , 
NN2(
0, 
0, 
-1, 0.128827, 1, -1, 0.123024,-99) , 
2, 0.924939, 0, 0, 0.260604,-99) , 
0, 0.122309, 1, 0, 0.42653,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.182402);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.545997,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.447955,-99) , 
5, 1.73369, 1, 0, 0.521244,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524806,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.171947,-99) , 
5, -1.46435, 0, 0, 0.369761,-99) , 
8, -0.725379, 0, 0, 0.504847,-99) , 
NN2(
0, 
0, 
-1, 1.46583, 1, -1, 0.250306,-99) , 
8, 1.24945, 1, 0, 0.494645,-99) , 
NN2(
0, 
0, 
-1, 0.924939, 0, -1, 0.273746,-99) , 
0, 0.122309, 1, 0, 0.462593,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.208425);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.535234,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.368569,-99) , 
8, 0.834605, 1, 0, 0.514988,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.536111,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.250691,-99) , 
8, -0.273972, 0, 0, 0.431545,-99) , 
5, -1.4645, 0, 0, 0.485384,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.544421,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0419618, 1, 0, 0.279059,-99) , 
2, 0.568342, 0, 0, 0.473772,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.587816,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.352878,-99) , 
3, 6.23585, 0, 0, 0.48215,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0313536,-99) , 
9, 4.22222, 1, 0, 0.408756,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.799837, 0, 0, 0.288175,-99) , 
0, 0.133407, 1, 0, 0.453014,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.192498);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.536711,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.422302,-99) , 
5, 1.46722, 1, 0, 0.484041,-99) , 
NN2(
0, 
0, 
-1, -0.276664, 0, -1, 0.386335,-99) , 
6, -1.59866, 0, 0, 0.457982,-99) , 
NN2(
0, 
0, 
-1, 0.117865, 1, -1, 0.348304,-99) , 
9, 5.27778, 1, 0, 0.441611,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.228771,-99) , 
2, 0.574654, 0, 0, 0.428067,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.18554);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.534375,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.379561,-99) , 
6, 1.73339, 1, 0, 0.50012,-99) , 
NN2(
0, 
0, 
-1, 0.0483052, 1, -1, 0.42484,-99) , 
3, 7.95918, 1, 0, 0.472181,-99) , 
NN2(
0, 
0, 
-1, 2.5, 1, -1, 0.32318,-99) , 
5, -2.1308, 0, 0, 0.462024,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.613098,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.249431,-99) , 
5, 1.19828, 1, 0, 0.530979,-99) , 
NN2(
0, 
0, 
-1, 6.69563, 1, -1, 0.209249,-99) , 
9, 2.11111, 1, 0, 0.410695,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.799837, 0, 0, 0.299215,-99) , 
0, 0.133407, 1, 0, 0.444789,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.22649);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.632364,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.499465,-99) , 
8, -0.0702733, 1, 0, 0.56601,-99) , 
NN2(
0, 
0, 
-1, -0.408076, 0, -1, 0.436579,-99) , 
5, -0.931299, 0, 0, 0.50121,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.586598,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.247086,-99) , 
5, -1.61511, 0, 0, 0.471417,-99) , 
NN2(
0, 
0, 
-1, 1.24151, 1, -1, 0.267404,-99) , 
6, 1.19638, 1, 0, 0.381089,-99) , 
8, 0.378726, 1, 0, 0.464161,-99) , 
NN2(
0, 
0, 
-1, 0.784008, 0, -1, 0.27019,-99) , 
8, -0.970355, 0, 0, 0.448973,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.160319);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.693024,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.630108,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.494675,-99) , 
9, 0.555556, 1, 0, 0.524775,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.570773,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.275424,-99) , 
0, 0.0127573, 1, 0, 0.393937,-99) , 
0, 0.0166122, 0, 0, 0.49854,-99) , 
0, 0.0067006, 1, 0, 0.512232,-99) , 
NN2(
0, 
0, 
-1, 0.649715, 0, -1, 0.397841,-99) , 
0, 0.0779156, 1, 0, 0.47495,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.213529);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.612158,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.473271,-99) , 
1, 6.95499, 0, 0, 0.551665,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.660113,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.410605,-99) , 
0, 0.0113185, 1, 0, 0.454215,-99) , 
1, 11.3971, 1, 0, 0.522989,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.628851,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.376088,-99) , 
1, 6.81169, 1, 0, 0.522858,-99) , 
NN2(
0, 
0, 
-1, 1.05556, 1, -1, 0.114475,-99) , 
2, 0.905481, 0, 0, 0.387977,-99) , 
0, 0.133407, 1, 0, 0.510056,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.566753,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0457162, 1, 0, 0.306053,-99) , 
2, 0.574654, 0, 0, 0.498186,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.180678);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.58,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.477375,-99) , 
8, -0.274706, 0, 0, 0.548973,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.549059,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.342261,-99) , 
0, 0.012933, 1, 0, 0.457149,-99) , 
0, 0.0171797, 0, 0, 0.530936,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.588563,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.348928,-99) , 
9, 2.11111, 1, 0, 0.50876,-99) , 
NN2(
0, 
0, 
-1, 0.00722395, 1, -1, 0.22305,-99) , 
2, 0.905481, 0, 0, 0.40967,-99) , 
0, 0.122309, 1, 0, 0.516349,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.513768,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0457162, 1, 0, 0.289908,-99) , 
2, 0.574654, 0, 0, 0.503635,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.193845);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.542934,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.33763,-99) , 
1, 31.2454, 1, 0, 0.533356,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0693391,-99) , 
8, -2.01082, 0, 0, 0.529139,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.651813,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.286965,-99) , 
5, -1.59785, 0, 0, 0.52381,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.580205,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.22265,-99) , 
6, 1.10618, 1, 0, 0.321999,-99) , 
5, 1.20034, 1, 0, 0.427268,-99) , 
8, 0.416875, 1, 0, 0.503645,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.274968,-99) , 
2, 0.574654, 0, 0, 0.491127,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.14152);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.742562,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.496208,-99) , 
7, 0.0317107, 0, 0, 0.528148,-99) , 
NN2(
0, 
0, 
-1, 4.97707, 1, -1, 0.351167,-99) , 
1, 17.7935, 1, 0, 0.505091,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.505181,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.362212,-99) , 
5, 1.66707, 1, 0, 0.463575,-99) , 
NN2(
0, 
0, 
-1, 0.723692, 0, -1, 0.245029,-99) , 
5, -1.99754, 0, 0, 0.440615,-99) , 
2, 0.856114, 0, 0, 0.476336,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531887,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.23195,-99) , 
6, 1.71173, 1, 0, 0.486322,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.055483,-99) , 
9, 4.22222, 1, 0, 0.431169,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.799837, 0, 0, 0.337573,-99) , 
0, 0.133407, 1, 0, 0.463293,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.192816);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 15.6706, 1, 1, 0.671719,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.543583,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.404598,-99) , 
1, 9.96706, 1, 0, 0.504065,-99) , 
7, 0.0333525, 0, 0, 0.525214,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.286106,-99) , 
1, 30.5861, 1, 0, 0.513491,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.686168,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.470222,-99) , 
3, 5.56983, 1, 0, 0.514469,-99) , 
NN2(
0, 
0, 
-1, 0.572288, 0, -1, 0.402169,-99) , 
1, 8.84157, 0, 0, 0.46154,-99) , 
NN2(
0, 
0, 
-1, 6.81519, 1, -1, 0.22396,-99) , 
0, 0.0945276, 1, 0, 0.415685,-99) , 
2, 0.849878, 0, 0, 0.472386,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.139785);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.663278,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531486,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.430147,-99) , 
0, 0.016253, 0, 0, 0.498463,-99) , 
4, 6.92958, 0, 0, 0.520478,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50784,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.27295,-99) , 
5, 1.99977, 1, 0, 0.487116,-99) , 
NN2(
0, 
0, 
-1, 5.11093, 1, -1, 0.106255,-99) , 
2, 0.641469, 0, 0, 0.460388,-99) , 
0, 0.0483102, 1, 0, 0.493272,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.507946,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.285516,-99) , 
6, -1.47028, 0, 0, 0.435951,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.054603,-99) , 
9, 4.22222, 1, 0, 0.387246,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.799837, 0, 0, 0.313228,-99) , 
0, 0.133407, 1, 0, 0.476662,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.181632);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.615018,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.456198,-99) , 
9, 1.11111, 0, 0, 0.533082,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504524,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.307955,-99) , 
6, -1.59697, 0, 0, 0.461622,-99) , 
0, 0.0342923, 1, 0, 0.502993,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.318337,-99) , 
9, 8.33333, 1, 0, 0.493812,-99) , 
NN2(
NN2(
0, 
0, 
-1, 2.13291, 1, -1, 0.436356,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.662314,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 0.00713399, 1, 0, 0.435116,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 6.04402, 1, 0, 0.217541,-99) , 
2, 0.749796, 0, 0, 0.394523,-99) , 
0, 0.0723665, 1, 0, 0.458892,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.179973);
  fForest.push_back( 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.652249,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.655764,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.389551,-99) , 
7, 0.0406614, 1, 0, 0.578554,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.586267,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.342332,-99) , 
1, 11.3976, 0, 0, 0.458229,-99) , 
2, 0.928057, 0, 0, 0.500976,-99) , 
4, 6.92958, 0, 0, 0.522692,-99) , 
NN2(
0, 
0, 
-1, 0.574654, 0, -1, 0.436324,-99) , 
0, 0.0335222, 1, 0, 0.467646,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.134127);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.637222,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.499483,-99) , 
8, 0.101768, 0, 0, 0.529488,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.5291,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.36127,-99) , 
6, 1.19239, 1, 0, 0.456311,-99) , 
8, 0.338583, 1, 0, 0.509337,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.140573,-99) , 
8, 1.94283, 1, 0, 0.506285,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.617084,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.374738,-99) , 
6, -0.922769, 0, 0, 0.52314,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.576334,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.100776, 1, 0, 0.378272,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 6.04402, 1, 0, 0.180374,-99) , 
0, 0.0447325, 1, 0, 0.392721,-99) , 
2, 0.674735, 0, 0, 0.492151,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.169608);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.708527,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.548864,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.453795,-99) , 
2, 0.792208, 0, 0, 0.532868,-99) , 
0, 0.00577368, 1, 0, 0.539603,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.55829,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.240045,-99) , 
5, 1.99643, 1, 0, 0.522813,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510036,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.240187,-99) , 
7, 0.00555308, 1, 0, 0.343755,-99) , 
9, 2.11111, 1, 0, 0.452938,-99) , 
8, 0.416875, 1, 0, 0.519045,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.624738,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.415984,-99) , 
9, 4.44444, 0, 0, 0.515872,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.543295,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.100776, 1, 0, 0.363753,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 6.04402, 1, 0, 0.177006,-99) , 
0, 0.0447325, 1, 0, 0.389659,-99) , 
2, 0.674735, 0, 0, 0.503263,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.110482);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.522464,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.381321,-99) , 
5, -2.13056, 0, 0, 0.513473,-99) , 
NN2(
0, 
0, 
-1, 1.20021, 1, -1, 0.434541,-99) , 
8, 0.336017, 1, 0, 0.490656,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.488641,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.716902,-99) , 
NN2(
0, 
0, 
-1, 0.0133331, 0, -1, 0.180162,-99) , 
9, 4.44444, 0, 0, 0.495575,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.329935,-99) , 
2, 0.574654, 0, 0, 0.481267,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.073875);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.636507,-99) , 
NN2(
0, 
0, 
-1, 0.574654, 0, -1, 0.466792,-99) , 
0, 0.00577637, 1, 0, 0.472809,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0895642);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524808,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.471691,-99) , 
9, 2.11111, 1, 0, 0.503019,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.324516,-99) , 
6, 2.26656, 1, 0, 0.498764,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.496888,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.706069,-99) , 
NN2(
0, 
0, 
-1, 0.0133331, 0, -1, 0.197289,-99) , 
9, 4.44444, 0, 0, 0.501419,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.339876,-99) , 
2, 0.574654, 0, 0, 0.489933,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0549846);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508484,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.359042,-99) , 
3, 16.6043, 1, 0, 0.502886,-99) , 
NN2(
0, 
0, 
-1, 0.811398, 0, -1, 0.403973,-99) , 
0, 0.138957, 1, 0, 0.495362,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.493577,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.339418,-99) , 
2, 0.574654, 0, 0, 0.486922,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.10018);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.519144,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.463198,-99) , 
5, -0.93185, 0, 0, 0.490806,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.555453,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.19961,-99) , 
5, 1.89143, 0, 0, 0.380716,-99) , 
6, 2.13327, 1, 0, 0.484645,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.703007,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.224642,-99) , 
9, 4.44444, 0, 0, 0.5157,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.355724,-99) , 
2, 0.574654, 0, 0, 0.479159,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.477326,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.10949);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.51138,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.233908,-99) , 
6, -2.28755, 0, 0, 0.504809,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.560072,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.045965,-99) , 
5, -1.45928, 0, 0, 0.358801,-99) , 
8, -1.31705, 0, 0, 0.499577,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.497472,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.567226,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.284737,-99) , 
1, 12.5229, 1, 0, 0.506789,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510541,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.27159,-99) , 
7, 0.0175823, 0, 0, 0.352084,-99) , 
3, 6.82283, 0, 0, 0.434849,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0144463,-99) , 
8, 1.24945, 1, 0, 0.418156,-99) , 
6, 1.6001, 1, 0, 0.477751,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0986615);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.601169,-99) , 
NN2(
0, 
0, 
-1, 0.574654, 0, -1, 0.452711,-99) , 
0, 0.00577637, 1, 0, 0.457898,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0401161);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.500464,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.419163,-99) , 
0, 0.133407, 1, 0, 0.493226,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.279442,-99) , 
6, 2.26456, 1, 0, 0.489544,-99) , 
NN2(
0, 
0, 
-1, 0.0730472, 1, -1, 0.37864,-99) , 
5, 2.13344, 1, 0, 0.482341,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.480728,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.119465);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.610363,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.476731,-99) , 
5, -0.898642, 0, 0, 0.502724,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.630237,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.431271,-99) , 
6, 0.940585, 1, 0, 0.44893,-99) , 
5, 1.20052, 1, 0, 0.481156,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.479711,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.340629,-99) , 
2, 0.574654, 0, 0, 0.474001,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.058124);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.686034, 1, 1, 0.51104,-99) , 
NN2(
0, 
0, 
-1, -0.543094, 0, -1, 0.430744,-99) , 
2, 0.657439, 0, 0, 0.50331,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0996453,-99) , 
8, -1.97617, 0, 0, 0.501123,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.603972,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.525485,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.449925,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0166836,-99) , 
6, 1.59588, 1, 0, 0.358415,-99) , 
8, 1.24921, 1, 0, 0.495121,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0828795);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.51583,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.443179,-99) , 
0, 0.0168747, 0, 0, 0.503974,-99) , 
NN2(
0, 
0, 
-1, 5.2754, 0, -1, 0.453617,-99) , 
6, 1.6001, 1, 0, 0.491572,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.104983,-99) , 
8, -1.97617, 0, 0, 0.489524,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.667549,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.178622,-99) , 
5, 1.72202, 1, 0, 0.54709,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.132205,-99) , 
5, -1.06638, 0, 0, 0.442119,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0176644,-99) , 
6, 1.59588, 1, 0, 0.353626,-99) , 
8, 1.24921, 1, 0, 0.483887,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.066333);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.610677,-99) , 
NN2(
0, 
0, 
-1, 16.6029, 1, -1, 0.480866,-99) , 
0, 0.00577637, 1, 0, 0.48568,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.484209,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.585178,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.509031,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.438251,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0191616,-99) , 
6, 1.59588, 1, 0, 0.352262,-99) , 
8, 1.24921, 1, 0, 0.478851,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0579553);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.639531,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508229,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.457273,-99) , 
8, 0.365099, 1, 0, 0.497297,-99) , 
8, 1.06374, 0, 0, 0.50103,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.499559,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.568991,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.496738,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.429108,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0204489,-99) , 
6, 1.59588, 1, 0, 0.346569,-99) , 
8, 1.24921, 1, 0, 0.493437,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0551887);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.632027,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.496252,-99) , 
8, 1.02986, 0, 0, 0.501403,-99) , 
NN2(
0, 
0, 
-1, 0.675056, 0, -1, 0.429481,-99) , 
8, -0.721756, 0, 0, 0.493045,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.11778,-99) , 
8, -1.97617, 0, 0, 0.491184,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.600229,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1.77104, 1, 0, 0.494733,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0473616,-99) , 
5, -1.33238, 0, 0, 0.420944,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0216426,-99) , 
6, 1.59588, 1, 0, 0.341446,-99) , 
8, 1.24921, 1, 0, 0.485264,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0674637);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 6.92946, 0, 1, 0.513956,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.536649,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.294144,-99) , 
5, -1.46435, 0, 0, 0.446607,-99) , 
8, -0.693059, 0, 0, 0.505464,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.504061,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.548647,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.479041,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.414728,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0228426,-99) , 
6, 1.59588, 1, 0, 0.337622,-99) , 
8, 1.24921, 1, 0, 0.497568,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0374579);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, -1.97617, 0, -1, 0.48885,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.531892,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.466219,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.405083,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0243979,-99) , 
6, 1.59588, 1, 0, 0.331491,-99) , 
8, 1.24921, 1, 0, 0.482789,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0452451);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.566117,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.498752,-99) , 
4, 6.92946, 0, 0, 0.505273,-99) , 
NN2(
0, 
0, 
-1, 0.675056, 0, -1, 0.436621,-99) , 
8, -0.877985, 0, 0, 0.49953,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.498212,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.572228,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1.77104, 1, 0, 0.468143,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0480186,-99) , 
5, -1.33238, 0, 0, 0.399645,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0253055,-99) , 
6, 1.59588, 1, 0, 0.328012,-99) , 
8, 1.24921, 1, 0, 0.491704,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.061869);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517605,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.431997,-99) , 
5, 2.14089, 1, 0, 0.512097,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.400732,-99) , 
5, -2.26458, 0, 0, 0.508838,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.507525,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517397,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.453411,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.394516,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0264458,-99) , 
6, 1.59588, 1, 0, 0.3248,-99) , 
8, 1.24921, 1, 0, 0.50061,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0403182);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.585515,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.49484,-99) , 
8, 0.97997, 0, 0, 0.498376,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.229361,-99) , 
0, 0.188899, 1, 0, 0.496648,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.128626,-99) , 
8, -1.97617, 0, 0, 0.494964,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.552035,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1.77104, 1, 0, 0.450178,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0489411,-99) , 
5, -1.33238, 0, 0, 0.385463,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0280863,-99) , 
6, 1.59588, 1, 0, 0.318946,-99) , 
8, 1.24921, 1, 0, 0.488371,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0549602);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.52752,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.4941,-99) , 
8, 0.0672015, 1, 0, 0.511159,-99) , 
NN2(
0, 
0, 
-1, 0.675056, 0, -1, 0.443493,-99) , 
8, -0.877985, 0, 0, 0.505508,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.504267,-99) , 
NN2(
0, 
0, 
-1, 1.59588, 1, -1, 0.316032,-99) , 
8, 1.24921, 1, 0, 0.497279,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0946679);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.568219,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.383868,-99) , 
3, 11.4183, 1, 0, 0.541242,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501502,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.2853,-99) , 
8, 0.0774173, 1, 0, 0.48405,-99) , 
8, 0.139108, 0, 0, 0.5064,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.505189,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.510972,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 4.22222, 1, 0, 0.45001,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, -1.62119, 0, 0, 0.393905,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0308074,-99) , 
6, 1.59588, 1, 0, 0.32803,-99) , 
8, 1.24921, 1, 0, 0.498669,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.123196);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.551806,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.408381,-99) , 
3, 11.4202, 1, 0, 0.530583,-99) , 
NN2(
0, 
0, 
-1, 6.81195, 1, -1, 0.26651,-99) , 
0, 0.139342, 1, 0, 0.519045,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.514179,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.425074,-99) , 
9, 2.22222, 1, 0, 0.478383,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.336325,-99) , 
8, 0.032038, 1, 0, 0.464431,-99) , 
8, 0.104366, 0, 0, 0.486619,-99) , 
NN2(
0, 
0, 
-1, 0.899918, 0, -1, 0.318644,-99) , 
8, 1.24921, 1, 0, 0.480518,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0738406);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.592929,-99) , 
NN2(
0, 
0, 
-1, 0.559564, 0, -1, 0.474474,-99) , 
0, 0.00577637, 1, 0, 0.478674,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.128257,-99) , 
8, -1.97617, 0, 0, 0.477148,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.571666,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1.77104, 1, 0, 0.471301,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.057926,-99) , 
5, -1.33238, 0, 0, 0.409107,-99) , 
NN2(
0, 
0, 
-1, 1.80435, 0, -1, 0.0380214,-99) , 
6, 1.59588, 1, 0, 0.345967,-99) , 
8, 1.24921, 1, 0, 0.472454,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0223);
  fForest.push_back( 
NN2(
0, 
0, 
-1, 1.24921, 1, -1, 0.488852,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0316282);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50548,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.391015,-99) , 
6, 2.26656, 1, 0, 0.502978,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.253497,-99) , 
0, 0.188899, 1, 0, 0.501384,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.139395,-99) , 
8, -1.97617, 0, 0, 0.499859,-99) , 
NN2(
0, 
0, 
-1, 0.899918, 0, -1, 0.345193,-99) , 
8, 1.24921, 1, 0, 0.494425,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0800164);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.570491,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.46888,-99) , 
5, 1.20021, 1, 0, 0.521701,-99) , 
NN2(
0, 
0, 
-1, 0.0774173, 1, -1, 0.475552,-99) , 
8, 0.139108, 0, 0, 0.493524,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.492459,-99) , 
NN2(
0, 
0, 
-1, 0.899918, 0, -1, 0.352377,-99) , 
8, 1.24921, 1, 0, 0.487559,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0451268);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.0917707, 0, 1, 0.510767,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.524405,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.185486,-99) , 
5, 1.2001, 1, 0, 0.454294,-99) , 
0, 0.122309, 1, 0, 0.505438,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.0802, 0, 0, 0.504388,-99) , 
NN2(
0, 
0, 
-1, 0.899918, 0, -1, 0.370845,-99) , 
8, 1.24921, 1, 0, 0.499757,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0474777);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.630409,-99) , 
NN2(
0, 
0, 
-1, 0.676464, 0, -1, 0.491795,-99) , 
2, 0.598296, 1, 0, 0.494759,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.728862,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.239585,-99) , 
9, 4.44444, 0, 0, 0.547537,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.391253,-99) , 
2, 0.574654, 0, 0, 0.490681,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.489719,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0645703);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517801,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.479746,-99) , 
1, 11.3971, 1, 0, 0.507597,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.308153,-99) , 
0, 0.188899, 1, 0, 0.506121,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.50523,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.763193,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.264995,-99) , 
9, 4.22222, 0, 0, 0.571367,-99) , 
NN2(
0, 
0, 
-1, 8.38658, 0, -1, 0.0600176,-99) , 
1, 9.52373, 0, 0, 0.388555,-99) , 
2, 0.574654, 0, 0, 0.50068,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0429958);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.612205,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501959,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.402536,-99) , 
2, 0.676464, 0, 0, 0.496362,-99) , 
2, 0.598296, 1, 0, 0.498812,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.710508,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.260589,-99) , 
9, 4.44444, 0, 0, 0.54397,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.391925,-99) , 
2, 0.574654, 0, 0, 0.494737,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.493816,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.130648);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.674699,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.607426,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.454483,-99) , 
6, 1.4669, 0, 0, 0.511195,-99) , 
8, -0.187361, 1, 0, 0.555718,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.413763,-99) , 
3, 6.2323, 0, 0, 0.516297,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517233,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.266586,-99) , 
5, -2.13132, 0, 0, 0.504859,-99) , 
NN2(
0, 
0, 
-1, 0.104383, 1, -1, 0.418484,-99) , 
3, 7.54757, 1, 0, 0.476377,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.499593, 0, 0, 0.470178,-99) , 
0, 0.0279731, 1, 0, 0.484679,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.126147);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.675448,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.484916,-99) , 
1, 9.3354, 0, 0, 0.582036,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.629492,-99) , 
NN2(
0, 
0, 
-1, 0.0114683, 1, -1, 0.364966,-99) , 
0, 0.017852, 0, 0, 0.472104,-99) , 
9, 1.41667, 0, 0, 0.52366,-99) , 
NN2(
0, 
0, 
-1, 0.499593, 0, -1, 0.461512,-99) , 
0, 0.0279731, 1, 0, 0.480978,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.118043);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.537886,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.420331,-99) , 
6, -2.00989, 0, 0, 0.525975,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.529696,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.332308,-99) , 
4, 4.13576, 0, 0, 0.485094,-99) , 
4, 4.48839, 0, 0, 0.513142,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.38849,-99) , 
6, 2.26656, 1, 0, 0.510355,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.582315,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.378133,-99) , 
8, -0.562394, 0, 0, 0.521086,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.116197,-99) , 
9, 4.22222, 1, 0, 0.483006,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 0.799837, 0, 0, 0.42382,-99) , 
0, 0.133407, 1, 0, 0.503541,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0933713);
  fForest.push_back( 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.611649,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.56374,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.472167,-99) , 
3, 9.20494, 0, 0, 0.491051,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.331362,-99) , 
3, 16.6037, 1, 0, 0.48607,-99) , 
NN2(
0, 
0, 
-1, 0.0435795, 1, -1, 0.304255,-99) , 
2, 0.574654, 0, 0, 0.480343,-99) , 
0, 0.00577637, 1, 0, 0.484689,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0485679);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, -0.888739, 0, 1, 0.520189,-99) , 
NN2(
0, 
0, 
-1, 1.86115, 1, -1, 0.482988,-99) , 
5, 0.800704, 1, 0, 0.502672,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.501889,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.527458,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0457162, 1, 0, 0.384887,-99) , 
2, 0.574654, 0, 0, 0.497733,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0433063);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.611904,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.504462,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.415628,-99) , 
2, 0.676464, 0, 0, 0.499565,-99) , 
2, 0.598296, 1, 0, 0.501967,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.501203,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.687694,-99) , 
NN2(
0, 
0, 
-1, 0.0133331, 0, -1, 0.248833,-99) , 
9, 4.44444, 0, 0, 0.519238,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.378394,-99) , 
2, 0.574654, 0, 0, 0.496868,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.044369);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.601571,-99) , 
NN2(
0, 
0, 
-1, 3.16667, 1, -1, 0.489929,-99) , 
2, 0.598296, 1, 0, 0.492306,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.491573,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.678319,-99) , 
NN2(
0, 
0, 
-1, 0.0133331, 0, -1, 0.257016,-99) , 
9, 4.44444, 0, 0, 0.516879,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.377964,-99) , 
2, 0.574654, 0, 0, 0.48761,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0547515);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517581,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.470945,-99) , 
3, 5.51066, 0, 0, 0.505821,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.419636,-99) , 
3, 16.6037, 1, 0, 0.502926,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.502193,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.514669,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0457162, 1, 0, 0.377513,-99) , 
2, 0.574654, 0, 0, 0.497894,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0370887);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.635985,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.498099,-99) , 
8, -1.72692, 1, 0, 0.500256,-99) , 
NN2(
0, 
0, 
-1, 1.72692, 1, -1, 0.429661,-99) , 
8, 1.09897, 1, 0, 0.496827,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.496122,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.731319,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.321565,-99) , 
9, 4.44444, 0, 0, 0.584291,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.417361, 1, 0, 0.50525,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.370098,-99) , 
2, 0.574654, 0, 0, 0.491804,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0452188);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0.598296, 1, 1, 0.509238,-99) , 
NN2(
0, 
0, 
-1, 1.72692, 1, -1, 0.438772,-99) , 
8, 1.09897, 1, 0, 0.505824,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.505119,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.723969,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.329709,-99) , 
9, 4.44444, 0, 0, 0.582321,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.417361, 1, 0, 0.504281,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.37031,-99) , 
2, 0.574654, 0, 0, 0.500552,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0901556);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.519467,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.412737,-99) , 
4, 4.1627, 0, 0, 0.504416,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.516727,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.323197,-99) , 
9, 3.5, 1, 0, 0.47139,-99) , 
4, 5.46474, 1, 0, 0.495614,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.494939,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.641596,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -0.717095, 0, 0, 0.579879,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.417361, 1, 0, 0.503075,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.370576,-99) , 
2, 0.574654, 0, 0, 0.49078,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0868009);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.69271,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.438972,-99) , 
2, 0.673083, 0, 0, 0.523891,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.559016,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.469832,-99) , 
6, -2.1318, 1, 0, 0.475512,-99) , 
2, 0.692814, 1, 0, 0.480499,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.479872,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.363477,-99) , 
2, 0.574654, 0, 0, 0.476068,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0413554);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.600229,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.508586,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.476753,-99) , 
2, 0.866123, 0, 0, 0.495961,-99) , 
2, 0.598296, 1, 0, 0.498206,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.497581,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.512151,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.0457162, 1, 0, 0.383787,-99) , 
2, 0.574654, 0, 0, 0.493892,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0759427);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.646084,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.491083,-99) , 
5, 0.790477, 1, 0, 0.509836,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.50786,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.393158,-99) , 
8, -0.426775, 0, 0, 0.479789,-99) , 
6, -0.932423, 0, 0, 0.495889,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, -2.08014, 0, 0, 0.49528,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.713442,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.335413,-99) , 
9, 4.44444, 0, 0, 0.576455,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 0.417361, 1, 0, 0.504674,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.377953,-99) , 
2, 0.574654, 0, 0, 0.491494,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.173916);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.718573,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.429372,-99) , 
4, 4.49857, 0, 0, 0.621702,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0.0881241, 0, 1, 0.524777,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.599109,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.142554,-99) , 
5, 1.2966, 1, 0, 0.367122,-99) , 
0, 0.105712, 1, 0, 0.505996,-99) , 
6, 0.826382, 1, 0, 0.521653,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.601835,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.458355,-99) , 
7, 0.0106564, 0, 0, 0.524604,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.563903,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.379466,-99) , 
4, 5.46474, 0, 0, 0.434418,-99) , 
9, 1.11111, 0, 0, 0.487756,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.62744,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.247483,-99) , 
0, 0.135759, 1, 0, 0.569889,-99) , 
NN2(
0, 
0, 
-1, 0.931969, 0, -1, 0.28373,-99) , 
5, -1.42904, 0, 0, 0.389673,-99) , 
8, -0.415463, 0, 0, 0.463228,-99) , 
6, -0.932423, 0, 0, 0.494704,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.143676);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.607231,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.357826,-99) , 
5, -1.59548, 0, 0, 0.544807,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517914,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.430439,-99) , 
5, 0.800704, 1, 0, 0.477868,-99) , 
4, 4.93549, 0, 0, 0.495396,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.575262,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.450201,-99) , 
4, 7.2556, 0, 0, 0.489354,-99) , 
NN2(
0, 
0, 
-1, 0.858222, 0, -1, 0.315921,-99) , 
0, 0.0778168, 1, 0, 0.454583,-99) , 
4, 5.46474, 1, 0, 0.484509,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.552374,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 0.062202, 1, 0, 0.482838,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 8.39415, 0, 0, 0.36171,-99) , 
2, 0.574654, 0, 0, 0.480629,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0879015);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.625623,-99) , 
NN2(
0, 
0, 
-1, 1.11087, 1, -1, 0.484325,-99) , 
6, 0.892709, 1, 0, 0.500672,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.517538,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0579343,-99) , 
0, 0.155742, 1, 0, 0.500051,-99) , 
NN2(
0, 
0, 
-1, 0.0168747, 0, -1, 0.420838,-99) , 
9, 1.05556, 0, 0, 0.46626,-99) , 
5, -0.93185, 0, 0, 0.484056,-99) , 
NN2(
0, 
0, 
-1, 0.0457162, 1, -1, 0.346038,-99) , 
2, 0.574654, 0, 0, 0.479782,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.14046);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.58062,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.477745,-99) , 
7, 0.0134046, 0, 0, 0.526168,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.358401,-99) , 
6, 2.21473, 1, 0, 0.517077,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0800851,-99) , 
9, 12.2222, 1, 0, 0.513509,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.604551,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.477645,-99) , 
5, -2.05695, 1, 0, 0.507505,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.560491,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.371194,-99) , 
2, 0.839591, 1, 0, 0.415077,-99) , 
8, -0.27674, 0, 0, 0.473923,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.539893,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.187489,-99) , 
0, 0.0565492, 1, 0, 0.422447,-99) , 
NN2(
0, 
0, 
-1, -2.13816, 1, -1, 0.0432769,-99) , 
5, -1.95254, 0, 0, 0.346777,-99) , 
2, 0.724776, 0, 0, 0.457731,-99) , 
6, -0.932423, 0, 0, 0.487813,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.107611);
  fForest.push_back( 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, -1.48733, 1, 1, 0.609589,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.514563,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.236254,-99) , 
8, 1.38697, 1, 0, 0.507711,-99) , 
6, 0.826382, 1, 0, 0.521082,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.0910623,-99) , 
9, 12.2222, 1, 0, 0.51775,-99) , 
NN2(
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.542456,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.380369,-99) , 
1, 24.1908, 1, 0, 0.526218,-99) , 
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.527356,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.387366,-99) , 
5, -1.42572, 0, 0, 0.432816,-99) , 
8, -0.27674, 0, 0, 0.4925,-99) , 
NN2(
NN2(
NN2(
0, 
0, 
-1, 0, 1, 1, 0.501323,-99) , 
NN2(
0, 
0, 
-1, 0, 1, -1, 0.141488,-99) , 
3, 9.6898, 1, 0, 0.40909,-99) , 
NN2(
0, 
0, 
-1, -2.13816, 1, -1, 0.0494803,-99) , 
5, -1.95254, 0, 0, 0.340024,-99) , 
2, 0.724776, 0, 0, 0.473391,-99) , 
6, -0.932423, 0, 0, 0.497356,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
