dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_100_1_N6b.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_101_1_2F5.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_10_1_2g8.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_11_1_lLU.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_12_1_iMI.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_13_1_7p6.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_14_1_eyo.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_15_1_lBS.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_16_1_z2j.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_17_1_tDW.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_18_1_HAE.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_19_1_NmM.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_1_1_wMV.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_20_1_ts5.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_21_1_18v.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_22_1_dkN.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_24_1_xfO.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_25_1_BQF.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_26_1_Jbz.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_27_1_WkM.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_28_1_oup.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_29_1_kpp.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2_1_bSi.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_30_1_cqh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_31_1_dmH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_32_1_ssq.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_33_1_Q0c.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_34_1_yXg.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_35_1_Bg5.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_36_1_7bJ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_37_1_laj.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_38_1_w6p.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_39_1_Yvr.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_3_1_BRO.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_40_1_xEt.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_41_1_cPX.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_42_1_OyH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_43_1_zvB.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_44_1_ejp.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_45_1_od7.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_46_1_6LH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_47_1_QIr.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_48_1_Vqg.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_49_1_tS2.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_4_1_bNQ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_50_1_DAJ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_51_1_Ah1.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_52_1_iRo.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_53_1_tD2.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_54_1_u4J.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_55_1_M5I.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_56_1_xmy.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_57_1_wI7.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_58_1_PEl.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_59_1_9GC.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_5_1_nnF.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_60_1_J2N.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_61_1_Qbw.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_62_1_u46.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_63_1_QTF.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_64_1_i2y.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_65_1_mS8.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_66_1_5mI.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_67_1_nF9.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_68_1_v3A.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_69_1_6lj.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_6_1_4nj.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_70_1_szQ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_71_1_8ws.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_72_1_eiA.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_73_1_DUm.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_74_1_IhU.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_75_1_5BV.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_76_1_KKs.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_77_1_tYh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_78_1_CUI.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_79_1_gNP.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_7_1_nLC.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_80_1_931.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_81_1_8YP.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_82_1_oy4.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_83_1_Ebv.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_84_1_JXL.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_85_1_GGM.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_86_1_Qny.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_87_1_sx6.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_88_1_VIH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_89_1_vpY.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_8_1_Rg9.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_90_1_DHf.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_91_1_rbh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_92_1_HEu.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_93_1_DoW.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_94_1_TOl.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_95_1_F2V.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_96_1_0bt.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_97_1_iNh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_98_1_vFe.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_99_1_r4T.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_9_1_aY1.root
