dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_100_1_vAJ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_101_1_wWd.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_10_1_hAu.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_11_1_YxJ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_12_1_uox.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_13_1_t3t.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_14_1_RRb.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_15_1_bk7.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_16_1_4iw.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_17_1_Vnb.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_18_1_RC8.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_19_1_NOH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_1_1_dRE.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_20_1_xZD.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_21_1_E4k.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_22_1_Roh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_23_1_zd2.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_24_1_sjf.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_25_1_ACG.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_26_1_6lW.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_27_1_HbA.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_28_1_gQi.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_29_1_RtY.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_2_1_PhD.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_30_1_OnJ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_31_1_qPv.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_32_1_JjO.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_33_1_x0y.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_34_1_E9I.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_35_1_TiF.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_36_1_Y1V.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_37_1_usa.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_38_1_inu.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_39_1_n1c.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_3_1_XKe.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_40_1_lu9.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_41_1_38b.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_42_1_7Uw.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_43_1_T5f.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_44_1_VXx.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_45_1_FK9.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_46_1_MOw.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_47_1_1lq.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_48_1_Rl0.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_49_1_thp.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_4_1_jqv.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_50_1_6gV.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_51_1_O6y.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_52_1_TW6.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_53_1_HVp.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_54_1_JQH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_55_1_kn4.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_56_1_nLC.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_57_1_HGQ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_58_1_TiZ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_59_1_YnL.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_5_1_V5Z.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_60_1_nNv.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_61_1_y2U.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_62_1_xGf.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_63_1_vH6.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_64_1_6Ad.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_65_1_Ncs.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_66_1_ih3.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_67_1_Glu.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_68_1_qkn.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_69_1_mic.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_6_1_LBI.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_70_1_y6K.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_71_1_zXQ.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_72_1_qiH.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_73_1_Yuh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_74_1_N9p.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_75_1_6Py.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_76_1_WYb.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_77_1_u1l.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_78_1_4Us.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_79_1_T5O.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_7_1_odp.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_80_1_iZs.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_81_1_UjX.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_82_1_p7Y.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_83_1_PeA.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_84_1_hJN.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_85_1_ntG.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_86_1_lgg.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_87_1_j7f.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_88_1_4Mh.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_89_1_0HW.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_8_1_eWN.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_90_1_Dk2.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_91_1_wVf.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_92_1_wxi.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_93_1_1o4.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_94_1_VPv.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_95_1_eaV.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_96_1_x2u.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_97_1_M5d.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_98_1_HbB.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_99_1_DJf.root
dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat/store/user/naegelic/production/BsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/BsToJPsiMuMu_2MuPEtaFilter_9_1_TZF.root
