#! /usr/bin/perl
#
# usage: ./runAll -s or b  for Bs2MuMu signal and/or bg
#        ./runAll -n or m  for Bp2JpsiKp signal and/or bg
#        ./runAll -r or q  for rare BG and/or QCD bg
#        ./runAll -[..] -p    dry-run
#



#===========================================================

$workspace       = "/home/ceggel/new/macros";
$perl            = "/home/ceggel/perl";  

#$workspace       = "/home/chi/bsmumu/Bs2MuMu";
#$perl            = "/home/chi/perl";  

#===========================================================

use Getopt::Std;
getopts('sbnmrqpc:');

if ( !$opt_s &&!$opt_b &&!$opt_n &&!$opt_m &&!$opt_r &&!$opt_q ) {
    

    $opt_s = 1;  $opt_b = 1;
    $opt_n = 1;  $opt_m = 1;
    $opt_r = 1;  # $opt_q = 1;
}

print "\n ... START BMM ANALYSIS ... \n\n";

# ---------------
# Signal & BG
# ---------------

if ( $opt_s || $opt_b ) {

    $cut_file = "bmm.default.cuts";
    if ( $opt_c ) { $cut_file = $opt_c; }
    
    $cuts = $cut_file;
    $cuts =~ s/bmm//g;
    $cuts =~ s/cuts//g;
    $cuts =~ s/\///g;
    $cuts =~ s/\.//g;

    $#chain = -1;

    chdir("$workspace/chains");

    if ( $opt_s ) { #push(@chain, `ls -1 csg-003`); push(@chain, `ls -1 csg-003p`); }
		    #push(@chain, `ls -1 csg-00{3,4}`);
		    push(@chain, `ls -1 csg-003`); }

    if ( $opt_b ) { push(@chain, `ls -1 cbg-009`); push(@chain, `ls -1 cbg-00{3,4,5,6,7,8}`); }
		    #push(@chain, `ls -1 cbg-003`); }
	            #push(@chain, `ls -1 cbg-003`); }


    chdir("$workspace");

    foreach $file (@chain) {
	
	chop($file);
	
	if ( -e "treebmm/$file.log" ) { if (!$opt_p) { system("rm -f treebmm/$file.log"); }  }

	if ( $file eq "csg-001" || $file eq "csg-002" || $file eq "cbg-001" ) { 

	    print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -o \>\& treebmm/$file\.$cuts\.log\n";
	    if (!$opt_p) { 
		system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -o \>\& treebmm/$file\.$cuts\.log"); 
	    }

	} elsif ( $file eq "csg-004" || $file eq "cbg-004" || $file eq "cbg-008") {
 
	    print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -t -v 1 \>\& treebmm/$file\.$cuts\.log\n";
	    if (!$opt_p) { 
		system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -t -v 1 \>\& treebmm/$file\.$cuts\.log"); 
	    }


	} else {

	    print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -v 1 \>\& treebmm/$file\.$cuts\.log\n";
	    if (!$opt_p) { 
		system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -v 1 \>\& treebmm/$file\.$cuts\.log"); 
	    }
	}
    }
}
  
# -------------------
# Normalization & BG 
# -------------------
   
if ( $opt_n || $opt_m )     {  

    $cut_file = "bjk.norm.cuts";
    
    $cuts = $cut_file;
    $cuts =~ s/bjk//g;
    $cuts =~ s/cuts//g;
    $cuts =~ s/\///g;
    $cuts =~ s/\.//g;

    $#chain = -1;

    chdir("$workspace/chains");

    if ( $opt_n )     {  push(@chain, `ls -1 csg-004`); }
			 #push(@chain, `ls -1 csg-004j`); push(@chain, `ls -1 csg-004f`); }   
    if ( $opt_m )     {  push(@chain, `ls -1 cbg-009`); push(@chain, `ls -1 cbg-00{3,4,5,6,7,8}`); } 
			 #push(@chain, `ls -1 cbg-004f`);}

    chdir("$workspace");

    foreach $file (@chain) {
	
	chop($file);

	if ( -e "treebmm/$file.$cuts.log" ) { if (!$opt_p) { system("rm -f treebmm/$file.$cuts.log"); } }

	if ( $file eq "csg-004" || $file eq "cbg-004" || $file eq "cbg-008") { 

	    print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b bjk -t -v 1 \>\& treebmm/$file\.$cuts\.log\n";
	    if (!$opt_p) { 
		system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b bjk -t -v 1 \>\& treebmm/$file\.$cuts\.log"); 
	    }

	} else {
	    
	    print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b bjk -v 1 \>\& treebmm/$file\.$cuts\.log\n";
	    if (!$opt_p) { 
		system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b bjk -v 1 \>\& treebmm/$file\.$cuts\.log"); 
	    }
	    # add option -v 2 to run verbose
	}
    }
}


# ---------------
# Rare BG's
# ---------------

if ( $opt_r )  {  
    

    $cut_file = "bmm.default.cuts";
    
    $cuts = $cut_file;
    $cuts =~ s/bmm//g;
    $cuts =~ s/cuts//g;
    $cuts =~ s/\///g;
    $cuts =~ s/\.//g;

    $#chain = -1;

    chdir("$workspace/chains"); 
    
    @chain = `ls -1 cbg-222-*`;   

    chdir("$workspace");

    foreach $file ( @chain ) { 
	
	chop($file);
	
	@tmp = split(/\-/, $file);
	$chName =  @tmp[$#tmp];
	
	if ( -e "treebmm/$file.$cuts.log" ) { if (!$opt_p) { system("rm -f treebmm/$file.$cuts.log"); }  }
	
	print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b $chName -v 1 \>\& treebmm/$chName\.$cuts\.log\n";
	if (!$opt_p) { 
	    system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b $chName -v 1 \>\& treebmm/$chName\.$cuts\.log"); 
	}
    }
}


# ---------------
# QCD background
# ---------------

if ( $opt_q )  { 

    $cut_file = "bmm.default.cuts";
    
    $cuts = $cut_file;
    $cuts =~ s/bmm//g;
    $cuts =~ s/cuts//g;
    $cuts =~ s/\///g;
    $cuts =~ s/\.//g;

    $#chain = -1;

    chdir("$workspace/chains");

    $file = "cbg-030";

    if ( -e "$file") {

	chdir("$workspace");

	if ( -e "treebmm/$file\.$cuts\.log" ) { if (!$opt_p) { system("rm -f  treebmm/$file\.$cuts\.log"); } }

	print  "./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b qcd \>\& treebmm/$file\.$cuts\.log\n";
	if (!$opt_p) { 
	    system("./bmm -C cuts/$cut_file -D treebmm -c chains/$file -b qcd \>\& treebmm/$file\.$cuts\.log"); 
	}

	if (!$opt_p) { 
	    system("mv treebmm/$file.$cuts.root treebmm/qcd.$cuts.root"); 
	}

    }
}

print  " \n\n ... DONE ... \n\n";
