#! /usr/bin/perl
#
# OPTIONS :  -o s,b,r  mkCheckedChain option for signal, bg or rare bg  
#
#===========================================================
$pwd  = $ENV{'PWD'};
$home = $ENV{'HOME'};

$workspace       = "$pwd";
$perl            = "$home/perl";  

#$workspace       = "/home/chi/bsmumu/Bs2MuMu";
#$perl            = "/home/chi/perl";  

#===========================================================

use Getopt::Std;
getopts('o:rbs');

if ( $opt_s ) {

    $opt_o = "s";
}

if ( $opt_b ) {

    $opt_o = "b";
}

if ( $opt_r ) {

    $opt_o = "r";
}


chdir("$workspace");

if ( !(-e "chains") ) {

    mkdir("chains");

} else {

    @chain2del= `ls -1 chains/*~`;
}

foreach $del (@chain2del) { 
    chop($del);
    print  "\nRemoving $del ... \n";
    system("rm -f $del");
}

print "\n\n Starting \"mkChains\" ...\n";
system("$perl/mkChains");
print "\n\n Starting \"mkCheckedChains\" ...\n";

if ( $opt_o ) {
    system("$perl/mkCheckedChains -$opt_o");
} else {
    system("$perl/mkCheckedChains");
}
