#!/usr/bin/env perl

# ----------------------------------------------------------------------
# usage:  cscs2psi [-d] [-p /store/user/bstomumu/v14] [-x bmmMCBg]
#
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('dp:x:');

my $prefix = "/store/user/bstomumu/v14";
if ($opt_p) {
    $prefix = $opt_p;
}

my $se2se = "/shome/ursl/perl/se2se";

my %syncDirectories = (
    # -- hadronic non-muon PD
    "/cmsRun/2011/data-hadronic-nonMuon/A" => "ht",
    "/cmsRun/2011/data-hadronic-nonMuon/B" => "ht",
    "/cmsRun/2012/data-hadronic-nonMuon/A" => "ht",
    "/cmsRun/2012/data-hadronic-nonMuon/B" => "ht",
    "/cmsRun/2012/data-hadronic-nonMuon/C" => "ht",
    "/cmsRun/2012/data-hadronic-nonMuon/D" => "ht",

    # -- hadronic non-muon PD
    "/cmsRun/2012/data-hadronic-singleElectron/A" => "singleElectron",
    "/cmsRun/2012/data-hadronic-singleElectron/B" => "singleElectron",
    "/cmsRun/2012/data-hadronic-singleElectron/C" => "singleElectron",
    "/cmsRun/2012/data-hadronic-singleElectron/D" => "singleElectron",

    # -- hadronic non-muon PD
    "/cmsRun/2012/data-hadronic-minimumBias/A" => "minimumBias",
    "/cmsRun/2012/data-hadronic-minimumBias/B" => "minimumBias",
    "/cmsRun/2012/data-hadronic-minimumBias/C" => "minimumBias",
    "/cmsRun/2012/data-hadronic-minimumBias/D" => "minimumBias",

    # -- hadronic non-muon PD
    "/cmsRun/2012/data-hadronic-multiJet/A" => "multiJet",
    "/cmsRun/2012/data-hadronic-multiJet/B" => "multiJet",
    "/cmsRun/2012/data-hadronic-multiJet/C" => "multiJet",
    "/cmsRun/2012/data-hadronic-multiJet/D" => "multiJet",
    
    # -- onia MC
    "/cmsRun/2012/mc-cms/Upsilon1SToMuMu_2MuPtEtaFilter_tuneD6T_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1" => "oniaMC",
    "/cmsRun/2012/mc-cms/Upsilon2SToMuMu_2MuPtEtaFilter_tuneD6T_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1" => "oniaMC",
    "/cmsRun/2012/mc-cms/Upsilon3SToMuMu_2MuPtEtaFilter_tuneD6T_8TeV-pythia6__Summer12_DR53X-PU_S10_START53_V7A-v1" => "oniaMC",
    "/cmsRun/2012/mc-cms/JPsiToMuMu_2MuPtEtaFilter_tuneD6T_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2" => "oniaMC",
    "/cmsRun/2012/mc-cms/Psi2SToMuMu_2MuPtEtaFilter_tuneD6T_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1" => "oniaMC",

    # -- bmm MC
    "/cmsRun/2012/mc-cms/BsToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToKPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg", 
    "/cmsRun/2012/mc-cms/BdToJpsiKstar_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmBgMCBg",
    "/cmsRun/2012/mc-cms/BdToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToMuMuK0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToMuMuPi0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToRohPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BsToJPsiPhi_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCCs",
    "/cmsRun/2012/mc-cms/BsToJPsiPhi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCCs",
    "/cmsRun/2012/mc-cms/BsToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BsToKMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BsToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCSg",
    "/cmsRun/2012/mc-cms/BsToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCNo",
    "/cmsRun/2012/mc-cms/BuToJpsiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BuToMuMuK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BuToMuMuK_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMcBg", 
    "/cmsRun/2012/mc-cms/BuToMuMuPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/LambdaBToPK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/LambdaBToPMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToPiMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BuToJPsiK_K2MuPtEtaEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCNo",
    "/cmsRun/2012/mc-cms/BdToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCSg",
    "/cmsRun/2012/mc-cms/BsToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCSg",
    "/cmsRun/2012/mc-cms/LambdaBToPPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    "/cmsRun/2012/mc-cms/BdToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1" => "bmmMCBg",
    );


foreach $dir (keys %syncDirectories) {
    $sdir = "$prefix/$dir";
    if ($opt_x) {
	if ($syncDirectories{$dir} =~ /$opt_x/) {
	    print "sync $sdir\n";
	    if (!$opt_d) {
		system("$se2se -s T2_CH_CSCS -t T3_CH_PSI -d $sdir")
	    }
	}
    } else {
	print "sync $sdir\n";
	if (!$opt_d) {
	    system("$se2se -s T2_CH_CSCS -t T3_CH_PSI -d $sdir")
	}
    }
}
