#! /usr/bin/env perl

# Usage:  mkFileList -p RECO -x /store/user/ursl/production/Winter10/BsToKK
# ------
#
#
# 2010/03/10   First version
#              
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('x:p:');

$prefix  = "srm://storage01.lcg.cscs.ch:8443/srm/managerv2\?SFN=/pnfs/lcg.cscs.ch/cms/trivcat";

@files = `srmls $prefix/$opt_x`; 

foreach $file (@files) {
    chop($file); 
    if ($file =~ /$opt_p/ && $file =~ /\.root$/) {
	($size, $fname) = split(/\/store\//, $file);
	$fname = "/store/$fname";
	push(@fileList, $fname); 
    }
}

@sorted = sort(@fileList);

foreach $file (@sorted) {
    print "$file\n";
}
