#!/usr/bin/env perl

#
# mkPyFiles -t file-XXXX.py [-x 12] [[-l] -n 5| -e 5000] -f filenames.txt -d outputDirectory -s suffix
#
# This is useful for creating a set of python files, inserting opt_n lines (or opt_e events) from opt_f, and incrementing XXXX 
#
#
# History   
# -------   
#           11/11/10  Bug fix to produce py files with last batch of files even if not > $opt_e (!)
#           11/05/24  Will this odyssee ever end? bug fix when searching for /store in @files instead of @afiles
#           11/05/17  Added -l to split a file with input lines only (and no event numbers)
#           11/05/09  Bug fix to properly fill withEvents also whent the dbs header was removed (e.g., by a diff)
#           11/05/04  Bug fix to avoid including previous last file in new run
#           10/07/26  Migration to skipEvents
#           10/03/29  Bug fix: works now also for (data_replica.py compliant) file lists
#           09/12/23  Add runnumber also to output rootfilename, incremental file counting different for -r and default
#           09/12/21  Added -r option to split at run boundaries
#           09/12/08  Added printout of how many events were combined
#           09/12/04  Added opt_s to start from same skeleton into different branches (datasets)
#           09/10/26  Bug fix affecting small initial files
#	    09/09/02  Added event numbers for splitting
#           09/08/31  First shot		       
#           TODO:     split files with > opt_e events into two py files with offset
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <ursl@phys.ethz.ch>
# ----------------------------------------------------------------------

$hostname = `hostname`; chop($hostname); 
$directory = `pwd`;     chop($directory); 

@args = @ARGV; 
use Getopt::Std;
getopts('c:e:d:f:ln:rs:t:vx:');

# -- this is just for convenience in here
if ($opt_c) {
    $cntEvents = 0;
    open(IN, "$opt_c") || die "cannot open $opt_c\n";
    while(<IN>){
	($bla, $cnt) = split(/\.root */);
	$cntEvents += $cnt; 
    }
    close IN; 
    die "Counted a total of $cntEvents events\n";
} 


if (!$opt_d) {
    $opt_d = "."; 
}

if (!$opt_s) {
    $opt_s = ""; 
}

if ($opt_t) {
    open(IN, "$opt_t") || die "cannot open $opt_t\n";
    @in = <IN>;
    close IN; 
    grep(s/\n//, @in); 
} else {
    die "need a template py file!\n";
}

if (!$opt_n && !$opt_e) {
    $opt_n = 1; 
}

if ($opt_f) {
    open(IN, "$opt_f") || die "cannot open $opt_f\n";
    @afiles = <IN>;
    close IN; 
    @files = grep(/\/store\//, @afiles);
} else {
    die "need dbs txt file with all the filenames\n";
}

# -- Remove stuff from dbs txt file
$withEvents = 0; 
if ($files[0] =~ /^\/store/) {
    $withEvents = 2; 
} else {
    $withEvents = 1; 
}

grep(s/\n//, @files); 

my @blockEvents;
my @blockSkipEvents;
my @block;

# -- determine total number of events
$totEvents = 0; 
$bevt = 0; 
$ib = -1; 
$oldRun = -1; 
$startNewBlock = 1; 
$blockFiles = 0; 

# -- this hash (indexed by runnumber) contains records with $RUNNUMBER, $NEVENTS, @FILELIST
#    and is filled in createRunList

if ($opt_r) {
    my %runList;
    &createRunList();
    print "runList contains something\n";
    &createPyFilesPerRun();
    die "\n";
} elsif ($opt_l) {
    my @fileList;
    $withEvents = 0; 
    &createFileList();
    &createPyFilesWithoutEvents();
} else {
    my @fileList;
    &createFileList();
    &createPyFilesPerBlock();
    die "\n";
}


# ----------------------------------------------------------------------
sub createRunList() {

    $runEventNumber = 0; 
    $oldrun = 0; 
    $num = 0; 

    for ($i = 0; $i <= $#files; $i++) {
	print "$files[$i]\n";

	# -- skip lines that do not contain filenames
	if (!($files[$i] =~ /.*\.root/)) {next;}
	# -- change format for parsing
	$files[$i] =~ s/\t/:/g;
	$files[$i] =~ s/\s{1,99}/:/g;

	if ($withEvents == 1) {
	    ($num, $filename) = split(/:/, $files[$i]); 
	} elsif ($withEvents == 2) {
	    ($filename, $num) = split(/:/, $files[$i]); 
	}
	if ($num == 0) {next;}

        # -- get runnumber
	if ($opt_r) {
	    @bblocks =  split(/\//, $filename); 
	    $run = $bblocks[$#bblocks-2]*1000 + $bblocks[$#bblocks-1];
	} else {
	    $run = 1; 
	}

	print "$run $num\n";

	push(@fList, $filename); 
	$runEventNumber += $num; 
	if ($run != $oldrun) {
	    if ($oldrun == 0) {
		$oldrun = $run;
		next; 
	    }

	    pop(@fList);
	    $runEventNumber -= $num; 

	    createRunRecord($oldrun, $runEventNumber, @fList); 

	    # -- set up new run 
	    $oldrun = $run;
	    @fList = (); 
	    push(@fList, $filename); 
	    $runEventNumber = $num; 

	}
    }
    
    # -- push out final line/run as well
    if ($oldrun != 0) {
	createRunRecord($oldrun, $runEventNumber, @fList); 
    }
}


# ----------------------------------------------------------------------
sub createRunRecord() {
    local($run, $nevts, @files) = @_;

    print "finish old run: $oldrun with $runEventNumber events\n";
    for ($j = 0; $j <= $#files; $j++) {
	print "$files[$j] \n";
    }
    
    $runInfo = {
	RUNNUMBER => $run,
	NEVENTS  => $nevts,
	FILELIST => [@files],
    };
    
    $runList{$run} =  $runInfo; 
}



# ----------------------------------------------------------------------
sub createFileList() {
    for ($i = 0; $i <= $#files; $i++) {
	# -- skip lines that do not contain filenames
	if (!($files[$i] =~ /.*\.root/)) {next;}
	# -- change format for parsing
	$files[$i] =~ s/\t/:/g;
	$files[$i] =~ s/\s{1,99}/:/g;

	if ($withEvents == 1) {
	    ($num, $filename) = split(/:/, $files[$i]); 
	    if ($num > 0) {createFileRecord($num, $filename); }
	} elsif ($withEvents == 2) {
	    ($filename, $num) = split(/:/, $files[$i]); 
	    if ($num > 0) {createFileRecord($num, $filename); }
	} else {
	    print "-> $files[$i]\n";
	    createFileRecord(-1, $files[$i]); 
	}
    }
    

}

# ----------------------------------------------------------------------
sub createFileRecord() {
    
    local($nevts, $filename) = @_; 

    print "insert $runEventNumber events for file $filename\n";
    
    $fileInfo = {
	NEVENTS  => $nevts,
	FILELIST => $filename,
    };
    
    push(@fileList, $fileInfo); 
}


# ----------------------------------------------------------------------
sub createPyFilesPerRun() {
    
    foreach $run (sort keys %runList) {
	if ($opt_e) {
	    $njobs = $runList{$run}->{NEVENTS}/$opt_e;
	} else {
	    $njobs = 1; 
	}
	for ($iJob = 0; $iJob < $njobs; $iJob++) {

	    if ($opt_s) {
		$blockName = sprintf("-%s", $opt_s);
	    }

	    if ($opt_r) {
		$blockName .= sprintf("-%07i", $run);
	    }
	    

	    $blockName .= sprintf("-%04i", $iJob);
	    $skipevents = $iJob*$opt_e; 
	    ($fileName = $opt_t) =~ s/XXXX/$blockName/g;
	    $fileName  =~ s/--/-/g; # -- remove spurious double hyphens ...
	    $tmp = $fileName; @tmp = split(/\//, $fileName); $fileName = pop(@tmp); # strip path
	    $fileName = $opt_d . "/" . $fileName; 

	    printf("producing file: %s\n", $fileName); 
	    open(OUT, ">$fileName") || die "Cannot open $fileName for output\n";
	    print OUT "# ######################################################################\n";
            print OUT "# $hostname\n";
	    print OUT "# $directory\n";
	    print OUT "# file list contains $runList{$run}->{NEVENTS} events\n";
	    print OUT "# mkPyFiles @args\n";
	    print OUT "# $fileName with $opt_e events, skipEvents = $skipevents\n";
	    print OUT "# ######################################################################\n";

		
            for ($l = 0; $l <= $#in; $l++) {
		# -- increment numbering
		if ($in[$l] =~ /XXXX/) {
		    ($tmp = $in[$l]) =~ s/XXXX/$blockName/g; 
		    $tmp  =~ s/--/-/g; # -- remove spurious double hyphens ...
		    print OUT $tmp, "\n";
		}
		# -- substitute files and skipevents and nevents
		elsif ($in[$l] =~ /POOLSOURCE/) {
		    print OUT "process.source = cms.Source(\n";
		    print OUT " \"PoolSource\",\n";
		    print OUT "  fileNames = cms.untracked.vstring(\n";
		    @bla = @{$runList{$run}->{FILELIST}}; 
		    for ($ij = 0; $ij <= $#bla; $ij++) {
			if ($ij < $#bla) {
			    print OUT "         \"$bla[$ij]\",\n";
			} else {
			    print OUT "         \"$bla[$ij]\"\n";
			}
		    }
		    
		    if ($skipevents > 0) {
			print OUT " ),\n";
			print OUT " skipEvents = cms.untracked.uint32(";
			print OUT $skipevents;
			print OUT ")\n";
		    } else {
			print OUT " )\n";
		    }
		    
		    print OUT ")\n";
		    if ($runList{$run}->{NEVENTS} < $opt_e) {
			print OUT "process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )\n";
		    } else {
			print OUT "process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32($opt_e) )\n";
		    }
		}
		
		
		# -- substitute files
		elsif ($in[$l] =~ /REPLACEFILES/) {
		    if ($opt_n) {
			$startline = $i*$opt_n; 
			$endline = ($i+1)*$opt_n; 
			for ($j = $startline; $j < $endline; $j++) {
			    if (length($files[$j+1]) > 1) {
				if ($j < $endline-1) {
				    print OUT "   \"$files[$j]\", \n"; 
				} else {
				    print OUT "   \"$files[$j]\" \n"; 
				}
			    } else {
				print OUT "   \"$files[$j]\"\n"; 
				last;
			    }	    
			}
		    } elsif ($opt_e) {
			print OUT @block[$bLine];
			print OUT "\n";
			$bLine++;
		    }
		} else {
		    print OUT $in[$l], "\n"; 
		}
	    }
	    
	    close(OUT); 
	    
	}
	
	
    }
    


}


# ----------------------------------------------------------------------
sub createPyFilesPerBlock() {

    my $fEvt = 0; 
    my $jobID = -1; 
    if ($opt_x) {
	$jobID = $opt_x - 1;
    }
    
    print "#fileList = $#fileList\n";
    
    for ($iFile = 0; $iFile <= $#fileList; $iFile++) {

	$blockName = sprintf("-%s", $opt_s);

	push(@fList, $fileList[$iFile]->{FILELIST}); 
	
	$fEvt += $fileList[$iFile]->{NEVENTS};

        print "file $iFile:  $fileList[$iFile]->{FILELIST} -> $fileList[$iFile]->{NEVENTS} .. $fEvt \n";
	
	if (($fEvt > $opt_e) || ($iFile == $#fileList)) {
	    $jobID++; 

	    $blockName .= sprintf("-%04i", $jobID);
	    ($fileName = $opt_t) =~ s/XXXX/$blockName/g;
	    $fileName  =~ s/--/-/g; # -- remove spurious double hyphens ...
	    $tmp = $fileName; @tmp = split(/\//, $fileName); $fileName = pop(@tmp); # strip path
	    $fileName = $opt_d . "/" . $fileName; 
	    
	    printf("producing file: %s\n", $fileName); 
	    open(OUT, ">$fileName") || die "Cannot open $fileName for output\n";
	    print OUT "# ######################################################################\n";
            print OUT "# $hostname\n";
	    print OUT "# $directory\n";
	    print OUT "# file list contains $runList{$run}->{NEVENTS} events\n";
	    print OUT "# mkPyFiles @args\n";
	    print OUT "# $fileName with $fEvt events\n";
	    print OUT "# ######################################################################\n";

		
            for ($l = 0; $l <= $#in; $l++) {
		# -- increment numbering
		if ($in[$l] =~ /XXXX/) {
		    ($tmp = $in[$l]) =~ s/XXXX/$blockName/g; 
		    $tmp  =~ s/--/-/g; # -- remove spurious double hyphens ...
		    print OUT $tmp, "\n";
		}
		# -- substitute files and skipevents and nevents
		elsif ($in[$l] =~ /POOLSOURCE/) {
		    print OUT "process.source = cms.Source(\n";
		    print OUT " \"PoolSource\",\n";
		    print OUT "  fileNames = cms.untracked.vstring(\n";
		    for ($ij = 0; $ij <= $#fList; $ij++) {
			if ($ij < $#fList) {
			    print OUT "         \"$fList[$ij]\",\n";
			} else {
			    print OUT "         \"$fList[$ij]\"\n";
			}
		    }
		    
		    print OUT " )\n";
		    
		    print OUT ")\n";
		    print OUT "process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )\n";
		}
		else {
		    print OUT $in[$l], "\n"; 
		}		
	    }	    
	    close(OUT); 

	    @fList = (); 
	    $fEvt = 0; 
	}
	
	
    }
    
}


# ----------------------------------------------------------------------
sub createPyFilesWithoutEvents() {
    
    my $n = 0; 
    my $jobID = -1; 

    if ($opt_x) {
	$jobID = $opt_x - 1;
    }
    
    for ($iFile = 0; $iFile <= $#fileList; $iFile++) {
	print "$fileList[$iFile]->{FILELIST}\n";

	$blockName = sprintf("-%s", $opt_s);
	push(@fList, $fileList[$iFile]->{FILELIST}); 
	$n++; 
	
	if ($n == $opt_n || $iFile == $#fileList) {
	    $jobID++; 

	    $blockName .= sprintf("-%04i", $jobID);
	    ($fileName = $opt_t) =~ s/XXXX/$blockName/g;
	    $fileName  =~ s/--/-/g; # -- remove spurious double hyphens ...
	    $tmp = $fileName; @tmp = split(/\//, $fileName); $fileName = pop(@tmp); # strip path
	    $fileName = $opt_d . "/" . $fileName; 
	    
	    printf("producing file: %s\n", $fileName); 
	    open(OUT, ">$fileName") || die "Cannot open $fileName for output\n";
	    print OUT "# ######################################################################\n";
            print OUT "# $hostname\n";
	    print OUT "# $directory\n";
	    print OUT "# file list contains $runList{$run}->{NEVENTS} events\n";
	    print OUT "# mkPyFiles @args\n";
	    print OUT "# $fileName with $fEvt events\n";
	    print OUT "# ######################################################################\n";

		
            for ($l = 0; $l <= $#in; $l++) {
		# -- increment numbering
		if ($in[$l] =~ /XXXX/) {
		    ($tmp = $in[$l]) =~ s/XXXX/$blockName/g; 
		    $tmp  =~ s/--/-/g; # -- remove spurious double hyphens ...
		    print OUT $tmp, "\n";
		}
		# -- substitute files and skipevents and nevents
		elsif ($in[$l] =~ /POOLSOURCE/) {
		    print OUT "process.source = cms.Source(\n";
		    print OUT " \"PoolSource\",\n";
		    print OUT "  fileNames = cms.untracked.vstring(\n";
		    for ($ij = 0; $ij <= $#fList; $ij++) {
			if ($ij < $#fList) {
			    print OUT "         \"$fList[$ij]\",\n";
			} else {
			    print OUT "         \"$fList[$ij]\"\n";
			}
		    }
		    
		    print OUT " )\n";
		    
		    print OUT ")\n";
		    print OUT "process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )\n";
		}
		else {
		    print OUT $in[$l], "\n"; 
		}		
	    }	    
	    close(OUT); 

	    @fList = (); 
	    $n = 0; 
	}
	
	
    }
    
}
