#!/usr/bin/env perl

# -s slim
use Getopt::Std;
getopts('i:s');

if ($ARGV[0]) {
    $name = $ARGV[0];
} else {
    die "need a name for the tarfile\n";
}

$include  = "AnalysisDataFormats/HeavyFlavorObjects HeavyFlavorAnalysis/Bs2MuMu";
if ($opt_i) {
    $include .= " $opt_i";
}

if ($opt_s) {$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/lib/\\*.so";}
$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/obj/\\*.o";
$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/test";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/obj/\\*.o";
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/lib/\\*.so";}
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/bin/\\*";}
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/chains/\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/crab";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/batchruns";
$exclude .= " --exclude \\*.root";
$exclude .= " --exclude \\*.pdf";
$exclude .= " --exclude \\*Dict\\*";

system("tar zcvf $name $include $exclude"); 
print("tar zcvf $name $include $exclude  --wildcards\n"); 
