#!/usr/bin/env perl

# -s slim
# -c complete (to be invoked from CMSSW_X_Y_Z, allows to be used w/o compilation)

use Getopt::Std;
getopts('ci:s');

if ($ARGV[0]) {
    $name = $ARGV[0];
} else {
    die "need a name for the tarfile\n";
}

$include  = "AnalysisDataFormats/HeavyFlavorObjects HeavyFlavorAnalysis/Bs2MuMu ";
if (-d "MuonAnalysis/MuonAssociators") { $include .= " MuonAnalysis/MuonAssociators ";}
if (-d "DataFormats/MuonReco") { $include .= " DataFormats/MuonReco ";}

if ($opt_c) {
    $include  = "src/AnalysisDataFormats/HeavyFlavorObjects src/HeavyFlavorAnalysis/Bs2MuMu src/MuonAnalysis/MuonAssociators lib config python";
}    
#$include  = $opt_i;
if ($opt_i) {
    $include .= " $opt_i";
}

if ($opt_s) {$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/lib/\\*.so";}
$exclude .= " --exclude obj/\\*.o";
$exclude .= " --exclude AnalysisDataFormats/HeavyFlavorObjects/test";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/obj/\\*.o";
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/lib/\\*.so";}
if ($opt_s) {$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/bin/\\*";}
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/chains/\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test/test-\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test/bmm-\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test/Winter\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test/Fall11";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/test/v\\*";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/crab";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/batchruns";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/ulcalc";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros/jobs";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/tmva";
$exclude .= " --exclude HeavyFlavorAnalysis/Bs2MuMu/macros2/chains";
$exclude .= " --exclude \\*.root";
$exclude .= " --exclude \\*.pdf";
$exclude .= " --exclude \\*.ps";
$exclude .= " --exclude \\*.eps";
$exclude .= " --exclude \\*~";
$exclude .= " --exclude \\*Dict\\*";

system("tar zcvf $name $include $exclude"); 
print("tar zcvf $name $include $exclude  --wildcards\n"); 
