#!/usr/bin/env perl

# Usage:       monGrid [-i jobs.list] [-u grid-url] [-o] [-r] [-x]
# ------
#              check status of grid jobs
#              if done, retrieve sandbox and put files into job directory 
#              if sandbox retrieved, check for successful job completion
#
# 2013/05/27   add -x to allow for resubmission of jobs that have not completed (even when they are still in "SUBMIT")
# 2011/09/16   copy logfile out from sandbox
# 2010/05/03   reworked some bugs
# 2010/03/09   remove capability of checking SGE jobs,use monSge instead
# 2010/03/03   First version
#              
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------

use File::Copy; 
use Getopt::Std;
getopts('i:oru:x');

my $user  = $ENV{'USER'};

my $minRootFileSize = 13362; 

# -- jobs list
my $jobslist = "jobs.list";
if ($opt_i) {
    $jobslist = $opt_i;
}

# -- which glite commands
my $gliteStatus = `which glite-wms-job-status`; chop($gliteStatus); 
if ($gliteStatus eq "") {
    die "glite-wms-job-status not found, cannot run without this\n";
}
my $gliteOutput = `which glite-wms-job-output`; chop($gliteOutput); 
if ($gliteOutput eq "") {
    die "glite-wms-job-output not found, cannot run without this\n";
}
$gliteOutput = $gliteOutput." --noint";

my $jobDestination  = ""; 
my $jobStatus       = ""; 
my $jobExitCode     = ""; 
my $jobStatusReason = ""; 

my $goodJobs = 0; 
my $badJobs  = 0; 
my $minGood  = 9999999999; 
open(IN, $jobslist) || die "Cannot find file $joblist with grid jobs\n";
while(<IN>) {
    next if (/\#\#\#/);

    # -- parse one job: one URL/sge and one additional line with information
    $url  = $_;   chop($url); 
    $line = <IN>; chop($line); 

    # -- fixed screwed jobs.list input
    while ($line =~ /https/) {
	$url = $line;
	$line = <IN>; chop($line); 
    }

    if ($url =~ /sge/) {
	next;
    }

    $line =~ s/\# //;
    ($machine, $date, $time, $dir, $jdl) = split(/ /, $line); 
    $pwd = `pwd`; chop($pwd);
    $mdir = $dir;
    $mdir =~ s%$pwd/%%;

    # -- if a specific URL is given, skip all others
    if ($opt_u && $url ne $opt_u) {
	next; 
    }

    # -- check whether this job had its sandbox retrieved already
    ($llog = $jdl) =~ s/jdl/log/;
    print "==> $llog\n";
    if (-e "$dir/$llog") {
	$ok = parseOutput($dir, $llog); 
	($rsize, $lsize, $srmFile) = rootFileSize("$dir/$llog"); 
    	printf("%50s %s; %s/root: %10i, log: %7i\n", $mdir, $url, $jobStatus, $ok, $rsize, $lsize);
	next; 
    }

    # -- get job status
    $gliteResult = `$gliteStatus $url`; 
    parseStatus($gliteResult); 

    # -- subdirectory where output sandbox is placed
    $string = substr($url, rindex($url, '/')+1, length($url)); 
    $sdir = $dir."/".$user."_".$string;
    
    # -- get output sandbox if successful and not yet already happened and not vetoed
    if ($jobStatus =~ /Done/ && $opt_o) {
	$logfile = getOutputSandBox($url, $dir, $jdl, $jobStatus); 
	chop($logfile); 
	if (-e "$sdir/$logfile") {
	    copy("$sdir/$logfile", "$mdir/$logfile");
	}
	$ok = parseOutput($sdir, $logfile); 
	($rsize, $lsize, $srmFile) = rootFileSize("$sdir/$logfile"); 
    	printf("%50s %s %15s; %s/root: %10i, log: %7i\n", $mdir, $url, $jobStatus, $ok, $rsize, $lsize);
	
	if ($ok =~ /no problems seen/) { 
	    system("/bin/touch $mdir/OK"); 
	    $goodJobs++; 
	    if ($rsize < $minGood) {$minGood = $rsize;}
	    if ($opt_r && ($rsize < $minRootFileSize)) {
		print "--> removing $srmFile\n"; 
		#system("srmrm $srmFile");
	    }
	} else { 
	    system("/bin/touch $mdir/NOK"); 
	    $badJobs++; 
	    if ($opt_r) {
		print "--> removing $srmFile\n"; 
		#system("srmrm $srmFile");
	    }
	}
    } elsif ($jobStatus =~ /Aborted/ && $opt_o) {
    	printf("%60s %s %15s; %s\n", $mdir, $url, $jobStatus, $jobStatus);
	system("/bin/touch $mdir/NOK"); 
	$badJobs++; 
    } elsif ($jobStatus =~ /Submitted/ && $opt_x) {
    	printf("%60s %s %15s; %s\n", $mdir, $url, $jobStatus, $jobStatus);
	system("/bin/touch $mdir/NOK"); 
	$badJobs++; 
    } elsif ($jobStatus =~ /Cleared/ && $opt_o) {
	$logfile = getOutputSandBox($url, $dir, $jdl, $jobStatus); 
	$ok = parseOutput($sdir, $logfile); 
	($rsize, $lsize, $srmFile) = rootFileSize("$sdir/$logfile"); 
    	printf("%60s %s %15s; %s/root: %10i, log: %7i\n", $mdir, $url, $jobStatus, $ok, $rsize, $lsize);
	if ($ok =~ /no problems seen/) { 
	    system("/bin/touch $mdir/OK"); 
	    $goodJobs++; 
	    if ($rsize < $minGood) {$minGood = $rsize;}
	    if ($opt_r && ($rsize < $minRootFileSize)) {
		print "--> removing $srmFile\n"; 
		system("srmrm $srmFile");
	    }
	} else { 
	    system("/bin/touch $mdir/NOK"); 
	    $badJobs++; 
	    if ($opt_r) {
		print "--> removing $srmFile\n"; 
		system("srmrm $srmFile");
	    }
	}
    } else {
    	printf("%60s %s %15s: %s\n", $mdir, $url, $jobStatus, $jobStatusReason);
    }

}

if ($opt_o) {
    print "----------------------------------------------------------------------\n";
    print "Successful jobs: $goodJobs\n";
    print "Failed jobs:     $badJobs\n";
    if ($goodJobs > 0) {print "Minimum rootfile size of good jobs: $minGood\n";}
    print "----------------------------------------------------------------------\n";
}



# ----------------------------------------------------------------------
sub parseStatus {
    ($in) = @_;
    @in = split(/\n/, $in); 
    $jobStatus = ""; 
    $jobStatusReason = ""; 
    $jobExitCode = ""; 
    $jobDestination = ""; 
    foreach $line (@in) {
	if ($line =~ s/Current Status:\ *//) { $jobStatus = $line; }
	if ($line =~ s/Status Reason:\ *//)  { $jobStatusReason = $line; }
	if ($line =~ s/Exit code:\ *//)      { $jobExitCode = $line; }
	if ($line =~ s/Destination:\ *//)    { $jobDestination = $line; }
    }

}


# ----------------------------------------------------------------------
sub getOutputSandBox {
    ($lurl, $ldir, $ljdl, $lstatus) = @_;
    if ($lstatus =~ /Cleared/){
    } else {
	system("$gliteOutput --dir $ldir $lurl >& /dev/null"); 
    }

    # -- determine logfile from jdl: 
    $logfile = `/bin/grep StdOutput $ldir/$ljdl`;
    $logfile =~ s/StdOutput\ *//;
    $logfile =~ s/\"//g;
    $logfile =~ s/\;//g;
    $logfile =~ s/= //g;

    return $logfile; 
}

# ----------------------------------------------------------------------
sub parseOutput {
    ($ldir, $logfile) = @_;

    # -- now search for possible problems in the logfile
    $foundException = `/bin/grep -i cms::exception  $ldir/$logfile`;
    if ($foundException) { $return = "cms::exception found"; }

    $foundGlibc     = `/bin/grep -i "glibc detected" $ldir/$logfile`;
    if ($foundGlibc) {$return = "core dump detected"; }

    $abort     = `/bin/grep -i "Abort" $ldir/$logfile`;
    if ($abort) {$return = "abort detected"; }

    # -- finally if no error found: 
    $foundMyEnd     = `/bin/grep -i "run: This is the end, my friend"  $ldir/$logfile`;
    if ($foundMyEnd) { $return = "no problems seen"; }

    return $return;
}


# ----------------------------------------------------------------------
sub rootFileSize {
    (my $logfile) = @_; 

    my $result  = 0; 
    my $logsize = 0; 

    open(LIN, "$logfile") || die "Cannot open $logfile\n";
    my $lfn = ""; 
    while(<LIN>) {
	if (/--> Save output to SE:/) {
	    ($bla, $lfn) = split(/SFN=/); 
	    ($bla, $pfn) = split(/SE: /); 
	    chop($lfn); 
	    my @tmp = split(/\//, $lfn); $rfn = pop(@tmp); 
	    #print "lfn: $lfn\n";
	    #print "rfn: $rfn\n";
	    ($logn = $lfn) =~ s/root$/log/;
	    #print "-> $logn\n";
	}


	if ($lfn ne "" && /([0-9]*) *$lfn/) {
	    if ($1 > 0) {
		$result = $1; 
		#print "-> $result\n";
		# last; 
	    }
	}


	if ($logn ne "" && /([0-9]*) *$logn/) {
	    if ($1 > 0) {
		$logsize = $1; 
		#print "-> $logsize\n";
		# last; 
	    }
	}
    }
    close(LIN); 
    return ($result, $logsize, $pfn); 
}
