#!/usr/bin/env perl

# Usage:       monSge [-i jobs.list] [-r]
# ------
#              check status of SGE jobs
#
# 2013/05/17   added check against "no events seen" in candAna
# 2013/02/28   fix again for the root file size and check that the file exists on the SE
# 2012/08/23   adapt to changed sge output at the end
# 2012/08/13   -k adds NOK file for terminated waiting/running jobs
# 2011/11/29   find terminated jobs
# 2011/01/20   parse for worker node that had failed job, dump into file problems.txt
# 2010/06/15   allow killing running jobs
# 2010/05/10   working again after some (previous) changes to jobs.list
# 2010/03/09   First version
#              
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('di:koru:v');

# -- jobs list
my $jobslist = "jobs.list";
if ($opt_i) {
    $jobslist = $opt_i;
}

my $STORAGE1 = "srm://storage01.lcg.cscs.ch:8443/srm/managerv2\?SFN=";

my $goodJobs = 0; 
my $runningJobs = 0; 
my $badJobs  = 0; 
my $minGood  = 9999999999; 
my $workerNode; 

open(IN, $jobslist) || die "Cannot find file $joblist with grid jobs\n";

my $user  = $ENV{'USER'};
if ($user eq "ursl") {
    open(OUT, ">>/shome/ursl/problems.txt") || die "Cannot open problems.txt\n";
} else {
    open(OUT, ">>problems.txt") || die "Cannot open problems.txt\n";
}

while(<IN>) {
    next if (/\#\#\#/);

    # -- parse one job: one URL/sge and one additional line with information
    my $url  = $_;   chop($url); 
    my $line = <IN>; chop($line); 
    
    # -- fixed screwed jobs.list input
    while ($line =~ /https/ || $line =~ /sge/) {
	$url = $line;
	$line = <IN>; chop($line); 
    }

    if ($url =~ /https/) {next;}

    if ($opt_v) {print "$line\n";}
    $line =~ s/\# //;
    ($machine, $date, $time, $dir, $jname, $sgeNumber) = split(/ /, $line); 
    my $pwd = `pwd`; chop($pwd);
    my $mdir = $dir;
    $mdir =~ s%$pwd/%%;
    (my $logfile = $mdir) =~ s/tmp-//;  
    $logfile .= ".sge.log";

    if (-e "$mdir/$logfile") {
	if ($opt_v) {print "parseOutput(\"$mdir/$logfile\")\n";}
	$ok = parseOutput("$mdir/$logfile"); 
	($rsize, $lsize, $srmFile) = rootFileSize("$mdir/$logfile"); 
	$lsize = -s "$mdir/$logfile";
    } else {
	if (-e "$mdir/$jobslist") {
	    $ok = "waiting";
	} else {
	    print "$mdir/$logfile not found???\n";
	    next;
	}
    }

   
    if ($ok eq "running" || $ok eq "waiting") {
	printf("%7i %10s %30s; %s\n", $sgeNumber, $jname, $mdir, $ok);
    } else {
	if ($rsize < 1) { 
	    $ok = "rootfile empty  ";
	}
	printf("%7i %10s; %s/root: %10i, log: %7i %30s (%s)\n", $sgeNumber, $jname, $ok, $rsize, $lsize, $mdir, $workerNode);
    }

    if ($ok =~ /no problems seen/) { 
	system("/bin/touch $mdir/OK"); 
	$goodJobs++; 
	if ($rsize < $minGood) {$minGood = $rsize;}
    } elsif ($ok eq "running" || $ok eq "waiting") {
	$runningJobs++; 
	if ($opt_k) {
	    # print "Killing job $jname $sgeNumber\n";
	    $bla = `qdel $sgeNumber`;
	    print $bla;
	    if (!$opt_d) {
		system("/bin/rm -f  $mdir/OK"); 
		system("/bin/touch $mdir/NOK"); 
	    }
	}
    } else { 
	print OUT "$workerNode: $sgeNumber ($jname) $mdir\n";
	if (!$opt_d) {
	    system("/bin/rm -f  $mdir/OK"); 
	    system("/bin/touch $mdir/NOK"); 
	}
	$badJobs++; 
	if ($opt_r) {
	    print "--> removing $srmFile\n"; 
	    system("srmrm $srmFile");
	}
    }
}

print "----------------------------------------------------------------------\n";
print "Successful jobs: $goodJobs\n";
print "Running jobs: $runningJobs\n";
print "Failed jobs:     $badJobs\n";
if ($goodJobs > 0) {print "Minimum rootfile size of good jobs: $minGood\n";}
print "----------------------------------------------------------------------\n";


# ----------------------------------------------------------------------
sub parseOutput {
    (my $llogfile) = @_;

    my $return = "running"; 

    if ($opt_v) {print "/bin/grep Linux $llogfile | awk '{print \$2}'\n";}
    $workerNode     = `/bin/grep Linux $llogfile | awk '{print \$2}'`;
    chop($workerNode);
    if ($opt_v) {print "-> $workerNode\n";}

    # -- now search for possible problems in the logfile
    $foundException = `/bin/grep -i "error, no events seen" $llogfile`;
    if ($foundException) { return "no events seen"; }

    $foundException = `/bin/grep -i cms::exception  $llogfile`;
    if ($foundException) { return "cms::exception found"; }

    $foundException = `/bin/grep -i 'Abort (core dumped)'  $llogfile`;
    if ($foundException) { return "abort/core dump detected"; }

    $foundGlibc     = `/bin/grep -i "glibc detected" $llogfile`;
    if ($foundGlibc) {return "abort/core dump detected"; }

    $foundBadAlloc   = `/bin/grep -i "std::bad_alloc" $llogfile`;
    if ($foundBadAlloc) {return "std::bad_alloc detected"; }

    $foundSEGV   = `/bin/grep -i "segmentation violation" $llogfile`;
    if ($foundSEGV) {return "segmentation violation detected"; }

    $foundJavaProblem   = `/bin/grep -i "java.lang.Error" $llogfile`;
    if ($foundJavaProblem) {return "java.lang.Error detected"; }

    # -- 
    $foundMyEnd     = `/bin/grep -i "run: This is the end, my friend"  $llogfile`;
    if ($foundMyEnd) { return "no problems seen"; }

    $foundTerminated = `/bin/grep -i "JOB Resource USAGE for job" $llogfile`; 
    if ($foundTerminated) {return "terminated job  "; }

    $foundTerminated = `/bin/grep -i "JOB Live Resources USAGE for job" $llogfile`; 
    if ($foundTerminated) {return "terminated job  "; }

    $foundTerminated = `/bin/grep -i "JOB Historical Resources USAGE for job" $llogfile`; 
    if ($foundTerminated) {return "terminated job  "; }

    if ($opt_v) {print "-> return $return\n";}
    return $return;
}


# ----------------------------------------------------------------------
sub rootFileSize {
    (my $llogfile) = @_; 

    my $result  = 0; 
    my $logsize = 0; 

#  -rw-rw-r--   1     2     2 791816255               ONLINE /pnfs/psi.ch/cms/trivcat/store/user/bstomumu/v14/cmsRun/2012/data-bmm-MuOnia/A/bmm-2012-rereco-v14-MuOnia__Run2012A-13Jul2012-v1-0000.root

    open(LIN, "$llogfile") || die "Cannot open $llogfile\n";
    my $lfn = ""; 
    # print "logfile: $llogfile\n";
    my $gotRoot = 0; 
    my $gotLog = 0; 
    while(<LIN>) {
	if (/--> Save output to SE:/) {
	    ($bla, $lfn) = split(/SFN=/); 
	    chop($lfn); 
	    my @tmp = split(/\//, $lfn); $rfn = pop(@tmp); 
	    #print "lfn: $lfn\n";
	    #print "rfn: $rfn\n";
	    ($logn = $lfn) =~ s/root$/log/;
	}

	if (/ONLINE/) {
	    ($stuff, $junk) = split(/ONLINE/); 
	    $stuff =~ s/\s{1,99}/\ /g;
	    my @tmpstuff = split(/\ /, $stuff);
	    $result = pop(@tmpstuff);
	    #print "result = $result\n";
	    $gotRoot = 1; 
	    if ($gotLog) {last; }
	}

    }
    close(LIN); 

    # -- check that the rootfile really exists on the SE
    if (-e "$lfn") {
    } else {
	$result = 0; 
    }

    return ($result, $logsize, "$STORAGE1$lfn"); 
}
