#!/usr/bin/env perl

# Usage:       run [-C] -c grid.csh -t tarfile -m {debug|local|grid|batch} *.py
# ------
#              submit to grid all jobs specified in the command line
#
# Example:     cd Bs2MuMu/test/Winter01/production/Bs2MuMu
# --------     ../../../../perl/run -c ../../gen.csh -t ~/grid/Winter07/grid-1.tar.gz -m grid
#              -r 'STORAGE1 srm://storage01.lcg.cscs.ch:8443/srm/managerv2\?SFN=/pnfs/lcg.cscs.ch/cms/trivcat/store/user/ursl/production/Winter10/BdToKPi' \ 
#              BsToMuMu_7TeV_GEN_SIM_DIGI_L1_DIGI2RAW_HLT_START-10014.py
#
# Assumptions: jobs are serialized a la asd_asd-asd-10000.py, the numbering is at the end, separated with -
# ------------ is run in directory where the py files reside!
#
# 2010/03/18   change name, remove all traces of ursl, add batch job name to jobs.list
# 2010/03/09   translate XXXX in replacements into the correct number
# 2010/03/08   Add -C to submit only those which crashed in a previous attempt. Add also batch jobs to jobs.list.
# 2010/03/06   Changed separation character for -r list to %, added default settings to always be written into csh!
# 2010/03/05   STORAGE1 and input file location now provided as command line argument
# 2010/03/03   Added grid URL duplication into local and common jobs.list files
# 2010/03/02   First version that runs locally, in batch, on the grid. 
#              
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('Cc:d:j:m:r:t:');

# -- Default settings
my $CMSSW = "CMSSW_3_5_0"; 
my $SCRAM = "slc5_ia32_gcc434";
my $SRMCP = "\"srmcp -2\"";          if ($opt_m eq "batch") {$SRMCP = "\"srmcp -2 -globus_tcp_port_range 20000,25000\"";}
my $user  = $ENV{'USER'};
my $glite = "/shome/$user/grid/glite.conf";

if (!-e "$glite") {
    print "$glite does not exist, using /shome/ursl/grid/glite.conf\n";
    $glite = "/shome/ursl/grid/glite.conf";    
}

# -- replacements
if ($opt_r) {$replace = $opt_r; }
@replaces = split(/%/, $replace); 
print "Replacement list: \n";
foreach $repl (@replaces) {
    print "$repl\n"
}

# -- destination
if ($opt_m eq "grid" && !$opt_d) {
    $opt_d = "ce01.lcg.cscs.ch"; 
    print " no destination provided, sending to CSCS: $opt_d\n";
}

my $host = `hostname`; 
chop($host); 

# -- split arguments into directory- and file-names
my $tarFile, $tarDirectory; 
($tarDirectory, $tarFile) = fileAndDirectory($opt_t); 
my $cshFile, $cshDirectory; 
($cshDirectory, $cshFile) = fileAndDirectory($opt_c); 

my $pwd = `pwd`; 
chop($pwd); 

# -- Make sure that the combined jobs.list exist
if (!(-e "../jobs.list")) { 
    open(TMP, ">../jobs.list"); 
    print TMP "###Submitted Job Ids###\n";
    close(TMP); 
}

# -- submit all job files
foreach $pyfile (@ARGV) {
    my $pyFile, $pyDirectory; 
    ($pyDirectory, $pyFile) = fileAndDirectory($pyfile); 
    if ($pyDirectory =~ /^\//) {
    } else {
	$pyDirectory = "../".$pyDirectory;
    }
    # -- Cut off trailing extension and possible directories in front
    ($barefile = $pyfile) =~ s/\.py//g;
    $rest = substr($barefile, 0, rindex($barefile, '/')+1); 
    $barefile =~ s/$rest//;
    $job      = $barefile;
    # -- Cut off everything except the number
    $number    = $job;
    $number = substr($job, rindex($job, '-')+1, length($job)); 

    $ENV{'JOB'}    = $job; 

    $tdir = "tmp-$job";
    # -- Check whether the previous submission was successful
    if ($opt_C) {
	if (-e "$tdir/NOK") {
	    print "resubmitting $job\n";
	    # -- remove old entry in jobs.list
	    $https = `/bin/grep https $tdir/jobs.list`; chop($https); 	    
	    &remove("jobs.list", $https); 
	    &remove("jobs.list", $tdir); # this will also remove the sge lines which contain $tdir
	} else {
	    next; 
	}
    }

     # -- create tmp directory for running/submission
    system("/bin/rm -rf $tdir"); 
    mkdir($tdir); 
    chdir($tdir);
    &makeJdlFile($job);
    &makeCshFile($job);
    system("/bin/cp $pyDirectory/$job.py .");
    &makeTarLink($job);
    system("/bin/chmod 755 $job.csh"); 

    # -- get a timestamp
    ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
    $year += 1900; 
    $timeStamp = sprintf("%s, %4i/%02i/%02i %02i:%02i:%02i", $host, $year, $mon, $mday, $hour, $min, $sec); 

    if ($opt_m eq "local") {
	print "local running: $job.csh\n";
	system("./$job.csh >& local.log");
    } elsif ($opt_m eq "debug") {
	print "debug, no running\n";
    } elsif ($opt_m eq "batch") {
	print "batch submission: $job\n";
	$jobName = "$job.csh";
	if ($user eq "ursl") { $jobName = `/shome/$user/perl/rline`; chop($jobName); }
	print "qsub -q all.q -N $jobName -o $pwd/$tdir/$job.sge.log -e $pwd/$tdir/$job.sge.err ./$job.csh\n";
	system("qsub -q all.q -N $jobName -o $pwd/$tdir/$job.sge.log -e $pwd/$tdir/$job.sge.err ./$job.csh");
	open(IN, ">>jobs.list") || die "Cannot open jobs.list\n";
	print IN "###Submitted Job Ids###\n";
	print IN "sge $tdir \n";
	print IN "\# $timeStamp $pwd/$tdir $job.jdl $jobName\n"; 
	close(IN); 
	system("/usr/bin/tail -2 jobs.list >> ../jobs.list");
    } elsif ($opt_m eq "grid") {
	print "grid running: $job.jdl\n";
	system("glite-wms-job-submit -o jobs.list -a --config $glite $job.jdl"); 
	open(IN, ">>jobs.list") || die "Cannot open jobs.list\n";
	print IN "\# $timeStamp $pwd/$tdir $job.jdl\n"; 
	close(IN); 
	system("/usr/bin/tail -2 jobs.list >> ../jobs.list");
    }

    chdir(".."); 
}


# ----------------------------------------------------------------------
sub makeTarLink {
    ($ljob) = @_;
    if ($opt_t =~ /^\//) {
	#system("/bin/ln -s $opt_t $ljob.tar.gz"); 
	system("/bin/cp $opt_t $ljob.tar.gz"); 
    } else {
	#system("/bin/ln -s ../$tarDirectory/$tarFile $ljob.tar.gz"); 
	system("/bin/cp ../$tarDirectory/$tarFile $ljob.tar.gz"); 
    }
}

# ----------------------------------------------------------------------
sub makeJdlFile {
    ($ljob) = @_;
    open(OUT, ">$ljob.jdl")  || die "Cannot open $ljob.jdl\n";
    my $datum = `/bin/date`; chop $datum;
    print OUT "# created by runGrid at $datum\n";
    print OUT "Executable    = \"$ljob.csh\";\n";
    print OUT "StdOutput     = \"$ljob.log\";\n";
    print OUT "StdError      = \"$ljob.err\";\n";
    print OUT "InputSandbox  ={\"$ljob.csh\", \"$ljob.jdl\", \"$ljob.py\", \"$ljob.tar.gz\"};\n";
    print OUT "OutputSandbox ={\"$ljob.csh\", \"$ljob.jdl\", \"$ljob.py\", \"$ljob.log\", \"$ljob.err\"};\n";
    print OUT "VirtualOrganisation = \"cms\";\n";
    print OUT "PerusalFileEnable = true;\n";
    print OUT "PerusalTimeInterval = 30;\n";
    if ($opt_d) {
	print OUT "Requirements  = ((RegExp(\"$opt_d\", other.GlueCEUniqueId)));\n";
    }

#    print OUT "Requirements  = ((RegExp(\"ce01.lcg.cscs.ch\", other.GlueCEUniqueId)) 
#                  && (Member(\"VO-cms-CMSSW_3_5_0\", other.GlueHostApplicationSoftwareRunTimeEnvironment))
#                 );\n";

    close OUT; 
}


# ----------------------------------------------------------------------
sub makeCshFile {
    ($ljob) = @_;
    if ($cshDirectory =~ /^\//) {
	open(IN, "$cshDirectory/$cshFile") || die "Cannot open $cshDirectory/$cshFile\n";
    } else {
	open(IN, "../$cshDirectory/$cshFile") || die "Cannot open ../$cshDirectory/$cshFile\n";
    }
    open(OUT, ">$ljob.csh")  || die "Cannot open $ljob.csh\n";
    my $datum = `/bin/date`; chop $datum;
    while (<IN>) {
	if (($opt_m eq "batch" || $opt_m eq "local") && /\# BATCH START/) {
	    print OUT "# BATCH START\n";
	    print OUT "mkdir -p /scratch/$user\n";
	    print OUT "cd /scratch/$user\n";
	    print OUT "mkdir \$JOB\n";
	    print OUT "cd \$JOB\n";
	    print OUT "/bin/cp $pwd/$tdir/$ljob.tar.gz .\n";
	    print OUT "/bin/cp $pwd/$tdir/$ljob.py .\n";
	}
	
	if (($opt_m eq "batch" || $opt_m eq "local") && /\# BATCH END/) {
	    print OUT "# BATCH END\n";
	    print OUT "cd ..\n";
	    print OUT "rm -rf \$JOB\n";
	}

	foreach $repl (@replaces) {
	    ($patt, $value) = split(/ /, $repl); 
	    # FIXME: HERE ADD PARSING/REPLACING OF XXXX with $number!!!
	    $value =~ s/XXXX/$number/g;
            if (/setenv $patt/) {
                s/$patt/$patt $value/g;
                last;
            }
	}

	if (/XXXX/) {
	    s/XXXX/$number/g;
	} elsif (/setenv CMSSW/) {
	    s/setenv CMSSW/setenv CMSSW       $CMSSW/g;
	} elsif (/setenv SRMCP/) {
	    s/setenv SRMCP/setenv SRMCP       $SRMCP/g;
	} elsif (/setenv SCRAM_ARCH/) {
	    s/setenv SCRAM_ARCH/setenv SCRAM_ARCH  $SCRAM/g;
	} elsif (/setenv JOB/) {
	    s/setenv JOB/setenv JOB      $ljob/g;
	}

	print OUT;
    }
    close OUT; 
}

	
# ----------------------------------------------------------------------
sub fileAndDirectory {
    ($in) = @_;

    $dir = substr($in, 0, rindex($in, '/')); 
    if (rindex($in, '/') < 0) { $dir = ""; }
    $file = substr($in, rindex($in, '/')+1, length($in)); 
    @result = ($dir, $file); 
    return @result; 
}

	
# ----------------------------------------------------------------------
sub remove {
    ($lfile, $lpat) = @_; 
    rename("$lfile", "$lfile.old"); 
    open(IN, "$lfile.old"); 
    open(OUT, ">$lfile"); 
    while(<IN>) {
	unless (/$lpat/) { print OUT; }
    }
    close(IN); 
    close(OUT); 
}
