#!/usr/bin/env perl

# Usage: cd chains/subdir; runAll -t tarfile [-h] [-m] [-n] [-r] [-a] [-d]
# ------
#            -d                           printout only, don't do anything
#            -h                           hadd the output rootfiles
#            -C                           run crashed jobs
#            -s {mc,data,signal,norm,cs}  run jobs of a specific sample
#            -r rootdir                   place where to put output
#
# 2011/11/14 added rare backgrounds (again)
# 2011/10/27 changed to new candAna setup
# 2011/05/26 realized that same dataset name will lead to problems on identical WN!
# 2011/05/17 added rare backgrounds
# 2010/11/25 remove inclusion of old merged file in dataset-* list ...
# 2010/11/23 first shot
# 2010/12/14 bug fix to allow really n wildcards (in addition to the trailing -*)
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------
use Getopt::Std;
getopts('Cdhj:r:s:t:v:');

my $job = "2011";
if ($opt_j) {
    $job = $opt_j; 
}

my $rootdir = "bmm/$job"; 
if ($opt_r) {
    $rootdir = $opt_r; 
}

if ($opt_v) {
    $version = $opt_v; 
} else {
    $version = "v12";
}

%jobs = (
    "signal Bs2MuMu MC 1e33"  
    => "-m,bmm2Reader.1e33-Bs2MuMu,cbmm-$version-1e33-Bs2MuMu,$version-1e33-Bs2MuMu.root"
    , "signal Bs2MuMu MC 2e33"  
    => "-m,bmm2Reader.2e33-Bs2MuMu,cbmm-$version-2e33-Bs2MuMu,$version-2e33-Bs2MuMu.root"
    , "signal Bs2MuMu MC 3e33"  
    => "-m,bmm2Reader.3e33-Bs2MuMu,cbmm-$version-3e33-Bs2MuMu,$version-3e33-Bs2MuMu.root"
    , "signal Bs2MuMu MC mix"  
    => "-m,bmm2Reader.mix-Bs2MuMu,cbmm-$version-mix-Bs2MuMu,$version-mix-Bs2MuMu.root"
    , "signal Bs2MuMu MC cms"  
    => "-m,bmm2Reader.mix-Bs2MuMu,cbmm-$version-mix-Bs2MuMu,$version-cms-Bs2MuMu.root"
    , "signal Bd2MuMu MC 1e33"  
    => "-m,bmm2Reader.1e33-Bd2MuMu,cbmm-$version-1e33-Bd2MuMu,$version-1e33-Bd2MuMu.root"
    , "signal Bd2MuMu MC 2e33"  
    => "-m,bmm2Reader.2e33-Bd2MuMu,cbmm-$version-2e33-Bd2MuMu,$version-2e33-Bd2MuMu.root"
    , "signal Bd2MuMu MC 3e33"  
    => "-m,bmm2Reader.3e33-Bd2MuMu,cbmm-$version-3e33-Bd2MuMu,$version-3e33-Bd2MuMu.root"
    , "signal Bd2MuMu MC mix"  
    => "-m,bmm2Reader.mix-Bd2MuMu,cbmm-$version-mix-Bd2MuMu,$version-mix-Bd2MuMu.root"
    #
    , "norm Bu2JpsiK MC 1e33"  
    => "-m,bmm2Reader.1e33-Bu2JpsiK,cbmm-$version-1e33-Bu2JpsiK-*,$version-1e33-Bu2JpsiK.root"
    , "norm Bu2JpsiK MC 2e33"  
    => "-m,bmm2Reader.2e33-Bu2JpsiK,cbmm-$version-2e33-Bu2JpsiK-*,$version-2e33-Bu2JpsiK.root"
    , "norm Bu2JpsiK MC 3e33"  
    => "-m,bmm2Reader.3e33-Bu2JpsiK,cbmm-$version-3e33-Bu2JpsiK-*,$version-3e33-Bu2JpsiK.root"
    , "norm Bu2JpsiK MC mix"  
    => "-m,bmm2Reader.mix-Bu2JpsiK,cbmm-$version-mix-Bu2JpsiK-*,$version-mix-Bu2JpsiK.root"
    , "norm Bu2JpsiK MC acc"  
    => "-m,bmm2Reader.2e33-Bu2JpsiK,cbmm-$version-2e33-accBu2JpsiK-*,$version-2e33-accBu2JpsiK.root"
    #
    , "cs Bs2JpsiPhi MC 1e33"  
    => "-m,bmm2Reader.1e33-Bs2JpsiPhi,cbmm-$version-1e33-Bs2JpsiPhi,$version-1e33-Bs2JpsiPhi.root"
    , "cs Bs2JpsiPhi MC 2e33"  
    => "-m,bmm2Reader.2e33-Bs2JpsiPhi,cbmm-$version-2e33-Bs2JpsiPhi,$version-2e33-Bs2JpsiPhi.root"
    , "cs Bs2JpsiPhi MC 3e33"  
    => "-m,bmm2Reader.3e33-Bs2JpsiPhi,cbmm-$version-3e33-Bs2JpsiPhi,$version-3e33-Bs2JpsiPhi.root"
    , "cs Bs2JpsiPhi MC mix"  
    => "-m,bmm2Reader.mix-Bs2JpsiPhi,cbmm-$version-mix-Bs2JpsiPhi,$version-mix-Bs2JpsiPhi.root"
    , "cs Bs2JpsiPhi MC acc"  
    => "-m,bmm2Reader.2e33-Bs2JpsiPhi,cbmm-$version-2e33-accBs2JpsiPhi-*,$version-2e33-accBs2JpsiPhi.root"
    #
    , "Bs2KMuNu rare MC"  
    => "-m,bmm2Reader.2e33-Bs2KMuNu,cbmm-$version-2e33-Bs2KMuNu,$version-2e33-Bs2KMuNu.root"
    , "Bd2PiMuNu rare MC"  
    => "-m,bmm2Reader.2e33-Bd2PiMuNu,cbmm-$version-2e33-Bd2PiMuNu-*,$version-2e33-Bd2PiMuNu.root"
    , "Lb2PMuNu rare MC"  
    => "-m,bmm2Reader.2e33-Lb2PMuNu,cbmm-$version-2e33-Lb2PMuNu,$version-2e33-Lb2PMuNu.root"
    , "Bs2KK rare MC"  
    => "-m,bmm2Reader.2e33-Bs2KK,cbmm-$version-2e33-Bs2KK,$version-2e33-Bs2KK.root"
    , "Bs2KPi rare MC"  
    => "-m,bmm2Reader.2e33-Bs2KPi,cbmm-$version-2e33-Bs2KPi,$version-2e33-Bs2KPi.root"
    , "Bs2PiPi rare MC"  
    => "-m,bmm2Reader.2e33-Bs2PiPi,cbmm-$version-2e33-Bs2PiPi,$version-2e33-Bs2PiPi.root"
    , "Bd2KK rare MC"  
    => "-m,bmm2Reader.2e33-Bd2KK,cbmm-$version-2e33-Bd2KK,$version-2e33-Bd2KK.root"
    , "Bd2KPi rare MC"  
    => "-m,bmm2Reader.2e33-Bd2KPi,cbmm-$version-2e33-Bd2KPi,$version-2e33-Bd2KPi.root"
    , "Bd2PiPi rare MC"  
    => "-m,bmm2Reader.2e33-Bd2PiPi,cbmm-$version-2e33-Bd2PiPi,$version-2e33-Bd2PiPi.root"
    , "Lb2KP rare MC"  
    => "-m,bmm2Reader.2e33-Lb2KP,cbmm-$version-2e33-Lb2KP,$version-2e33-Lb2KP.root"
    , "Lb2PiP rare MC"  
    => "-m,bmm2Reader.2e33-Lb2PiP,cbmm-$version-2e33-Lb2PiP,$version-2e33-Lb2PiP.root"
    #
    , "data 2011"  
    => "-b 1,bmm2Reader.data,cbmm-$version-Run2011*,$version-2011-data.root"
    # 
    , "bmt jet"  
    => "-b 0,bmt2Reader.data,cbmt-$version-Jet-*,$version-bmt-Jet.root"
    , "bmt ht"  
    => "-b 0,bmt2Reader.data,cbmt-$version-HT-*,$version-bmt-HT.root"
    , "bmt photon"  
    => "-b 0,bmt2Reader.data,cbmt-$version-Photon-*,$version-bmt-Photon.root"
    );

my $user  = $ENV{'USER'};

my $tarfile = "../../../../../111027.tar.gz";
if ($opt_t) {
    $tarfile = $opt_t; 
} else {
    if ($opt_h) {
    } else {
	die "provide a tarfile!\n";
    }
}

my $crash = ""; 
if ($opt_C) {$crash = "-C";}

my $srmcmd  = "lcg-cp -b -D srmv2";
my $dcap    = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
my $scratch = "/shome/$user/scratch"; # /scratch is likely too small
my $srm     = "srm://t3se01.psi.ch:8443/srm/managerv2\\?SFN=/pnfs/psi.ch/cms/trivcat/store";
my $storage = "$srm/user/$user/$rootdir";

#my $runCommand = "run $queue $crash -c ../../treeNoCompNoSE.csh -t $tarfile -m batch";
my $runCommand = "run $crash -c ../../treeNoComp.csh -t $tarfile -m batch";


# ----------------------------------------------------------------------
# -- run hadd instead of submitting
if ($opt_h) {
    # print "srmls $storage | grep root\n";
    @lines = `srmls $storage | grep root`;
    #@lines = `ls $storage/* | grep root`;

    foreach $j (keys %jobs) {
	if ($opt_s =~ /1e33/   && !($j =~ /1e33/)) {next; }
	if ($opt_s =~ /2e33/   && !($j =~ /2e33/)) {next; }
	if ($opt_s =~ /3e33/   && !($j =~ /3e33/)) {next; }
	if ($opt_s =~ /signal/ && !($j =~ /signal/)) {next; }
	if ($opt_s =~ /cs/     && !($j =~ /cs/)) {next; }
	if ($opt_s =~ /norm/   && !($j =~ /norm/)) {next; }
	if ($opt_s =~ /data/   && !($j =~ /data/)) {next; }
	if ($opt_s =~ /mc/     && !($j =~ /MC/)) {next; }
	if ($opt_s =~ /rare/   && !($j =~ /rare/)) {next; }
	if ($opt_s =~ /acc/    && !($j =~ /acc/)) {next; }
	if ($opt_s =~ /bmt/    && !($j =~ /bmt/)) {next; }
	# -- skip bmt jobs if not explicitely requested
	if (!($opt_s =~ /bmt/) && ($j =~ /bmt/)) {next; }

	($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	
	$dataset =~ s/-\*//;
	$dataset =~ s/\*/.\*/g;
	print "dataset = $dataset\n";
	print "file = $output\n";
	@rootfiles = grep(/$dataset/, @lines); 
	@rootfiles = grep(/\.root/, @rootfiles); 
	@rootfiles = grep(s/\n//, @rootfiles); 
	if ($#rootfiles == 0) {
	    @rootfiles = grep(s/.*$user\/$rootdir\///, @rootfiles); 
	    if ($opt_d) {
		# print "cp $rootfiles[0] $scratch/$output \n";
		# print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";		
		print "$srmcmd $storage/$rootfiles[0] $scratch/$output \n";
	    } else {
		# print "cp $rootfiles[0] $scratch/$output \n";
		# system("/bin/cp $rootfiles[0] $scratch/$output");
                # print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";
                # system("$srmcmd $storage/$rootfiles[0] $storage/$output");
		print "$srmcmd $storage/$rootfiles[0] $scratch/$output \n";
		system("$srmcmd $storage/$rootfiles[0] $scratch/$output");
	    }	    
	} elsif ($#rootfiles > 0) {
	    @rootfiles = grep(s/.*\/trivcat/$dcap/, @rootfiles); 
	    if ($opt_d) {
		print "hadd $scratch/$output \n";
		foreach $f (@rootfiles) {print "  $f\n";}
	    } else {
		print "hadd $scratch/$output @rootfiles\n";
		if (-e "$scratch/$output") {unlink("$scratch/$output"); }
		system("hadd $scratch/$output @rootfiles");
		system("srmrm $storage/$class/$output");
		system("$srmcmd $scratch/$output $storage/$class/$output");
	    }
	}
    }
    
    die "that's it \n";
}


# ----------------------------------------------------------------------
# -- submit the jobs
foreach $j (keys %jobs) {
    ($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
    if ($opt_s =~ /1e33/   && !($j =~ /1e33/)) {next; }
    if ($opt_s =~ /2e33/   && !($j =~ /2e33/)) {next; }
    if ($opt_s =~ /3e33/   && !($j =~ /3e33/)) {next; }
    if ($opt_s =~ /data/   && !($j =~ /data/)) {next; }
    if ($opt_s =~ /norm/   && !($j =~ /norm/)) {next; }
    if ($opt_s =~ /signal/ && !($j =~ /signal/)) {next; }
    if ($opt_s =~ /cs/     && !($j =~ /cs/)) {next; }
    if ($opt_s =~ /mc/     && !($j =~ /MC/)) {next; }
    if ($opt_s =~ /rare/   && !($j =~ /rare/)) {next; }
    if ($opt_s =~ /acc/    && !($j =~ /acc/)) {next; }
    if ($opt_s =~ /bmt/    && !($j =~ /bmt/)) {next; }
    # -- skip bmt jobs if not explicitely requested
    if (!($opt_s =~ /bmt/) && ($j =~ /bmt/)) {next; }  

    if ($j =~ /data/) {
	$command = "$runCommand -q all.q -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/$class' ./$dataset"; 
    } else {
	$command = "$runCommand -q all.q -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/$class' ./$dataset"; 
    }

    if ($opt_d) {
	print "$j \n$command\n";
    } else {
	print "$command\n";
	system($command);
    }

}

