#!/usr/bin/env perl
#
# Usage: cd chains/subdir; runAll2012 -t tarfile [-h] [-r v14/bmm/2012/test] [-d] [-l] [-C] [-s]
# ------
#            -a                                split checked chains (why a? because this is how you have to start)
#            -d                                printout only, don't do anything
#            -h                                hadd the output rootfiles
#            -m                                copy merged files from SE to local scratch area
#            -C                                run crashed jobs
#            -s {string}                       run jobs of a specific sample
#                                              e.g.: signalMC, normMC, rareMC, slMC, data
#            -r rootdir                        place where to put output 
#
# 2012/06/11 added rare backgrounds (again)
# 2013/03/11 added the START53_V7C samples
# 2013/03/20 add chain splitting (-a) 
#            add newline (removal) to "jobs" parsing, 
#            -s now searches for any subpart, not just well-defined parts
#            combine V7A and V7C
#            -m to mirror reduced trees onto local scratch disk
#            remove -l and fix data output into data and mc output into mc
# 2013/03/25 added opt_q, changed chunk size
#
# Examples: runAll2012 -d -t ../../../../../130313runBmm2.tar.gz -s signal
#           runAll2012 -d -h -s signal
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
#
# Modified by	Jose Lazo-Flores <Jose.Lazo-Flores@cern.ch>
# ----------------------------------------------------------------------
use lib '/shome/ursl/perl/modules/Tie-IxHash-1.23/lib';
use Tie::IxHash;

use Getopt::Std;
getopts('aCdhj:l:m:q:r:s:t:v:');

# -- no input needed from this script ...
if ($opt_a) {
    &callA;
    die "done with splitting of checked chains\n";
}

my $job = "2012";
if ($opt_j) {
    $job = $opt_j; 
}

my $jobsList = "jobs.list";
if ($opt_l) {
    $jobsList = $opt_l; 
}

if ($opt_v) {
    $version = $opt_v; 
} else {
    $version = "v16";
}

my $rootdir = "$version/bmm/$job"; 
if ($opt_r) {
    $rootdir = $opt_r; 
}

my $queue = "short.q"; 
if ($opt_q) {
    $queue = $opt_q; 
}


# -- more definitions
my $scrtuser  = $ENV{'USER'};
my $user  = bstomumu;

my $tarfile = "../../../../../120416.tar.gz";
if ($opt_t) {
    $tarfile = $opt_t; 
} else {
    if ($opt_a || $opt_m || $opt_h) {
    } else {
	die "provide a tarfile!\n";
    }
}

my $crash = ""; 
if ($opt_C) {$crash = "-C";}

#my $srmcmd  = "lcg-cp -b -D srmv2";
my $srmcmd  = "srmcp -2 --streams_num=2";
my $srmpf   = "file:///";
my $dcap    = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
my $scratch = "/scratch/$scrtuser";
my $srm     = "srm://t3se01.psi.ch:8443/srm/managerv2\\?SFN=/pnfs/psi.ch/cms/trivcat/store";
my $storage = "$srm/user/$user/$rootdir";

my $runCommand = "run -l $jobsList $crash -c ../../treeNoCompSpecialRoot.csh -t $tarfile -m batch";
if ($opt_d) {
    $runCommand = "run -d -l $jobsList $crash -c ../../treeNoCompSpecialRoot.csh -t $tarfile -m batch";
}


# ----------------------------------------------------------------------
# -- The hash shall not change the order of its elements
tie %jobs, "Tie::IxHash";

%jobs = (
# -- signal Bs2MuMu and Bd2MuMU
    "signalMCfilter Bs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
 cbmm-2012-v16-BsToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToMuMu.root"
    , "signalMCfilter Bd2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bd2MuMu,
cbmm-2012-v16-BdToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToMuMu.root"
    , "signalMCacc Bs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-accBsToMuMu.root"
    , "signalMCacc Bd2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bd2MuMu,
cbmm-2012-v16-BdToMuMu_BdFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*,
$version-2012-cms-accBdToMuMu.root"
    , "signalMChacked m57Bs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_M-57_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v2-*,
$version-2012-cms-m57BsToMuMu.root"
    , "signalMChacked m51Bs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_M-51_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v2-*,
$version-2012-cms-m51BsToMuMu.root"
    , "signalMCHLT 5e33ABs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT5E33_PU_S10_START53_V19A-*,
$version-2012-cms-5e33ABsToMuMu.root"
    , "signalMCHLT 7e33BBs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT7E33_PU_S10_START53_V19B-*,
$version-2012-cms-7e33BBsToMuMu.root"
    , "signalMCHLT 7e33CBs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT7E33_PU_S10_START53_V19C-*,
$version-2012-cms-7e33CBsToMuMu.root"
    , "signalMCHLT 8e33DBs2MuMu"  
    => "-y 2012 -m,bmm2Reader.mix-Bs2MuMu,
cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT8E33_PU_S10_START53_V19D-*,
$version-2012-cms-8e33DBsToMuMu.root"
# -- normalization and control samples (plus backgrounds)
    , "normMCfilter Bu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_K2MuPtEtaEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2-*
 cbmm-2012-v16-BuToJPsiK_K2MuPtEtaEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BuToJpsiK.root"
    , "normMCacc Bu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_K2MuFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-accBuToJpsiK.root"
    , "normMCHLT v19ABu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19A-v1-*,
$version-2012-cms-V19ABuToJpsiK.root"
    , "normMCHLT v19BBu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19B-v1-*,
$version-2012-cms-V19BBuToJpsiK.root"
    , "normMCHLT v19CBu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19C-v1-*,
$version-2012-cms-V19CBuToJpsiK.root"
    , "normMCHLT v19DBu2JpsiK"  
    => "-y 2012 -m,
bmm2Reader.mix-Bu2JpsiK,
 cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19D-v1-*,
$version-2012-cms-V19DBuToJpsiK.root"
    , "normMCfilter Bs2JpsiPhi"  
    => "-y 2012 -m,
bmm2Reader.mix-Bs2JpsiPhi,
 cbmm-2012-v16-BsToJPsiPhi_2K2MuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToJPsiPhi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToJpsiPhi.root"
    , "normMCacc Bs2JpsiPhi"  
    => "-y 2012 -m,
bmm2Reader.mix-Bs2JpsiPhi,
 cbmm-2012-v16-BsToJPsiPhi_2K2MuFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToJPsiPhi_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-accBsToJpsiPhi.root"
    , "normMC BuToJpsiPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bu2JpsiPi,
 cbmm-2012-v16-BuToJpsiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BuToJpsiPi.root"
    # -- data
    , "data 2012"  
    => "-y 2012 -b 1,
bmm2Reader.2012,
 cbmm-2012-$version-MuOnia__Run2012*,
$version-2012-bmm-data.root"
    # -- rare Bs bg
    , "rareMC Bs2KK"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bs2KK,
 cbmm-2012-v16-BsToKK_2KPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToKK.root"
    , "slMC Bs2KMuNu"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bs2KMuNu,
 cbmm-2012-v16-BsToKMuNu_KMuNuEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToKMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToKMuNu.root"
    , "rareMC Bs2KPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bs2KPi,
 cbmm-2012-v16-BsToKPi_KPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToKPi.root"
    , "slMC Bs2MuMuGamma"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bs2MuMuGamma,
 cbmm-2012-v16-BsToMuMuGamma_MuMuEtaPtGammaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToMuMuGamma.root"
    , "rareMC Bs2PiPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bs2PiPi,
 cbmm-2012-v16-BsToPiPi_2PiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BsToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BsToPiPi.root"
    # -- rare Bd bg
    , "rareMC Bd2KK"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2KK,
 cbmm-2012-v16-BdToKK_2KPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*
 cbmm-2012-v16-BdToKK_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToKK.root"
    , "rareMC Bd2KPi"  	
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2KPi,
 cbmm-2012-v16-BdToKPi_KPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-* 
 cbmm-2012-v16-BdToKPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToKPi.root"
    , "rareMC Bd2PiPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2PiPi,
 cbmm-2012-v16-BdToPiPi_2PiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2-* 
 cbmm-2012-v16-BdToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*
 cbmm-2012-v16-BdToPiPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToPiPi.root"
    , "slMC Bd2PiMuNu"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2PiMuNu,
 cbmm-2012-v16-BdToPiMuNu_PiMuNuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToPiMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToPiMuNu.root"
    , "slMC Bd2MuMuGamma"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2MuMuGamma,
 cbmm-2012-v16-BdToMuMuGamma_MuMuEtaPtGammaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToMuMuGamma.root"
    , "slMC Bd2MuMuPi0"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2MuMuPi0,
 cbmm-2012-v16-BdToMuMuPi0_MuMuPi0EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToMuMuPi0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToMuMuPi0.root"
    , "slMC Bd2MuMuK0" 
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2MuMuK0,
 cbmm-2012-v16-BuToMuMuK0_MuMuK0EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BdToMuMuK0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToMuMuK0.root"
    , "rareMC BdToJpsiKstar"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2JpsiKstar,
 cbmm-2012-v16-BdToJpsiKstar_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToJpsiKstar.root"
    , "rareMC BdToRhoPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bd2RhoPi,
 cbmm-2012-v16-BdToRohPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BdToRohPi.root"
    # -- rare Bu bg
    , "slMC Bu2MuMuK"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bu2MuMuK,
 cbmm-2012-v16-BuToMuMuK_MuMuKEtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BuToMuMuK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*
 cbmm-2012-v16-BuToMuMuK_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BuToMuMuK.root"
    , "slMC Bu2MuMuPi"  
    => "-y 2012 -m,
bmm2Reader.2e33-Bu2PiMuMu,
 cbmm-2012-v16-BuToMuMuPi_MuMuPiEtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-BuToMuMuPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-BuToMuMuPi.root"
    # -- rare Lb bg
    , "rareMC Lb2PK"  
    => "-y 2012 -m,
bmm2Reader.2e33-Lb2KP,
 cbmm-2012-v16-LambdaBToPK_PKPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2-*
 cbmm-2012-v16-LambdaBToPK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-LambdaBToPK.root"
    , "rareMC Lb2PiP"  
    => "-y 2012 -m,
bmm2Reader.2e33-Lb2PiP,
 cbmm-2012-v16-LambdaBToPPi_PPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-LambdaBToPPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*
 cbmm-2012-v16-LambdaBToPPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-LambdaBToPPi.root"
    , "slMC Lb2PMuNu"  
    => "-y 2012 -m,
bmm2Reader.2e33-Lb2PMuNu,
 cbmm-2012-v16-LambdaBToPMuNu_PMuNuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1-*
 cbmm-2012-v16-LambdaBToPMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1-*,
$version-2012-cms-LambdaBToPMuNu.root"
    );

# -- reformat the entries to correct for the newlines
foreach $j (keys %jobs) {
    $jobs{$j} =~ s%\n%%g;
}


# ----------------------------------------------------------------------
# -- mirror to local scratch disk
if ($opt_m ne "") {
    &callM;
    die "done with mirroring to $opt_m\n";
}


# ----------------------------------------------------------------------
# -- run hadd instead of submitting
if ($opt_h) {
    callH(); 
    die "running hadd\n";
}

# ----------------------------------------------------------------------
# -- submit the jobs
foreach $j (keys %jobs) {
    ($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
    if ($opt_s && !($j =~ /$opt_s/)) {next;}
    if ($j =~ /data/) {
	$command = "$runCommand -q $queue -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/data' $dataset"; 
    } else {
	$command = "$runCommand -q $queue -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/mc' $dataset"; 
    }

    if ($opt_d) {
	#$command = "$runCommand -q all.q -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage' $dataset";
	print "$command \n";
    } else {
	print "$command\n";
	system($command);
    }

}

die "this is the end ... \n";



# ----------------------------------------------------------------------
sub callM() {
    foreach $j (keys %jobs) {
	($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	print "$srmcmd $storage/$output $srmpf$scratch/$opt_m/$output\n";
	system("$srmcmd $storage/$output $srmpf$scratch/$opt_m/$output");
    }
    die "done with copy to local scratch area\n";
}


# ----------------------------------------------------------------------
sub callH() {
    print "srmls $storage/data |grep root \n";
    print "srmls $storage/mc |grep root \n";
    @dlines = `srmls $storage/data |grep root `;
    @mlines = `srmls $storage/mc |grep root `;
    
    push(@lines, @dlines); 
    push(@lines, @mlines); 

    foreach $j (keys %jobs) {
	if ($opt_s && !($j =~ /$opt_s/)) {next;}

	($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	
	$dataset =~ s/-\*//;
	$dataset =~ s/\*/.\*/g;
	@vdataset = split(/ /, $dataset); 
	print "dataset = $dataset\n";
	print "file = $output\n";
	my @rootfiles = (); 
	foreach $ds (@vdataset) {
	    @rf = grep(/$ds/, @lines); 
	    push(@rootfiles, @rf); 
	}
	@rootfiles = grep(/\.root/, @rootfiles); 
	@rootfiles = grep(s/\n//, @rootfiles); 
	if ($#rootfiles == 0) {
	    @rootfiles = grep(s/.*$user\/$rootdir\///, @rootfiles); 
	    if ($opt_d) {
		print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";
		print "$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output \n";
	    } else {
		print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";
		print "$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output \n";
		system("srmrm  $storage/$output");
		system("$srmcmd $storage/$rootfiles[0] $storage/$output");
		system("$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output");
	    }	    
	} elsif ($#rootfiles > 0) {
	    @rootfiles = grep(s/.*\/trivcat/$dcap/, @rootfiles); 
	    @rootfiles = sort @rootfiles; 

	    if ($opt_d) {
		print "hadd $scratch/$output ...\n";
		foreach $f (@rootfiles) {print "  $f\n";}
		print "srmrm $storage/$output \n";
		print "$srmcmd $srmpf$scratch/$output $storage/$output \n";
	    } else {
		#print "hadd $scratch/$output @rootfiles\n";
		if (-e "$scratch/$output") {unlink("$scratch/$output"); }
		system("hadd $scratch/$output @rootfiles");
		system("srmrm $storage/$output");
		system("$srmcmd $srmpf$scratch/$output $storage/$output");
	    }
	}
    }
    
    die "that's it \n";
}



# ----------------------------------------------------------------------
sub callA() {

#    my $datasplit = 350000; 
#    my $mcsplit   = 700000; 

    my $datasplit = 400000; 
    my $mcsplit   = 500000; 
    
    @data = (
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012A-13Jul2012-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012A-recover-06Aug2012-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012B-13Jul2012-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012C-24August2012-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012C-PromptReco-v2", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012D-PromptReco-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2012-v16-MuOnia__Run2012D-16Jan2013-v1"
	);
    
    
    
    @signal = (
#this is useless "splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_BsFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMu_BdFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_M-51_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v2",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_M-57_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v2",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT5E33_PU_S10_START53_V19A-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT7E33_PU_S10_START53_V19B-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT7E33_PU_S10_START53_V19C-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMu_8TeV-pythia6-evtgen__Summer12_DR53X-HLT8E33_PU_S10_START53_V19D-v1", 
	);
    
    @normalization = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_K2MuFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_K2MuPtEtaEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_K2MuPtEtaEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19A-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19B-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19C-v1", 
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJPsiK_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V19D-v1", 
	); 
    
    @controlsample = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToJPsiPhi_2K2MuFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToJPsiPhi_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToJPsiPhi_2K2MuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToJPsiPhi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1"
	); 
    
    @rareBs = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKK_2KPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKPi_KPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKMuNu_KMuNuEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToKMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToPiPi_2PiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMuGamma_MuMuEtaPtGammaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BsToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1"
	);
    
    @rareBd = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKK_2KPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKK_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKPi_KPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToKPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToPiPi_2PiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToPiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToPiPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToPiMuNu_PiMuNuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToPiMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMuGamma_MuMuEtaPtGammaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMuGamma_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMuPi0_MuMuPi0EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMuPi0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToMuMuK0_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuK0_MuMuK0EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToJpsiKstar_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToRohPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BdToD0starPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1"
	);
    
    @rareBu = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToJpsiPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuK_MuMuKEtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuK_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuPi_MuMuPiEtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-BuToMuMuPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1"
	); 
    
    @rareLb = (
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPK_PKPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v2",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPK_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPPi_PPiPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPPi_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPPi_EtaPtFilter_8TeV_ext-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",

	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPMuNu_EtaPtFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7C-v1",
	"splitCheckedChain -n $mcsplit ../cbmm-2012-v16-LambdaBToPMuNu_PMuNuPtEtaFilter_8TeV-pythia6-evtgen__Summer12_DR53X-PU_S10_START53_V7A-v1"
	);

    foreach $c (@data, @signal, @normalization, @controlsample, @rareBs, @rareBd, @rareBu, @rareLb) {
	system("$c");
    }


}

