#!/usr/bin/env perl

# Usage: cd chains/subdir; runAll -t tarfile [-h] [-m] [-n] [-r] [-a] [-d]
# ------
#            -d            printout only, don't do anything
#            -h            hadd the output rootfiles
#            -C            run crashed jobs
#            -c            run data ("CMS") jobs
#            -m            run MC jobs
#            -n            run normalization jobs
#            -s            run signal jobs
#            -a            run Bs2JpsiPhi jobs
#            -r rootdir    place where to put output
#
# 2010/11/23 first shot
# 2010/11/25 remove inclusion of old merged file in dataset-* list ...
# 2010/12/14 bug fix to allow really n wildcards (in addition to the trailing -*)
# 2011/05/17 added rare backgrounds
# 2011/05/26 realized that same dataset name will lead to problems on identical WN!
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('aCcdhj:mnq:r:s:t:');

my $job = "2010";
if ($opt_j) {
    $job = $opt_j; 
}

my $rootdir = "bmm/$job"; 
if ($opt_r) {
    $rootdir = $opt_r; 
}

my %jobs = ("signal MC" 
	    => "-m,bmmSignalReader,bmmSignalReader.$job.cuts,cBsToMuMu_2MuPtFilter_7TeV-pythia6-evtgen-Fall10,signalMC2010.root"
	    , "signal Bd2MuMu MC" 
	    => "-m,bmmSignalReader,bmmBd2MuMuReader.$job.cuts,cBdToMuMu_2MuPtFilter_7TeV-pythia6-evtgen-Fall10,Bd2MuMu2010.root"
	    , "signal data" 
	    => "-b 1,bmmSignalReader,bmmSignalReader.$job.cuts,cv01-signal-MuOnia-Run2010*_v1-*,signalData2010.root"
	    , "norm MC" 
	    => "-m,bmmNormalizationReader,bmmNormalizationReader.$job.cuts,cBpToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen-Fall10-*,normMC2010.root"
	    , "norm bg MC" 
	    => "-m,bmmNormalizationReader,bmmNormalizationReader.$job.cuts,cB0ToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen-Fall10-*,Bd2JpsiXMC2010.root"
	    , "norm data" 
	    => "-b 0,bmmNormalizationReader,bmmNormalizationReader.$job.cuts,cv01-norm-MuOnia-Run2010*_v1-*,normData2010.root"
	    , "Bs2JpsiPhi MC" 
	    => "-m,bmmBs2JpsiPhiReader,bmmBs2JpsiPhiReader.$job.cuts,cBsToJPsiMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen-Fall10-*,Bs2JpsiPhiMC2010.root"
	    , "Bs2JpsiPhi data" 
	    => "-b 0,bmmBs2JpsiPhiReader,bmmBs2JpsiPhiReader.$job.cuts,cv01-cs-MuOnia-Run2010*_v1-*,Bs2JpsiPhiData2010.root"
    );

my $user  = $ENV{'USER'};

my $tarfile = "../../../../../101123.tar.gz";
if ($opt_t) {
    $tarfile = $opt_t; 
} else {
    if ($opt_h) {
    } else {
	die "provide a tarfile!\n";
    }
}

my $crash = ""; 
if ($opt_C) {$crash = "-C";}

my $queue = ""; 
if (!$opt_q && !opt_h) {
    print "-q not set\n";
    $queue = "-q all.q";
} else {
    $queue = "-q $opt_q";
}

my $storage = "/shome/ursl/scratch/$rootdir";
my $srmcmd = "srmcp -2 --streams_num=1";
my $dcap = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
#my $scratch = "/scratch/$user"; 
my $scratch = "/shome/$user/scratch"; 

my $runCommand = "run $queue $crash -c ../../treeNoCompNoSE.csh -t $tarfile -m batch";


# ----------------------------------------------------------------------
# -- run hadd instead of submitting
if ($opt_h) {
    foreach $j (keys %jobs) {
	if ($opt_s =~ /signal/ && !($j =~ /signal/)) {next; }
	if ($opt_s =~ /cs/     && !($j =~ /Bs2JpsiPhi/)) {next; }
	if ($opt_s =~ /norm/   && !($j =~ /norm/)) {next; }
	if ($opt_s =~ /data/   && !($j =~ /data/)) {next; }
	if ($opt_s =~ /mc/     && !($j =~ /MC/)) {next; }
	($options, $class, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	#@lines = `srmls $storage/$class | grep root`;
	@lines = `ls $storage/$class/* | grep root`;

	$dataset =~ s/-\*//;
	$dataset =~ s/\*/.\*/g;
	print "dataset = $dataset\n";
	print "file = $output\n";
	@rootfiles = grep(/$dataset/, @lines); 
	@rootfiles = grep(/\.root/, @rootfiles); 
	#@rootfiles = grep(s/.*\/trivcat/$dcap/, @rootfiles); 
	@rootfiles = grep(s/\n//, @rootfiles); 
	if ($#rootfiles > -1) {
	    if ($opt_d) {
		print "hadd $scratch/$output \n";
		foreach $f (@rootfiles) {print "  $f\n";}
	    } else {
		print "hadd $scratch/$output @rootfiles\n";
		if (-e "$scratch/$output") {unlink("/scratch/$user/$output"); }
		system("hadd $scratch/$output @rootfiles");
		#system("srmrm $storage/$class/$output");
		#system("$srmcmd file:///$scratch/$output $storage/$class/$output");
	    }
	}
    }
    
    die "that's it \n";
}


# ----------------------------------------------------------------------
# -- submit the jobs
foreach $j (keys %jobs) {
    ($options, $class, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
    $command = "$runCommand -x 'bin/runTreeReaders -r $class $options -C cuts/$cutfile' -r 'STORAGE1 $storage/$class' ./$dataset"; 
    if ($opt_s =~ /data/   && !($j =~ /data/)) {next; }
    if ($opt_s =~ /norm/   && !($j =~ /norm/)) {next; }
    if ($opt_s =~ /signal/ && !($j =~ /signal/)) {next; }
    if ($opt_s =~ /cs/     && !($j =~ /Bs2JpsiPhi/)) {next; }
    if ($opt_s =~ /mc/     && !($j =~ /MC/)) {next; }

    if ($opt_d) {
	print "$j \n$command\n";
    } else {
	print "$command\n";
	system($command);
    }

}

