#!/usr/bin/env perl
#
# Usage: cd chains/subdir; runAll2011 -t tarfile [-h] [-r v16/bmm/2011/test] [-d] [-l] [-C] [-s data]
# ------
#            -a                                split checked chains (why a? because this is how you have to start)
#            -d                                printout only, don't do anything
#            -h                                hadd the output rootfiles
#            -m                                copy merged files from SE to local scratch area
#            -C                                run crashed jobs
#            -s {string}                       run jobs of a specific sample
#            -r rootdir                        place where to put output 
#
# 2012/06/11 added rare backgrounds (again)
# 2013/03/11 added the START53_V7C samples
# 2013/03/20 add chain splitting (-a) 
#            add newline (removal) to "jobs" parsing, 
#            -s now searches for any subpart, not just well-defined parts
#            combine V7A and V7C
#            -m to mirror reduced trees onto local scratch disk
#            remove -l and fix data output into data and mc output into mc
#
# Examples: runAll2012 -d -t ../../../../../130313runBmm2.tar.gz -s signal
#           runAll2012 -d -h -s signal
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
#
# Modified by	Jose Lazo-Flores <Jose.Lazo-Flores@cern.ch>
# ----------------------------------------------------------------------
use lib '/shome/ursl/perl/modules/Tie-IxHash-1.23/lib';
use Tie::IxHash;

use Getopt::Std;
getopts('aCdhj:m:l:q:r:s:t:v:');

# -- no input needed from this script ...
if ($opt_a) {
    &callA;
    die "done with splitting of checked chains\n";
}

my $job = "2011";
if ($opt_j) {
    $job = $opt_j; 
}

my $jobsList = "jobs.list";
if ($opt_l) {
    $jobsList = $opt_l; 
}

if ($opt_v) {
    $version = $opt_v; 
} else {
    $version = "v16";
}

my $rootdir = "$version/bmm/$job"; 
if ($opt_r) {
    $rootdir = $opt_r; 
}

my $queue = "short.q"; 
if ($opt_q) {
    $queue = $opt_q; 
}


# -- more definitions
my $scrtuser  = $ENV{'USER'};
my $user  = bstomumu;

my $tarfile = "../../../../../120416.tar.gz";
if ($opt_t) {
    $tarfile = $opt_t; 
} else {
    if ($opt_a || $opt_m || $opt_h) {
    } else {
	die "provide a tarfile!\n";
    }
}

my $crash = ""; 
if ($opt_C) {$crash = "-C";}

#my $srmcmd  = "lcg-cp -b -D srmv2";
my $srmcmd  = "srmcp -2 --streams_num=2";
my $srmpf   = "file:///";
my $dcap    = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
my $scratch = "/scratch/$scrtuser";
my $srm     = "srm://t3se01.psi.ch:8443/srm/managerv2\\?SFN=/pnfs/psi.ch/cms/trivcat/store";
my $storage = "$srm/user/$user/$rootdir";

my $runCommand = "run -l $jobsList $crash -c ../../treeNoCompSpecialRoot.csh -t $tarfile -m batch";
if ($opt_d) {
    $runCommand = "run -d -l $jobsList $crash -c ../../treeNoCompSpecialRoot.csh -t $tarfile -m batch";
}


# ----------------------------------------------------------------------
# -- The hash shall not change the order of its elements
tie %jobs, "Tie::IxHash";

%jobs = (
    "signalMC Bs2MuMu"  
    => "-y 2011 -m,bmm2Reader.mix-Bs2MuMu,cbmm-2011-$version-mix-Bs2MuMu-0*,$version-2011-mix-Bs2MuMu.root"
    , "signalMC Bd2MuMu"  
    => "-y 2011 -m,bmm2Reader.mix-Bd2MuMu,cbmm-2011-$version-mix-Bd2MuMu-0*,$version-2011-mix-Bd2MuMu.root"
#    , "signalMChacked m57Bs2MuMu"  
#    => "-y 2011 -m,bmm2Reader.mix-Bs2MuMu,cbmm-mc-2011-v16-BsToMuMu_M-57-*,$version-2011-cms-m57BsToMuMu.root"
#    , "signalMChacked m51Bs2MuMu"  
#    => "-y 2011 -m,bmm2Reader.mix-Bs2MuMu,cbmm-mc-2011-v16-BsToMuMu_M-51-*,$version-2011-cms-m51BsToMuMu.root"
    #
    , "normMCfilter Bu2JpsiK"  
    => "-y 2011 -m,bmm2Reader.mix-Bu2JpsiK,cbmm-2011-$version-mix-Bu2JpsiK-*,$version-2011-mix-Bu2JpsiK.root"
    , "normMCacc Bu2JpsiK"  
    => "-y 2011 -m,bmm2Reader.2e33-Bu2JpsiK,cbmm-2011-$version-2e33-accBu2JpsiK-*,$version-2011-2e33-accBu2JpsiK.root"
    #
    , "normMCfilter Bs2JpsiPhi"  
    => "-y 2011 -m,bmm2Reader.mix-Bs2JpsiPhi,cbmm-2011-$version-mix-Bs2JpsiPhi-*,$version-2011-mix-Bs2JpsiPhi.root"
    , "normMCacc Bs2JpsiPhi"  
    => "-y 2011 -m,bmm2Reader.mix-Bs2JpsiPhi,cbmm-2011-$version-2e33-accBs2JpsiPhi-*,$version-2011-2e33-accBs2JpsiPhi.root"
    #
    , "slMCacc Bd2PiMuNu"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2PiMuNu,cbmm-2011-$version-2e33-accBd2PiMuNu-*,$version-2011-2e33-accBd2PiMuNu.root"
    #
    , "rareMC Bs2KMuNu"  
    => "-y 2011 -m,bmm2Reader.2e33-Bs2KMuNu,cbmm-2011-$version-2e33-Bs2KMuNu-*,$version-2011-2e33-Bs2KMuNu.root"
    , "rareMC Bd2PiMuNu"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2PiMuNu,cbmm-2011-$version-2e33-Bd2PiMuNu-*,$version-2011-2e33-Bd2PiMuNu.root"
    , "rareMC Lb2PMuNu"  
    => "-y 2011 -m,bmm2Reader.2e33-Lb2PMuNu,cbmm-2011-$version-2e33-Lb2PMuNu-*,$version-2011-2e33-Lb2PMuNu.root"
    , "rareMC Bs2KK"  
    => "-y 2011 -m,bmm2Reader.2e33-Bs2KK,cbmm-2011-$version-2e33-Bs2KK-*,$version-2011-2e33-Bs2KK.root"
    , "rareMC Bs2KPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bs2KPi,cbmm-2011-$version-2e33-Bs2KPi-*,$version-2011-2e33-Bs2KPi.root"
    , "rareMC Bs2PiPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bs2PiPi,cbmm-2011-$version-2e33-Bs2PiPi-*,$version-2011-2e33-Bs2PiPi.root"
    , "rareMC Bd2KK"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2KK,cbmm-2011-$version-2e33-Bd2KK-*,$version-2011-2e33-Bd2KK.root"
    , "rareMC Bd2KPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2KPi,cbmm-2011-$version-2e33-Bd2KPi-*,$version-2011-2e33-Bd2KPi.root"
    , "rareMC Bd2PiPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2PiPi,cbmm-2011-$version-2e33-Bd2PiPi-*,$version-2011-2e33-Bd2PiPi.root"
    , "rareMC Bd2RhoPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bd2RhoPi,cbmm-2011-$version-2e33-Bd2RhoPi-*,$version-2011-2e33-Bd2RhoPi.root"
    , "rareMC Lb2KP"  
    => "-y 2011 -m,bmm2Reader.2e33-Lb2KP,cbmm-2011-$version-2e33-Lb2KP-*,$version-2011-2e33-Lb2KP.root"
    , "rareMC Lb2PiP"  
    => "-y 2011 -m,bmm2Reader.2e33-Lb2PiP,cbmm-2011-$version-2e33-Lb2PiP-*,$version-2011-2e33-Lb2PiP.root"
    , "slMC Bu2PiMuMu"  
    => "-y 2011 -m,bmm2Reader.2e33-Bu2PiMuMu,cbmm-2011-$version-2e33-Bu2PiMuMu-*,$version-2011-2e33-Bu2PiMuMu.root"
    , "rareMC Bu2JpsiPi"  
    => "-y 2011 -m,bmm2Reader.2e33-Bu2JpsiPi,cbmm-2011-$version-2e33-Bu2JpsiPi-*,$version-2011-2e33-Bu2JpsiPi.root"
    , "rareMC Bu2MuMuK"  
    => "-y 2011 -m,bmm2Reader.2e33-Bu2MuMuK,cbmm-2011-$version-2e33-Bu2KMuMu-*,$version-2011-2e33-Bu2MuMuK.root"
    , "rareMC Bs2PhiMuMu"  
    => "-y 2011 -m,bmm2Reader.2e33-Bs2PhiMuMu,cbmm-2011-$version-2e33-Bs2PhiMuMu-*,$version-2011-2e33-Bs2PhiMuMu.root"
    , "rareMC Bd2DstarPi"  
    => "-y 2011 -m,bmm2Reader.Bd2DstarPi.2011,cbmm-2011-$version-2e33-Bd2DstarPi-*,$version-2011-2e33-Bd2DstarPi.root"
    #
    , "data 2011 bmm"  
    => "-y 2011 -b 1,bmm2Reader.2011,cbmm-2011-$version-MuOnia__Run2011*,$version-2011-bmm-data.root"
    );

# -- reformat the entries to correct for the newlines
foreach $j (keys %jobs) {
    $jobs{$j} =~ s%\n%%g;
}


# ----------------------------------------------------------------------
# -- mirror to local scratch disk
if ($opt_m ne "") {
    &callM;
    die "done with mirroring to $opt_m\n";
}


# ----------------------------------------------------------------------
# -- run hadd instead of submitting
if ($opt_h) {
    callH(); 
    die "running hadd\n";
}

# ----------------------------------------------------------------------
# -- submit the jobs
foreach $j (keys %jobs) {
    ($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
    if ($opt_s && !($j =~ /$opt_s/)) {next;}
    if ($j =~ /data/) {
	$command = "$runCommand -q $queue -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/data' $dataset"; 
    } else {
	$command = "$runCommand -q $queue -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage/mc' $dataset"; 
    }

    if ($opt_d) {
	#$command = "$runCommand -q all.q -x 'bin/runBmm2 $options -C cuts/$cutfile' -r 'STORAGE1 $storage' $dataset";
	print "$command \n";
    } else {
	print "$command\n";
	system($command);
    }

}

die "this is the end ... \n";



# ----------------------------------------------------------------------
sub callM() {
    foreach $j (keys %jobs) {
	($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	print "$srmcmd $storage/$output $srmpf$scratch/$opt_m/$output\n";
	system("$srmcmd $storage/$output $srmpf$scratch/$opt_m/$output");
    }
    die "done with copy to local scratch area\n";
}


# ----------------------------------------------------------------------
sub callH() {
    print "srmls $storage/data |grep root \n";
    print "srmls $storage/mc |grep root \n";
    @dlines = `srmls $storage/data |grep root `;
    @mlines = `srmls $storage/mc |grep root `;
    
    push(@lines, @dlines); 
    push(@lines, @mlines); 

    foreach $j (keys %jobs) {
	if ($opt_s && !($j =~ /$opt_s/)) {next;}

	($options, $cutfile, $dataset, $output) = split(/,/, $jobs{$j});
	
	$dataset =~ s/-\*//;
	$dataset =~ s/\*/.\*/g;
	@vdataset = split(/ /, $dataset); 
	print "dataset = $dataset\n";
	print "file = $output\n";
	my @rootfiles = (); 
	foreach $ds (@vdataset) {
	    @rf = grep(/$ds/, @lines); 
	    push(@rootfiles, @rf); 
	}
	@rootfiles = grep(/\.root/, @rootfiles); 
	@rootfiles = grep(s/\n//, @rootfiles); 
	if ($#rootfiles == 0) {
	    @rootfiles = grep(s/.*$user\/$rootdir\///, @rootfiles); 
	    if ($opt_d) {
		print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";
		print "$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output \n";
	    } else {
		print "$srmcmd $storage/$rootfiles[0] $storage/$output \n";
		print "$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output \n";
		system("srmrm $storage/$output");
		system("$srmcmd $storage/$rootfiles[0] $storage/$output");
		system("$srmcmd $storage/$rootfiles[0] $srmpf$scratch/$output");
	    }	    
	} elsif ($#rootfiles > 0) {
	    @rootfiles = grep(s/.*\/trivcat/$dcap/, @rootfiles); 
	    @rootfiles = sort @rootfiles; 

	    if ($opt_d) {
		print "srmrm $storage/$output \n";
		print "hadd $scratch/$output @rootfiles\n";
		foreach $f (@rootfiles) {print "  $f\n";}
		print "srmls $storage/$output \n";
		print "$srmcmd $srmpf$scratch/$output $storage/$output \n";
	    } else {
		#print "hadd $scratch/$output @rootfiles\n";
		if (-e "$scratch/$output") {unlink("$scratch/$output"); }
		system("hadd $scratch/$output @rootfiles");
		system("srmrm $storage/$output");
		system("$srmcmd $srmpf$scratch/$output $storage/$output");
	    }
	}
    }
    
    die "that's it \n";
}



# ----------------------------------------------------------------------
sub callA() {

#    my $datasplit = 350000; 
#    my $mcsplit   = 700000; 

    my $datasplit = 400000; 
    my $mcsplit   = 500000; 
    
    @data = (
	"splitCheckedChain -n $datasplit ../cbmm-2011-v16-MuOnia__Run2011A-08Nov2011-v1", 
	"splitCheckedChain -n $datasplit ../cbmm-2011-v16-MuOnia__Run2011B-19Nov2011-v1" 
	);
    
    @signal = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-mix-Bs2MuMu",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-mix-Bd2MuMu",
	"splitCheckedChain -n $mcsplit ../cbmm-mc-2011-v16-BsToMuMu_M-51",
	"splitCheckedChain -n $mcsplit ../cbmm-mc-2011-v16-BsToMuMu_M-57"
	);
    
    @normalization = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-mix-Bu2JpsiK",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-accBu2JpsiK"
	); 
    
    @controlsample = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-mix-Bs2JpsiPhi",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-accBs2JpsiPhi"
	); 
    
    @rareBs = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bs2KK",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bs2KMuNu",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bs2KPi",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bs2PhiMuMu",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bs2PiPi"
	);
    
    @rareBd = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2KK",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2KPi",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2PiMuNu",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2PiPi",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2RhoPi",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bd2DstarPi", 
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-accBd2PiMuNu" 
	);
    
    @rareBu = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bu2JpsiPi", 
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bu2KMuMu", 
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Bu2PiMuMu"
	); 
    
    @rareLb = (
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Lb2KP",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Lb2PMuNu",
	"splitCheckedChain -n $mcsplit ../cbmm-2011-v16-2e33-Lb2PiP"
	);

    foreach $c (@data, @signal, @normalization, @controlsample, @rareBs, @rareBd, @rareBu, @rareLb) {
	system("$c");
    }


}

