#!/usr/bin/env perl

# usage: se2se [-n 4] [-s T2_CH_CSCS] [-t T3_CH_PSI] -d /store/user/bstomumu/v14/cmsRun/2012/data-hadronic-nonMuon/B

use Getopt::Std;
getopts('d:n:p:s:t:');

if (!$opt_s) { 
    $opt_s = "T2_CH_CSCS";
}

if ($opt_s eq "T2_CH_CSCS") {
    $sPrefix  = "srm://storage01.lcg.cscs.ch:8443/srm/managerv2\\?SFN=/pnfs/lcg.cscs.ch/cms/trivcat";
}

if ($opt_s eq "T3_CH_PSI") {
    $sPrefix  = "srm://t3se01.psi.ch:8443/srm/managerv2\?SFN=/pnfs/psi.ch/cms/trivcat";
}

if (!$opt_t) {
    $opt_t = "T3_CH_PSI";
}

if (!$opt_n) {
    $opt_n = 4;
}

if ($opt_t eq "T3_CH_PSI") {
    $tPrefix  = "srm://t3se01.psi.ch:8443/srm/managerv2\?SFN=/pnfs/psi.ch/cms/trivcat";
    $tMount   = "/pnfs/psi.ch/cms/trivcat";
}

my $drexe = "/shome/ursl/perl/data_replica.py --streams=$opt_n";

my $srmLsOptions = "\\.root\$";
if ($opt_p) {
    $srmLsOptions .= " $opt_p";
}
my $dr = "dr.$$";
my $cmd = "srmLs -x $sPrefix/$opt_d -C -p $srmLsOptions |sort";
system("$cmd > $dr");

# -- check that target directory exists
if (!-d "$tMount/$opt_d") {
    print "SE directory $tMount/$opt_d does not yet exist .. create it now\n";
    system("srmmkdir $tPrefix/$opt_d");
}

# -- now transfer
$cmd = "$drexe --from-site $opt_s --to-site $opt_t $dr $opt_d";
system("$cmd");

