#!/usr/bin/env perl

#  ./link 0 1293

use Getopt::Std;
getopts('');

if ($#ARGV < 1) {
    die "usage: ./link 0 1293\n";
}

$link = shift; 
$numb = shift; 

print "link: $link .. numb: $numb\n";
if ($numb < 2) {
    die "usage: ./link 0 1293\n";
}

@types = ("even", "odd"); 

foreach $type (@types) {
    
    $xmlfile0  = "TMVA-".$link."-".$type."_BDT.weights.xml"; 
    $xmlfile1  = "TMVA-".$numb."-".$type."_BDT.weights.xml"; 
    
    $rootfile0 = "TMVA-".$link."-".$type.".root"; 
    $rootfile1 = "TMVA-".$numb."-".$type.".root"; 
   
    print "ln -s $xmlfile1 $xmlfile0\n";
    print "ln -s $rootfile1 $rootfile0\n";    
    
    system("rm -f $xmlfile0 $rootfile0 ");
    system("ln -s $xmlfile1 $xmlfile0");
    system("ln -s $rootfile1 $rootfile0");
}

$combined0 = "TMVA-".$link."-combined.root"; 
$combined1 = "TMVA-".$numb."-combined.root"; 
system("rm -f $combined0 ");
print "ln -s $combined1 $combined0\n";
system("ln -s $combined1 $combined0");
