#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS :  -p: dry-run

#===============================================================
# Directory
# ---------
# $dir      = "/home/ceggel/new/test";
# $crab      = "/home/ceggel/new/test/test-crab";
# $output = "test";
#
#===============================================================


use Getopt::Std;
getopts('p');

print "\n";

$dir = `pwd`; chop($dir);
$crab = "$dir/test-crab";

chdir($crab);
@files = `ls -1 crab-*.cfg`;


if ( !$opt_p ) { open(LOG, ">cmsRun.crab.log"); }

foreach $file ( @files ) {

    chop($file);

    $date = `date`; chop($date);

    $ui_work = `grep ui_working_dir $file`;
    @run = split(/\//,$ui_work);
    $workdir = @run[$#run]; chop($workdir);

    if ( $file eq "crab-test.cfg" ) { next; }
    if ( $file eq "crab-bmm.cfg" ) { next; }

    if ( ($file eq "crab-bmm.cfg") || 
	  ($file eq "crab-BB.cfg") || 
	  ($file eq "crab-CC.cfg")
	 ) {
	
	$channel = "default";

    } else {
	
	$channel = $workdir;
    }

    
    print "\n ---> Changing default channel to $channel for $file\n\n";
    system("perl -pi -e \"s\/default\/$channel\/g\" test-crab.cfg");
    #system("cp test-crab.cfg test-crab.$channel.cfg");

    if ( !$opt_p ) {     

       if ( -d $workdir ) { 

         print LOG "$date directory $workdir exist, skipping\n";
       
        } else {
 
	  print LOG "$date \"crab -create -cfg $file\"\n";
	  system("crab -create -cfg $file");

          system("cp test-crab.cfg $workdir/test-crab.cfg");

	  print LOG "$date \"crab -submit -c $workdir\"\n\n";		
	  system("crab -submit -c $workdir");
          sleep 360;
      }
    } else {

        if ( -d $workdir ) { 
          print "$date directory $workdir exists, skipping\n"; 
        } else {
	  print "$date \"crab -create -cfg $file\"\n";
	  print "$date \"crab -submit -c $workdir\"\n\n";
        }
    }

    system("perl -pi -e \"s\/$channel\/default\/g\" test-crab.cfg");

}

if ( !$opt_p ) { close(LOG); }
