#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS :  -p: dry-run

#===============================================================
# Directory
# ---------
# $dir      = "/home/ceggel/new/test";
# $crab      = "/home/ceggel/new/test/test-crab";
# $output = "test";
#
#===============================================================


use Getopt::Std;
getopts('p');

print "\n";

$dir = `pwd`; chop($dir);
$crab = "$dir/test-crab";

chdir($crab);
@files = `ls -1 crab-*.cfg`;


if ( !$opt_p ) { open(LOG, ">cmsRun.crab.log"); }

foreach $file ( @files ) {

    $date = `date`; chop($date);

    chop($file);

    ($crabfile, $ext) = split(/\./, $file);
    ($p1, $p2) = split(/\-/, $crabfile);
    $beginswith = substr($p2, 0, 3);

    $ui_work = `grep ui_working_dir $file`;
    @run = split(/\//,$ui_work);
    $workdir = @run[$#run]; chop($workdir);

    if ( $p2 eq "test" ) {

	next; 
    }

    if ( $p2 eq "bmm" ||
	 $p2 eq "BB" ||
	 $p2 eq "CC" ||
	 $p2 eq "bbartojpsi" ||
	 $p2 eq "btojpsi" ||
	 $p2 eq "muonppmux" ||
	 $p2 eq "ppmux" ||
	 $p2 eq "charmonium1" ||
	 $p2 eq "charmonium2" ||
	 $beginswith eq "qcd"
	 ) {
	
	$channel = "default";

    } else {
	
	$channel = $workdir;
    }

    
    print "\n ---> Changing default channel to $channel for $file\n\n";
    system("perl -pi -e \"s\/default\/$channel\/g\" test-crab.cfg");
    #system("cp test-crab.cfg test-crab.$channel.cfg");

    if ( !$opt_p ) {     

	if ( -d $workdir ) { 

	    print LOG "$date directory $workdir exist, skipping\n";
	    
	} else {
	    
	    print LOG "$date \"crab -create -cfg $file\"\n";
	    system("crab -create -cfg $file");
	    
	    system("cp test-crab.cfg $workdir/test-crab.cfg");
	    
	    print LOG "$date \"crab -submit -c $workdir\"\n\n";		
	    system("crab -submit -c $workdir");
	    sleep 360;
	}
	
    } else {
	
        if ( -d $workdir ) { 
          print "$date directory $workdir exists, skipping\n"; 
      } else {
	  print "$date \"crab -create -cfg $file\"\n";
	  print "$date \"crab -submit -c $workdir\"\n\n";
      }
    }
    
    system("perl -pi -e \"s\/$channel\/default\/g\" test-crab.cfg");

}

if ( !$opt_p ) { close(LOG); }
