#! /usr/bin/perl
#
#==============================================================================================
#
# OPTIONS :   -s:                     path on SE

#==============================================================================================
# Directory
# ---------
# $dir  = "/home/ceggel/workspace/test";
# $rare = "/home/ceggel/workspace/test/test-crab";
#
#==============================================================================================

use Getopt::Std;
getopts('s:');

print "\n";

if ( $opt_s ) {

    $se = $opt_s;

} else {

    print "\n ----> please specify a directory on the SE with option -s !!!\n";
    print "\n ----> Example: ";
    print "\n                   ./mkAll -s  analysed_Spring07_noHLT_new \n";
    print "\n           =>  storage_path = /pnfs/lcg.cscs.ch/cms/local/eggel/analysed_Spring07_noHLT_new\n";
    print "\n ----> ABORTING ... \n\n";
    exit;
}


$dir = `pwd`; chop($dir);

chdir($dir);

$dir2 = $dir;
$se2 = $se;

$dir =~ s/\//\\\//g;
$se =~ s/\//\\\//g;

print "Setting WORKDIR to \"$dir2\"\n";
system("perl -pi -e \"s/WORKDIR/$dir/g\" crab-*.cfg");

print "Setting PATH on SE to \"$se2\"\n";
system("perl -pi -e \"s/PATHSE/$se/g\" crab-*.cfg");

print "\n";

